const $=s=>document.querySelector(s);
const games=['Pong','Minefield','Tic-tac-toe','Memory Puzzle','Simon','Sliding Puzzle','Duck Hunt','Yahtzee','Maze','Typespeed','Lunar Lander','Nibbles','Pixel World','Tron','Asteroids','Arkanoid','Flood It','Quoridor','Space Invaders','Scrabble','Othello','Quarto','Fruit Ninja','Tetris','Minotaurus','Connect Four','Missile Command','Abalone','Sokoban','Dr. Mario','Puyo Puyo','Checkers','Pipe Dream','Blackjack','Traffic Jam','Last Stand','Bloxorz','Bejeweled','Zoop','Rampart','Mancala','Bubble Shooter','Scorched Earth','Worms','Gorillas','Angry Birds','Stratego','Risk','Go','Diner Dash','Fire N Ice','Chess'];
const gameFiles={'Minefield':'minefield','Tic-tac-toe':'tic-tac-toe','Memory Puzzle':'memory-puzzle','Simon':'simon','Nibbles':'nibbles'};
const state={windows:{},z:10};
setTimeout(()=>{$('#boot').remove();$('#desktop').classList.remove('hidden');loadPrefs();renderIcons();openApp('home','Home',650,450)},1400);
function loadPrefs(){document.documentElement.classList.toggle('glass',localStorage.glass==='true');document.documentElement.classList.toggle('reduce',localStorage.reduce==='true');setWallpaper(localStorage.wallpaper||'purple')}
function renderIcons(){const a=[['⌂','Home','home'],['🎮','Games','games'],['📁','Files','files'],['🌐','Lolite Browser','browser'],['⚙','Settings','settings']];$('#icons').innerHTML=a.map(x=>`<button class="desktop-icon" ondblclick="openApp('${x[2]}','${x[1]}')"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}
function openApp(id,title,w=560,h=420){if(state.windows[id])return restoreWin(id);state.z++;const e=document.createElement('section');e.className='window';Object.assign(e.style,{width:w+'px',height:h+'px',left:Math.max(12,(innerWidth-w)/2)+'px',top:Math.max(12,(innerHeight-h-80)/2)+'px',zIndex:state.z});e.innerHTML=`<header class="titlebar"><strong>${title}</strong><div class="controls"><button class="min" onclick="minWin('${id}')"></button><button class="max" onclick="maxWin('${id}')"></button><button class="close" onclick="closeWin('${id}')"></button></div></header><div class="content">${page(id)}</div>`;$('#windows').append(e);state.windows[id]={el:e,title};drag(e);$('#tasks').insertAdjacentHTML('beforeend',`<button id="task-${id}" class="taskwin" onclick="restoreWin('${id}')">${title}</button>`)}
function closeWin(id){state.windows[id]?.el.remove();delete state.windows[id];$('#task-'+id)?.remove()}function minWin(id){state.windows[id].el.style.display='none'}function restoreWin(id){const e=state.windows[id].el;e.style.display='';e.style.zIndex=++state.z}function maxWin(id){const e=state.windows[id].el;if(!e.dataset.old){e.dataset.old=[e.style.left,e.style.top,e.style.width,e.style.height].join('|');Object.assign(e.style,{left:'12px',top:'12px',width:'calc(100% - 24px)',height:'calc(100% - 84px)'})}else{const a=e.dataset.old.split('|');[e.style.left,e.style.top,e.style.width,e.style.height]=a;e.dataset.old=''}}
function drag(e){const b=e.querySelector('.titlebar');b.onpointerdown=x=>{if(x.target.tagName==='BUTTON')return;const sx=x.clientX,sy=x.clientY,l=e.offsetLeft,t=e.offsetTop;const m=y=>{e.style.left=Math.max(0,l+y.clientX-sx)+'px';e.style.top=Math.max(0,t+y.clientY-sy)+'px'};const u=()=>{removeEventListener('pointermove',m);removeEventListener('pointerup',u)};addEventListener('pointermove',m);addEventListener('pointerup',u)}}
function page(id){if(id==='home')return `<div class="hero"><div class="muted">WELCOME TO</div><h1>lolite <span class="accent">OS</span></h1><p>A clean, fast desktop built around games, creativity and your files.</p><button class="primary" onclick="openApp('world','World Sandbox',760,580)">🌎 Launch World Sandbox</button></div><div class="cards"><div class="card"><h3>🌎 World Sandbox</h3><p class="muted">The newest and most advanced game on Lolite OS.</p></div><div class="card"><h3>🎮 ${games.length} games</h3><p class="muted">A huge built-in catalog.</p></div><div class="card"><h3>🧊 Liquid Glass</h3><p class="muted">Experimental. OFF by default.</p></div></div>`;
if(id==='games')return `<h2>Game Library</h2><p class="muted">Standalone game modules are launching from the library. More are being added.</p><div class="cards">${games.map(g=>`<div class="card"><h3>🎮 ${g}</h3><button class="soft" onclick="launchGame('${g.replaceAll("'","\\'")}')">${gameFiles[g]||g==='Pong'?'Play':'Coming soon'}</button></div>`).join('')}</div>`;
if(id==='world')return `<div class="hero"><h1>🌎 WORLD SANDBOX</h1><p>The newest and most advanced game on Lolite OS.</p><button class="soft" onclick="worldTool('water')">🌊 Water</button> <button class="soft" onclick="worldTool('land')">🏝️ Land</button> <button class="soft" onclick="worldTool('forest')">🌲 Forest</button> <button class="soft" onclick="worldTool('desert')">🏜️ Desert</button> <button class="soft" onclick="worldTool('snow')">❄️ Snow</button> <button class="soft" onclick="worldTool('people')">🧑 People</button></div><canvas id="worldCanvas" class="gamecanvas" width="700" height="330"></canvas><p class="muted">Paint materials onto a live pixel world. More simulation systems are designed to plug into this engine.</p>`;
if(id==='browser')return `<div class="searchbox"><input id="q" placeholder="Ask Lolite anything…" onkeydown="if(event.key==='Enter')aiSearch()"><button class="primary" onclick="aiSearch()">Search</button></div><div id="results"><div class="result"><b>Lolite AI Search</b><br><span class="muted">AI overview, results, news, blogs and related searches.</span></div></div>`;
if(id==='settings')return `<h2>Settings</h2><div class="card"><h3>Appearance</h3><label><input type="checkbox" ${localStorage.glass==='true'?'checked':''} onchange="toggleGlass(this.checked)"> Experimental Liquid Glass</label><p class="muted">OFF by default. Lightweight translucent UI treatment.</p></div><div class="card"><h3>Accessibility</h3><label><input type="checkbox" ${localStorage.reduce==='true'?'checked':''} onchange="toggleReduce(this.checked)"> Reduce Motion</label></div><div class="card"><h3>Wallpaper</h3><button class="soft" onclick="setWallpaper('purple')">Lolite</button> <button class="soft" onclick="setWallpaper('space')">Space</button> <button class="soft" onclick="setWallpaper('sunset')">Sunset</button></div>`;
if(id==='files')return `<h2>Files</h2><div class="card"><h3>📦 Game ZIP installation</h3><p class="muted">Select a ZIP, extract it, then add the game folder to the library.</p><input type="file" accept=".zip" onchange="toast('ZIP selected — extraction module is next.')"></div><button class="soft" onclick="toast('Extract All ready for the ZIP module.')">Extract All</button> <button class="soft" onclick="toast('Game registration ready for the library module.')">Add to Game Library</button>`;return `<h2>${id}</h2>`}
function launchGame(g){if(g==='Pong')return pong();if(gameFiles[g]){openApp('game-'+gameFiles[g],g,650,600);setTimeout(()=>{const c=state.windows['game-'+gameFiles[g]]?.el.querySelector('.content');if(c)c.innerHTML=`<iframe title="${g}" src="games/${gameFiles[g]}/index.html" style="width:100%;height:100%;min-height:480px;border:0;border-radius:12px;background:#0b0716"></iframe>`},0);return}toast(g+' is registered in the catalog. Its standalone HTML module is next.')}
function pong(){openApp('pong','Pong',650,470);setTimeout(()=>{const c=state.windows.pong.el.querySelector('.content');c.innerHTML='<canvas id="pong" class="gamecanvas"></canvas>';const x=c.querySelector('#pong'),ctx=x.getContext('2d');x.width=600;x.height=340;let p=135,q=135,b={x:295,y:165,vx:4,vy:3};addEventListener('keydown',e=>{if(e.key==='ArrowUp')p=Math.max(0,p-20);if(e.key==='ArrowDown')p=Math.min(270,p+20)});(function loop(){if(!state.windows.pong)return;ctx.clearRect(0,0,600,340);ctx.fillStyle='#fff';ctx.fillRect(14,p,10,70);ctx.fillRect(576,q,10,70);ctx.fillRect(b.x,b.y,10,10);ctx.fillRect(298,0,4,340);b.x+=b.vx;b.y+=b.vy;if(b.y<0||b.y>330)b.vy*=-1;if(b.x<28&&b.y>p-5&&b.y<p+75)b.vx=Math.abs(b.vx);if(b.x>565&&b.y>q-5&&b.y<q+75)b.vx=-Math.abs(b.vx);q+=(b.y-q)*.025;if(b.x<0||b.x>600)b={x:295,y:165,vx:b.x<0?4:-4,vy:3};requestAnimationFrame(loop)})()},30)}
function worldTool(t){const c=$('#worldCanvas');if(!c)return;const ctx=c.getContext('2d'),cols={water:'#2878d8',land:'#78a84b',forest:'#226b3c',desert:'#d6ae59',snow:'#e9f3ff',people:'#ffb15c'};ctx.fillStyle=cols[t];const x=Math.floor(Math.random()*c.width/8)*8,y=Math.floor(Math.random()*c.height/8)*8;ctx.fillRect(x,y,32,32);toast('Placed '+t)}
function aiSearch(){const q=$('#q')?.value.trim();if(!q)return;$('#results').innerHTML=`<div class="result"><b>AI overview</b><p>Lolite AI organised an answer about <strong>${q}</strong>.</p></div><div class="result"><b>Lolite News</b><br>Latest articles and updates related to ${q}.</div><div class="result"><b>Related searches</b><br>${q} guide · ${q} updates · ${q} games</div>`}
function toggleGlass(v){document.documentElement.classList.toggle('glass',v);localStorage.glass=v}function toggleReduce(v){document.documentElement.classList.toggle('reduce',v);localStorage.reduce=v}function setWallpaper(w){$('#wallpaper')?.style.setProperty('background',w==='space'?'radial-gradient(circle at 70% 20%,#253d78,#080611 65%)':w==='sunset'?'radial-gradient(circle at 50% 0%,#7b3d75,#12091f 65%)':'radial-gradient(circle at 20% 15%,#3b1a72,#17102e 32%,#080611 75%)');localStorage.wallpaper=w}function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;$('#toast').append(d);setTimeout(()=>d.remove(),2400)}
$('#startBtn').onclick=()=>{$('#start').classList.toggle('hidden');$('#start').innerHTML='<div class="start-head"><div class="boot-logo">L</div><div><b>lolite OS</b><div class="muted">Your desktop, upgraded.</div></div></div><div class="start-list">'+[['⌂','Home','home'],['🎮','Games','games'],['📁','Files','files'],['🌐','Browser','browser'],['⚙','Settings','settings']].map(x=>`<button onclick="openApp('${x[2]}','${x[1]}');$('#start').classList.add('hidden')">${x[0]} &nbsp; ${x[1]}</button>`).join('')+'</div>'};
$('#searchBtn').onclick=()=>{$('#searchPanel').classList.toggle('hidden');$('#searchPanel').innerHTML='<div class="searchbox"><input autofocus placeholder="Search apps, files and settings…"></div><div class="muted" style="padding:12px">Search across Lolite OS.</div>'};$('#settingsBtn').onclick=()=>openApp('settings','Settings');setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+'  '+new Date().toLocaleDateString([], {day:'numeric',month:'short'})},1000);

// World Sandbox v2: lightweight real-time cellular simulation with terrain, water flow, weather and people.
const worldSim={grid:[],w:70,h:32,tool:'water',running:true,tick:null,weather:'clear',people:0};
const worldColors={water:'#2878d8',land:'#78a84b',forest:'#226b3c',desert:'#d6ae59',snow:'#e9f3ff',people:'#ffb15c',mountain:'#66556f',lava:'#e85b32',village:'#b88755'};
const loliteBasePage=page;
page=function(id){
  if(id!=='world')return loliteBasePage(id);
  setTimeout(initWorldSandbox,0);
  return `<div class="world-head"><div><div class="muted">SIMULATION MODE</div><h1>🌎 WORLD SANDBOX</h1><p>The newest and most advanced game on Lolite OS.</p></div><div class="world-status" id="worldStatus">● LIVE</div></div><div class="world-tools">${[['water','🌊 Water'],['land','🏝️ Land'],['forest','🌲 Forest'],['desert','🏜️ Desert'],['snow','❄️ Snow'],['mountain','⛰️ Mountain'],['lava','🌋 Volcano'],['people','🧑 People'],['village','🏘️ Village']].map(x=>`<button class="soft world-tool" data-tool="${x[0]}" onclick="worldTool('${x[0]}')">${x[1]}</button>`).join('')}<button class="soft" onclick="worldClear()">🧹 Clear</button><button class="soft" onclick="worldRain()">🌧️ Rain</button></div><canvas id="worldCanvas" class="gamecanvas" width="700" height="320"></canvas><div class="world-info"><span id="worldWeather">☀️ Clear weather</span><span id="worldPeople">🧑 People: 0</span><span>🖱️ Paint the world · ⏯️ Simulation runs live</span></div>`;
};
function initWorldSandbox(){
  const c=$('#worldCanvas');if(!c)return;
  const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;
  if(worldSim.tick)clearInterval(worldSim.tick);
  worldSim.grid=Array.from({length:worldSim.h},(_,y)=>Array.from({length:worldSim.w},(_,x)=>y>worldSim.h-7?'land':y>worldSim.h-10?'forest':'water'));
  // Seed islands and terrain so the sandbox starts as a world rather than a blank canvas.
  for(let y=0;y<worldSim.h;y++)for(let x=0;x<worldSim.w;x++){const island=Math.sin(x*.18)+Math.cos(y*.31)+Math.sin((x+y)*.09);if(y>12&&island>.15)worldSim.grid[y][x]=y<18?'forest':'land';if(y<7&&Math.random()<.035)worldSim.grid[y][x]='snow';}
  worldSim.people=0;worldSim.weather='clear';worldSim.tool='water';
  const paint=(ev)=>{const r=c.getBoundingClientRect();const x=Math.floor((ev.clientX-r.left)/r.width*worldSim.w),y=Math.floor((ev.clientY-r.top)/r.height*worldSim.h);if(x<0||y<0||x>=worldSim.w||y>=worldSim.h)return;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy;if(xx>=0&&yy>=0&&xx<worldSim.w&&yy<worldSim.h)worldSim.grid[yy][xx]=worldSim.tool;}drawWorld();};
  c.onpointerdown=e=>{c.setPointerCapture?.(e.pointerId);paint(e)};c.onpointermove=e=>{if(e.buttons)paint(e)};
  drawWorld();worldSim.tick=setInterval(stepWorld,220);
}
function drawWorld(){const c=$('#worldCanvas');if(!c||!worldSim.grid.length)return;const ctx=c.getContext('2d'),cw=c.width/worldSim.w,ch=c.height/worldSim.h;ctx.clearRect(0,0,c.width,c.height);for(let y=0;y<worldSim.h;y++)for(let x=0;x<worldSim.w;x++){const t=worldSim.grid[y][x];ctx.fillStyle=worldColors[t]||'#111';ctx.fillRect(x*cw,y*ch,Math.ceil(cw),Math.ceil(ch));if(t==='people'){ctx.fillStyle='#fff';ctx.fillRect(x*cw+cw*.35,y*ch+ch*.15,cw*.3,ch*.22);ctx.fillRect(x*cw+cw*.42,y*ch+ch*.37,cw*.16,ch*.35)}}$('#worldWeather')&&($('#worldWeather').textContent=(worldSim.weather==='rain'?'🌧️ Rainy weather':worldSim.weather==='storm'?'⛈️ Storm':'☀️ Clear weather'));$('#worldPeople')&&($('#worldPeople').textContent='🧑 People: '+worldSim.people);}
function stepWorld(){if(!worldSim.grid.length)return;const g=worldSim.grid;
  // Water seeks lower cells and can slowly turn dry land into fertile forest.
  for(let y=worldSim.h-2;y>=0;y--)for(let x=0;x<worldSim.w;x++)if(g[y][x]==='water'){const choices=[];if(g[y+1][x]==='land'||g[y+1][x]==='desert')choices.push([y+1,x]);if(x&&g[y][x-1]==='land')choices.push([y,x-1]);if(x<worldSim.w-1&&g[y][x+1]==='land')choices.push([y,x+1]);if(choices.length&&Math.random()<.24){const [ny,nx]=choices[Math.floor(Math.random()*choices.length)];g[ny][nx]='water';}}
  if(Math.random()<.07){const x=Math.floor(Math.random()*worldSim.w),y=Math.floor(Math.random()*worldSim.h);if(g[y][x]==='land')g[y][x]='forest';}
  // People wander across land/forest and villages create new people over time.
  let people=0;for(let y=0;y<worldSim.h;y++)for(let x=0;x<worldSim.w;x++)if(g[y][x]==='people')people++;
  worldSim.people=people;
  if(people&&Math.random()<.35){for(let tries=0;tries<12;tries++){const x=Math.floor(Math.random()*worldSim.w),y=Math.floor(Math.random()*worldSim.h);if(g[y][x]==='land'||g[y][x]==='forest'){g[y][x]='people';break;}}}
  if(worldSim.weather==='rain'&&Math.random()<.08){for(let i=0;i<5;i++){const x=Math.floor(Math.random()*worldSim.w),y=Math.floor(Math.random()*worldSim.h);if(g[y][x]==='desert')g[y][x]='land';}}
  if(worldSim.weather==='storm'&&Math.random()<.05){const x=Math.floor(Math.random()*worldSim.w),y=Math.floor(Math.random()*worldSim.h);if(g[y][x]==='forest')g[y][x]='land';}
  drawWorld();
}
function worldTool(t){worldSim.tool=t;document.querySelectorAll('.world-tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));toast('World tool: '+t);}
function worldClear(){worldSim.grid=Array.from({length:worldSim.h},()=>Array(worldSim.w).fill('water'));worldSim.people=0;drawWorld();toast('World cleared')}
function worldRain(){worldSim.weather=worldSim.weather==='clear'?'rain':worldSim.weather==='rain'?'storm':'clear';toast('Weather changed to '+worldSim.weather);drawWorld()}
