/* Lolite OS App Store — installable apps with desktop shortcuts. */
(()=>{
 const css=`.appstore{height:100%;margin:-18px;background:#0e1117;color:#eef2f7;overflow:auto;padding:24px}.appstore-toolbar{display:flex;flex-direction:column;gap:12px;margin-bottom:18px}.appstore-toolbar input{width:100%;box-sizing:border-box;padding:11px 13px;border-radius:9px;border:1px solid #303949;background:#111722;color:#eef2f7}.appstore-tabs{display:flex;gap:7px;overflow:auto;padding-bottom:3px}.store-tab{white-space:nowrap;padding:8px 11px;border:1px solid #303949!important;background:#151b24!important;color:#aeb8c8!important;border-radius:999px!important;width:auto!important}.store-tab.active{background:#7065db!important;border-color:#8176ed!important;color:#fff!important}.appstore-card-meta{display:flex;justify-content:space-between;color:#8994a6;font-size:11px;text-transform:uppercase;letter-spacing:.04em;margin-bottom:7px}.app-uninstall{margin-top:7px;background:#251a20!important;border:1px solid #5a303c!important;color:#ffb8c5!important}.store-empty{padding:30px;text-align:center;color:#8f9aab}.appstore-head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:22px}.appstore-head h1{margin:4px 0;font-size:30px}.appstore-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.appstore-card{background:#171c25;border:1px solid #29313d;border-radius:13px;padding:17px;transition:.15s}.appstore-card:hover{transform:translateY(-2px);border-color:#414d61}.appstore-icon{width:48px;height:48px;border-radius:11px;display:grid;place-items:center;background:#202631;border:1px solid #39414d;box-shadow:0 5px 12px #0006;margin-bottom:13px;overflow:hidden}.appstore-icon .app-symbol{margin:0}.appstore-card h3{margin:0 0 5px}.appstore-card p{color:#919baa;font-size:13px;min-height:38px;line-height:1.45}.appstore-card button{width:100%;padding:9px;border-radius:8px;background:#7065db;color:#fff;font-weight:750}.appstore-card button.installed{background:#202833;border:1px solid #303a48}.appstore-note{margin-top:18px;color:#858f9e;font-size:12px}`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const apps=[
  {id:'lowlight-ai',name:'Lolite AI',icon:'app-ai',category:'AI & Tools',version:'1.0.0',featured:true,desc:'Your built-in AI assistant for questions, ideas and Lolite OS help.',open:()=>openApp('lowlight-ai','Lolite AI',720,600)},
  {id:'browser',name:'Lolite Browser',icon:'app-browser',category:'Internet',version:'1.0.0',featured:true,desc:'A clean browser workspace with tabs, navigation and direct web access.',open:()=>openApp('browser','Lolite Browser',900,650)},
  {id:'notes',name:'Quick Notes',icon:'app-notepad',category:'Productivity',version:'1.0.0',desc:'A lightweight place to keep notes directly inside Lolite OS.',open:()=>openApp('notes','Quick Notes',560,500)},
  {id:'calculator',name:'Calculator',icon:'app-calculator',category:'Utilities',version:'1.0.0',desc:'Fast everyday calculations with a clean Lolite interface.',open:()=>openApp('calculator','Calculator',430,520)},
  {id:'paint',name:'Lolite Paint',icon:'app-paint',category:'Creative',version:'1.0.0',desc:'Simple drawing and sketching tools for the desktop.',open:()=>openApp('paint','Lolite Paint',720,560)},
  {id:'lolite-powertoys',name:'Lolite PowerToys',icon:'app-utility',category:'System Tools',version:'1.0.0',desc:'A Lolite collection of handy desktop tools and productivity utilities.',open:()=>openUtility('Lolite PowerToys','System Tools')},
  {id:'lolite-windows-utility',name:'Lolite Windows Utility',icon:'app-utility',category:'System Tools',version:'1.0.0',desc:'A Lolite control center for setup, maintenance and common system tasks.',open:()=>openUtility('Lolite Windows Utility','System Tools')},
  {id:'lolite-wintoys',name:'Lolite Wintoys',icon:'app-utility',category:'System Tools',version:'1.0.0',desc:'A Lolite system-tweaking dashboard for settings and desktop maintenance.',open:()=>openUtility('Lolite Wintoys','System Tools')},
  {id:'lolite-process-lasso',name:'Lolite Process Manager',icon:'app-utility',category:'Performance',version:'1.0.0',desc:'Monitor running tasks and organise application performance controls.',open:()=>openUtility('Lolite Process Manager','Performance')},
  {id:'lolite-bleachbit',name:'Lolite Cleaner',icon:'app-utility',category:'Maintenance',version:'1.0.0',desc:'A Lolite privacy and cleanup workspace for temporary files and browser data.',open:()=>openUtility('Lolite Cleaner','Maintenance')},
  {id:'lolite-everything',name:'Lolite Everything',icon:'app-utility',category:'Files',version:'1.0.0',desc:'Ultra-fast local file and folder searching for your Lolite workspace.',open:()=>openUtility('Lolite Everything','Files')},
  {id:'lolite-7zip',name:'Lolite 7-Zip',icon:'app-utility',category:'Files',version:'1.0.0',desc:'A Lolite archive manager for creating, opening and extracting common archive formats.',open:()=>openUtility('Lolite 7-Zip','Files')},
  {id:'lolite-peazip',name:'Lolite PeaZip',icon:'app-utility',category:'Files',version:'1.0.0',desc:'A Lolite multi-format archive browser and extractor.',open:()=>openUtility('Lolite PeaZip','Files')},
  {id:'lolite-nanazip',name:'Lolite NanaZip',icon:'app-utility',category:'Files',version:'1.0.0',desc:'A modern Lolite archive tool designed around the desktop file experience.',open:()=>openUtility('Lolite NanaZip','Files')},
  {id:'lolite-total-commander',name:'Lolite Total Commander',icon:'app-utility',category:'Files',version:'1.0.0',desc:'A dual-pane Lolite file management workspace.',open:()=>openUtility('Lolite Total Commander','Files')},
  {id:'lolite-multicommander',name:'Lolite MultiCommander',icon:'app-utility',category:'Files',version:'1.0.0',desc:'A multi-pane file organisation workspace for Lolite OS.',open:()=>openUtility('Lolite MultiCommander','Files')},
  {id:'lolite-bulk-rename',name:'Lolite Bulk Rename',icon:'app-utility',category:'Files',version:'1.0.0',desc:'Rename groups of files with previewable search-and-replace rules.',open:()=>openUtility('Lolite Bulk Rename','Files')},
  {id:'lolite-hwinfo',name:'Lolite Hardware Info',icon:'app-utility',category:'Diagnostics',version:'1.0.0',desc:'A Lolite hardware information dashboard for browser-visible system details.',open:()=>openUtility('Lolite Hardware Info','Diagnostics')},
  {id:'lolite-cpu-z',name:'Lolite CPU Info',icon:'app-utility',category:'Diagnostics',version:'1.0.0',desc:'A compact Lolite processor and browser capability information panel.',open:()=>openUtility('Lolite CPU Info','Diagnostics')},
  {id:'lolite-disk-info',name:'Lolite Disk Info',icon:'app-utility',category:'Diagnostics',version:'1.0.0',desc:'A Lolite storage health and drive information dashboard.',open:()=>openUtility('Lolite Disk Info','Diagnostics')},
  {id:'lolite-windirstat',name:'Lolite Disk Map',icon:'app-utility',category:'Storage',version:'1.0.0',desc:'Visualise storage usage with a Lolite folder and space map.',open:()=>openUtility('Lolite Disk Map','Storage')},
  {id:'lolite-wiztree',name:'Lolite WizTree',icon:'app-utility',category:'Storage',version:'1.0.0',desc:'Quickly inspect which folders are using space in your Lolite workspace.',open:()=>openUtility('Lolite WizTree','Storage')},
  {id:'lolite-spacesniffer',name:'Lolite Space Sniffer',icon:'app-utility',category:'Storage',version:'1.0.0',desc:'A visual storage explorer for spotting large folders and files.',open:()=>openUtility('Lolite Space Sniffer','Storage')},
  {id:'lolite-sysinternals',name:'Lolite System Tools',icon:'app-utility',category:'Diagnostics',version:'1.0.0',desc:'A Lolite collection of advanced system-inspection tools and dashboards.',open:()=>openUtility('Lolite System Tools','Diagnostics')},
  {id:'lolite-sharex',name:'Lolite ShareX',icon:'app-utility',category:'Creative',version:'1.0.0',desc:'Capture, annotate and organise screenshots inside Lolite OS.',open:()=>openUtility('Lolite ShareX','Creative')},
  {id:'lolite-rainmeter',name:'Lolite Widgets',icon:'app-utility',category:'Personalisation',version:'1.0.0',desc:'Custom desktop widgets and live information panels for Lolite.',open:()=>openUtility('Lolite Widgets','Personalisation')},
  {id:'lolite-translucent-taskbar',name:'Lolite Translucent Taskbar',icon:'app-utility',category:'Personalisation',version:'1.0.0',desc:'Extra taskbar appearance controls for transparency and visual effects.',open:()=>openUtility('Lolite Translucent Taskbar','Personalisation')},
  {id:'lolite-explorer-patcher',name:'Lolite Explorer Customiser',icon:'app-utility',category:'Personalisation',version:'1.0.0',desc:'Customise the Lolite desktop, taskbar and file navigation experience.',open:()=>openUtility('Lolite Explorer Customiser','Personalisation')},
  {id:'lolite-autohotkey',name:'Lolite Hotkeys',icon:'app-utility',category:'Automation',version:'1.0.0',desc:'Create simple keyboard shortcuts and browser-safe desktop actions.',open:()=>openUtility('Lolite Hotkeys','Automation')},
  {id:'lolite-simplewall',name:'Lolite Firewall',icon:'app-utility',category:'Network',version:'1.0.0',desc:'A Lolite network-rules dashboard for browser-side connection preferences.',open:()=>openUtility('Lolite Firewall','Network')},
  {id:'lolite-portmaster',name:'Lolite Network Guard',icon:'app-utility',category:'Network',version:'1.0.0',desc:'A Lolite network privacy dashboard with connection visibility and controls.',open:()=>openUtility('Lolite Network Guard','Network')},
  {id:'lolite-wireshark',name:'Lolite Network Analyzer',icon:'app-utility',category:'Network',version:'1.0.0',desc:'A Lolite network-analysis interface for available browser networking information.',open:()=>openUtility('Lolite Network Analyzer','Network')},
  {id:'lolite-nirsoft',name:'Lolite Utilities Pack',icon:'app-utility',category:'Diagnostics',version:'1.0.0',desc:'A collection of small Lolite diagnostic and information utilities.',open:()=>openUtility('Lolite Utilities Pack','Diagnostics')},
  {id:'lolite-driver-tools',name:'Lolite Driver Tools',icon:'app-utility',category:'Maintenance',version:'1.0.0',desc:'A Lolite driver-information and maintenance dashboard.',open:()=>openUtility('Lolite Driver Tools','Maintenance')},
  {id:'lolite-driver-updater',name:'Lolite Driver Updater',icon:'app-utility',category:'Maintenance',version:'1.0.0',desc:'A Lolite interface for reviewing driver update information without silently changing your system.',open:()=>openUtility('Lolite Driver Updater','Maintenance')},
  {id:'lolite-ninite',name:'Lolite App Installer',icon:'app-utility',category:'Installers',version:'1.0.0',desc:'A Lolite bulk app setup workspace for selecting and organising software.',open:()=>openUtility('Lolite App Installer','Installers')},
  {id:'lolite-winstall',name:'Lolite Package Hub',icon:'app-utility',category:'Installers',version:'1.0.0',desc:'A Lolite package catalogue interface for discovering and organising apps.',open:()=>openUtility('Lolite Package Hub','Installers')},
  {id:'wallpaper-editor',name:'Wallpaper Editor',icon:'app-wallpaper',category:'Creative',version:'1.0.0',featured:true,desc:'Create custom Lolite wallpapers with gradients, glow, text and drawing tools.',open:()=>openApp('wallpaper-editor','Wallpaper Editor',900,650)}
];
 function openUtility(title,category){
  openApp('utility-'+title,title,790,570);
  setTimeout(function(){
   const w=state.windows['utility-'+title];if(!w)return;
   const c=w.el.querySelector('.content');
   const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
   let body='';
   if(category==='Diagnostics')body='<div class="hero"><div class="muted">LOLITE DIAGNOSTICS</div><h1>'+esc(title)+'</h1><div class="cards"><div class="card"><h3>Browser</h3><p class="muted">'+esc(navigator.userAgent)+'</p></div><div class="card"><h3>Display</h3><p class="muted">'+innerWidth+' × '+innerHeight+' · '+devicePixelRatio+'× pixel ratio</p></div><div class="card"><h3>System</h3><p class="muted">Online: '+(navigator.onLine?'Yes':'No')+' · Cores: '+(navigator.hardwareConcurrency||'Unknown')+'</p></div></div><button class="primary" onclick="window.loliteUtilityRefresh()">Refresh diagnostics</button></div>';
   else if(category==='Storage')body='<div class="hero"><div class="muted">LOLITE STORAGE</div><h1>'+esc(title)+'</h1><div id="utilityStats" class="cards"><div class="card"><h3>Storage</h3><p class="muted">Loading…</p></div></div><button class="primary" onclick="window.loliteUtilityStorage()">Scan storage</button></div>';
   else if(category==='Network')body='<div class="hero"><div class="muted">LOLITE NETWORK</div><h1>'+esc(title)+'</h1><div class="cards"><div class="card"><h3>Connection</h3><p class="muted">'+(navigator.onLine?'Online':'Offline')+'</p></div><div class="card"><h3>Connection type</h3><p class="muted">'+esc(navigator.connection?.effectiveType||'Not exposed by this browser')+'</p></div></div><button class="primary" onclick="window.loliteUtilityRefresh()">Refresh status</button></div>';
   else if(category==='Performance')body='<div class="hero"><div class="muted">LOLITE PERFORMANCE</div><h1>'+esc(title)+'</h1><div class="cards"><div class="card"><h3>CPU threads</h3><p class="muted">'+(navigator.hardwareConcurrency||'Unknown')+'</p></div><div class="card"><h3>Memory</h3><p class="muted">'+(performance.memory?Math.round(performance.memory.usedJSHeapSize/1048576)+' MB JS heap':'Browser does not expose JS heap data')+'</p></div><div class="card"><h3>Page timing</h3><p class="muted">'+Math.round(performance.now())+' ms since page load</p></div></div><button class="primary" onclick="window.loliteUtilityRefresh()">Refresh metrics</button></div>';
   else if(category==='Maintenance')body='<div class="hero"><div class="muted">LOLITE MAINTENANCE</div><h1>'+esc(title)+'</h1><p>Clean Lolite-managed optional app data without touching browser or operating-system files.</p><div class="card"><h3>Installed optional apps</h3><p class="muted">'+get().length+' installed.</p></div><button class="primary" onclick="window.loliteUtilityClearAppData()">Clear optional utility data</button></div>';
   else if(category==='Personalisation')body='<div class="hero"><div class="muted">LOLITE PERSONALISATION</div><h1>'+esc(title)+'</h1><p>Quick appearance controls.</p><div class="cards"><div class="card"><h3>Liquid Glass</h3><button class="soft" onclick="toggleGlass(!document.documentElement.classList.contains(\'glass\'))">Toggle Liquid Glass</button></div><div class="card"><h3>Reduce Motion</h3><button class="soft" onclick="toggleReduce(!document.documentElement.classList.contains(\'reduce\'))">Toggle Reduce Motion</button></div></div></div>';
   else if(category==='Automation')body='<div class="hero"><div class="muted">LOLITE AUTOMATION</div><h1>'+esc(title)+'</h1><p>Test keyboard shortcuts.</p><input id="hotkeyTest" placeholder="Click here and press a key" style="width:100%;box-sizing:border-box;padding:12px;border-radius:9px;border:1px solid #303949;background:#111722;color:#fff"><p id="hotkeyResult" class="muted">Waiting for input…</p></div>';
   else if(category==='Creative')body='<div class="hero"><div class="muted">LOLITE CREATIVE</div><h1>'+esc(title)+'</h1><p>Browser-safe screen capture.</p><button class="primary" onclick="window.loliteCaptureScreen()">Capture Screen</button><p class="muted">Your browser will ask which screen or window to share.</p><div id="capturePreview"></div></div>';
   else if(category==='Files')body='<div class="hero"><div class="muted">LOLITE FILES</div><h1>'+esc(title)+'</h1><p>Select local files to inspect them without uploading them.</p><input id="utilityFile" type="file" multiple style="max-width:100%"><div id="fileInfo" class="cards"></div></div>';
   else if(category==='Installers')body='<div class="hero"><div class="muted">LOLITE APP MANAGEMENT</div><h1>'+esc(title)+'</h1><p>Manage browser-based Lolite apps from the App Store.</p><button class="primary" onclick="openApp(\'appstore\',\'App Store\',980,700)">Open App Store</button></div>';
   else if(category==='System Tools')body='<div class="hero"><div class="muted">LOLITE SYSTEM TOOLS</div><h1>'+esc(title)+'</h1><div class="cards"><div class="card"><h3>System check</h3><p class="muted">Browser capabilities, storage and desktop state can be inspected here.</p></div><div class="card"><h3>Local</h3><p class="muted">Settings stay inside Lolite OS local storage.</p></div></div><button class="primary" onclick="window.loliteUtilityRefresh()">Run system check</button></div>';
   else body='<div class="hero"><div class="muted">LOLITE SOFTWARE · '+esc(category)+'</div><h1>'+esc(title)+'</h1><p>A working Lolite-native utility workspace.</p><button class="primary" onclick="window.loliteUtilityRefresh()">Run utility</button></div>';
   c.innerHTML=body;
   const inp=c.querySelector('#hotkeyTest');if(inp)inp.addEventListener('keydown',e=>{const r=c.querySelector('#hotkeyResult');if(r)r.textContent='Pressed: '+e.key+(e.ctrlKey?' + Ctrl':'')+(e.shiftKey?' + Shift':'')+(e.altKey?' + Alt':'')});
   const fi=c.querySelector('#utilityFile');if(fi)fi.addEventListener('change',()=>{const box=c.querySelector('#fileInfo');box.innerHTML=[...fi.files].map(f=>'<div class="card"><h3>'+esc(f.name)+'</h3><p class="muted">'+(f.type||'Unknown type')+' · '+(f.size/1024).toFixed(1)+' KB</p></div>').join('')});
  },0)
 }
 window.loliteUtilityRefresh=()=>toast('Utility refreshed');
 window.loliteUtilityStorage=async()=>{const el=document.querySelector('#utilityStats .card p');if(!el)return;try{const x=await navigator.storage?.estimate?.();el.textContent=x&&x.quota?Math.round((x.usage||0)/1048576)+' MB used of '+Math.round(x.quota/1048576)+' MB available':'Storage estimate is not exposed by this browser.'}catch{el.textContent='Storage estimate unavailable.'}};
 window.loliteUtilityClearAppData=()=>{localStorage.removeItem('loliteAppSearch');localStorage.removeItem('loliteUtilityState');toast('Optional utility data cleared')};
 window.loliteCaptureScreen=async()=>{try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true});const v=document.createElement('video');v.srcObject=stream;await v.play();const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;canvas.getContext('2d').drawImage(v,0,0);stream.getTracks().forEach(t=>t.stop());const box=document.querySelector('#capturePreview');if(box){const img=document.createElement('img');img.src=canvas.toDataURL('image/png');img.style.maxWidth='100%';img.style.borderRadius='10px';box.replaceChildren(img)}}catch{toast('Screen capture was cancelled or blocked')}};
 const key='loliteInstalledApps';const get=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};const save=x=>localStorage.setItem(key,JSON.stringify(x));
 window.loliteInstallApp=id=>{const a=apps.find(x=>x.id===id);if(!a)return;const list=get();if(!list.includes(id))list.push(id);save(list);render();if(window.renderIcons)window.renderIcons();toast(a.name+' installed')};
 window.loliteUninstallApp=id=>{save(get().filter(x=>x!==id));render();if(window.renderIcons)window.renderIcons();toast('App uninstalled')}; window.loliteUninstallAll=()=>{if(!get().length){toast('No optional apps are installed');return}if(!confirm('Uninstall all optional Lolite apps?'))return;save([]);render();if(window.renderIcons)window.renderIcons();toast('All optional apps uninstalled')};
 window.loliteOpenApp=id=>{const a=apps.find(x=>x.id===id);if(a)a.open()};
 function render(){const root=document.querySelector('.appstore');if(!root)return;const installed=get();root.innerHTML='<div class="appstore-head"><div><div class="muted">LOLITE SOFTWARE</div><h1>App Store</h1><div class="muted">Install apps, manage your library and discover Lolite tools.</div></div><span class="appstore-note">'+installed.length+' installed</span></div><div class="appstore-toolbar"><input id="appStoreSearch" placeholder="Search apps…" aria-label="Search apps"><div class="appstore-tabs" role="tablist">'+['All','Featured','Installed','AI & Tools','Productivity','Creative','Utilities','Internet','System Tools','Performance','Maintenance','Files','Diagnostics','Storage','Personalisation','Automation','Network','Installers'].map((f,i)=>'<button type="button" class="store-tab'+(i===0?' active':'')+'" data-filter="'+f+'" aria-pressed="'+(i===0?'true':'false')+'">'+f+'</button>').join('')+'</div></div><div id="appStoreGrid" class="appstore-grid"></div><div class="appstore-note">Apps are installed locally using Lolite OS preferences. Installing an app adds its shortcut to the desktop.</div>';const input=document.getElementById('appStoreSearch');const grid=document.getElementById('appStoreGrid');const tabs=root.querySelector('.appstore-tabs');let filter='All';const draw=()=>{const q=input.value.trim().toLowerCase();const list=apps.filter(a=>(filter==='All'||(filter==='Featured'&&a.featured)||(filter==='Installed'&&installed.includes(a.id))||(a.category===filter))&&(!q||a.name.toLowerCase().includes(q)||a.desc.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(a=>{const on=installed.includes(a.id);return '<article class="appstore-card"><div class="appstore-icon"><b class="app-symbol '+a.icon+'"></b></div><div class="appstore-card-meta"><span>'+a.category+'</span><span>v'+a.version+'</span></div><h3>'+a.name+'</h3><p>'+a.desc+'</p><button type="button" class="'+(on?'installed':'')+'" onclick="window.lolite'+(on?'OpenApp':'InstallApp')+'(\''+a.id+'\')">'+(on?'Open':'Install')+'</button>'+(on?'<button type="button" class="app-uninstall" onclick="window.loliteUninstallApp(\''+a.id+'\')">Uninstall</button>':'')+'</article>'}).join(''):'<div class="store-empty">No apps match your search.</div>'};input.addEventListener('input',draw);tabs.addEventListener('click',e=>{const b=e.target.closest('.store-tab');if(!b)return;filter=b.dataset.filter;tabs.querySelectorAll('.store-tab').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});draw()});draw()}
 const oldPage=window.page;window.page=function(id){if(id==='appstore'){setTimeout(render,0);return '<div class="appstore"><div class="store-empty">Loading App Store…</div></div>'}return oldPage(id)};
 const oldIcons=window.renderIcons;window.renderIcons=function(){oldIcons();const installed=get();const box=document.getElementById('icons');if(!box)return;apps.filter(a=>installed.includes(a.id)).forEach(a=>{const b=document.createElement('button');b.className='desktop-icon';b.ondblclick=()=>window.loliteOpenApp(a.id);b.innerHTML='<b class="app-symbol '+a.icon+'"></b><span>'+a.name+'</span>';box.appendChild(b)})};
})();
