/* Lolite OS App Store — installable apps with desktop shortcuts. */
(()=>{
 const css=`.appstore{height:100%;margin:-18px;background:#0e1117;color:#eef2f7;overflow:auto;padding:24px}.appstore-head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:22px}.appstore-head h1{margin:4px 0;font-size:30px}.appstore-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.appstore-card{background:#171c25;border:1px solid #29313d;border-radius:13px;padding:17px;transition:.15s}.appstore-card:hover{transform:translateY(-2px);border-color:#414d61}.appstore-icon{width:48px;height:48px;border-radius:11px;display:grid;place-items:center;background:#202631;border:1px solid #39414d;box-shadow:0 5px 12px #0006;margin-bottom:13px;overflow:hidden}.appstore-icon .app-symbol{margin:0}.appstore-card h3{margin:0 0 5px}.appstore-card p{color:#919baa;font-size:13px;min-height:38px;line-height:1.45}.appstore-card button{width:100%;padding:9px;border-radius:8px;background:#7065db;color:#fff;font-weight:750}.appstore-card button.installed{background:#202833;border:1px solid #303a48}.appstore-note{margin-top:18px;color:#858f9e;font-size:12px}`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const apps=[
  {id:'lowlight-ai',name:'Lolite AI',icon:'app-ai',category:'AI & Tools',version:'1.0.0',featured:true,desc:'Your built-in AI assistant for questions, ideas and Lolite OS help.',open:()=>openApp('lowlight-ai','Lolite AI',720,600)},
  {id:'browser',name:'Lolite Browser',icon:'app-browser',category:'Internet',version:'1.0.0',featured:true,desc:'A clean browser workspace with tabs, navigation and direct web access.',open:()=>openApp('browser','Lolite Browser',900,650)},
  {id:'notes',name:'Quick Notes',icon:'app-notepad',category:'Productivity',version:'1.0.0',desc:'A lightweight place to keep notes directly inside Lolite OS.',open:()=>openApp('notes','Quick Notes',560,500)},
  {id:'calculator',name:'Calculator',icon:'app-calculator',category:'Utilities',version:'1.0.0',desc:'Fast everyday calculations with a clean Lolite interface.',open:()=>openApp('calculator','Calculator',430,520)},
  {id:'paint',name:'Lolite Paint',icon:'app-paint',category:'Creative',version:'1.0.0',desc:'Simple drawing and sketching tools for the desktop.',open:()=>openApp('paint','Lolite Paint',720,560)},
  {id:'wallpaper-editor',name:'Wallpaper Editor',icon:'app-wallpaper',category:'Creative',version:'1.0.0',featured:true,desc:'Create custom Lolite wallpapers with gradients, glow, text and drawing tools.',open:()=>openApp('wallpaper-editor','Wallpaper Editor',900,650)}
 ];
 const key='loliteInstalledApps';const get=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};const save=x=>localStorage.setItem(key,JSON.stringify(x));
 window.loliteInstallApp=id=>{const a=apps.find(x=>x.id===id);if(!a)return;const list=get();if(!list.includes(id))list.push(id);save(list);render();if(window.renderIcons)window.renderIcons()};
 window.loliteUninstallApp=id=>{save(get().filter(x=>x!==id));render();if(window.renderIcons)window.renderIcons()};
 window.loliteOpenApp=id=>{const a=apps.find(x=>x.id===id);if(a)a.open()};
 function render(){const root=document.querySelector('.appstore');if(!root)return;const installed=get();root.innerHTML=`<div class="appstore-head"><div><div class="muted">LOLITE SOFTWARE</div><h1>App Store</h1><div class="muted">Install apps, manage your library and discover Lolite tools.</div></div><span class="appstore-note">${installed.length} installed</span></div><div class="appstore-toolbar"><input id="appStoreSearch" placeholder="Search apps…" aria-label="Search apps"><div class="appstore-tabs"><button class="store-tab active" data-filter="All">All</button><button class="store-tab" data-filter="Featured">Featured</button><button class="store-tab" data-filter="Installed">Installed</button><button class="store-tab" data-filter="Productivity">Productivity</button><button class="store-tab" data-filter="Creative">Creative</button><button class="store-tab" data-filter="Utilities">Utilities</button><button class="store-tab" data-filter="Internet">Internet</button></div></div><div id="appStoreGrid" class="appstore-grid"></div><div class="appstore-note">Apps are installed locally using Lolite OS preferences. Installing an app adds its shortcut to the desktop.</div>`;const input=document.getElementById('appStoreSearch');const grid=document.getElementById('appStoreGrid');let filter='All';const draw=()=>{const q=input.value.trim().toLowerCase();const list=apps.filter(a=>(filter==='All'||(filter==='Featured'&&a.featured)||(filter==='Installed'&&installed.includes(a.id))||(a.category===filter))&&(!q||a.name.toLowerCase().includes(q)||a.desc.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(a=>{const on=installed.includes(a.id);return \`<article class="appstore-card"><div class="appstore-icon"><b class="app-symbol \${a.icon}"></b></div><div class="appstore-card-meta"><span>\${a.category}</span><span>v\${a.version}</span></div><h3>\${a.name}</h3><p>\${a.desc}</p><button class="\${on?'installed':''}" onclick="\${on?\`window.loliteOpenApp('\\${a.id}')\`:\`window.loliteInstallApp('\\${a.id}')\`}">\${on?'Open':'Install'}</button>\${on?\`<button class="app-uninstall" onclick="window.loliteUninstallApp('\\${a.id}')">Uninstall</button>\`:''}</article>\`}).join(''):'<div class="store-empty">No apps match your search.</div>';grid.querySelectorAll('.store-tab')};input.oninput=draw;root.querySelectorAll('.store-tab').forEach(b=>b.onclick=()=>{root.querySelectorAll('.store-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;draw()});draw()}
 const oldPage=window.page;window.page=function(id){if(id==='appstore'){setTimeout(render,0);return '<div class="appstore"><div class="store-empty">Loading App Store…</div></div>'}return oldPage(id)};
 const oldIcons=window.renderIcons;window.renderIcons=function(){oldIcons();const installed=get();const icons=[['app-ai','Lolite AI','lowlight-ai'],['app-browser','Lolite Browser','browser'],['app-notepad','Quick Notes','notes'],['app-calculator','Calculator','calculator'],['app-paint','Lolite Paint','paint'],['app-wallpaper','Wallpaper Editor','wallpaper-editor']];const box=document.getElementById('icons');if(!box)return;icons.filter(x=>installed.includes(x[2])).forEach(x=>{const b=document.createElement('button');b.className='desktop-icon';b.ondblclick=()=>window.loliteOpenApp(x[2]);b.innerHTML=`<b class="app-symbol ${x[0]}"></b><span>${x[1]}</span>`;box.appendChild(b)});const app=document.createElement('button');app.className='desktop-icon';app.ondblclick=()=>openApp('appstore','App Store',780,590);app.innerHTML='<b class="app-symbol app-store"></b><span>App Store</span>';box.appendChild(app)};
})();
