/* Lolite OS App Store — installable apps with desktop shortcuts. */
(()=>{
 const css=`.appstore{height:100%;margin:-18px;background:#0e1117;color:#eef2f7;overflow:auto;padding:24px}.appstore-head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:22px}.appstore-head h1{margin:4px 0;font-size:30px}.appstore-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.appstore-card{background:#171c25;border:1px solid #29313d;border-radius:13px;padding:17px;transition:.15s}.appstore-card:hover{transform:translateY(-2px);border-color:#414d61}.appstore-icon{width:48px;height:48px;border-radius:12px;display:grid;place-items:center;background:#242b38;font-size:25px;margin-bottom:13px}.appstore-card h3{margin:0 0 5px}.appstore-card p{color:#919baa;font-size:13px;min-height:38px;line-height:1.45}.appstore-card button{width:100%;padding:9px;border-radius:8px;background:#7065db;color:#fff;font-weight:750}.appstore-card button.installed{background:#202833;border:1px solid #303a48}.appstore-note{margin-top:18px;color:#858f9e;font-size:12px}`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const apps=[
  {id:'lowlight-ai',name:'Low Light AI',icon:'✨',desc:'Your built-in AI assistant for questions, ideas and Lolite OS help.',open:()=>openApp('lowlight-ai','Low Light AI',720,600)},
  {id:'browser',name:'Lolite Browser',icon:'🌐',desc:'A clean browser workspace with tabs, navigation and direct web access.',open:()=>openApp('browser','Lolite Browser',900,650)},
  {id:'notes',name:'Quick Notes',icon:'📝',desc:'A lightweight place to keep notes directly inside Lolite OS.',open:()=>openApp('notes','Quick Notes',560,500)},
  {id:'calculator',name:'Calculator',icon:'🧮',desc:'Fast everyday calculations with a clean Lolite interface.',open:()=>openApp('calculator','Calculator',430,520)},
  {id:'paint',name:'Lolite Paint',icon:'🎨',desc:'Simple drawing and sketching tools for the desktop.',open:()=>openApp('paint','Lolite Paint',720,560)}
 ];
 const key='loliteInstalledApps';const get=()=>JSON.parse(localStorage.getItem(key)||'[]');const save=x=>localStorage.setItem(key,JSON.stringify(x));
 window.loliteInstallApp=id=>{const a=apps.find(x=>x.id===id);if(!a)return;const list=get();if(!list.includes(id))list.push(id);save(list);render();if(window.renderIcons)window.renderIcons()};
 window.loliteUninstallApp=id=>{save(get().filter(x=>x!==id));render();if(window.renderIcons)window.renderIcons()};
 window.loliteOpenApp=id=>{const a=apps.find(x=>x.id===id);if(a)a.open()};
 function render(){const root=document.querySelector('.appstore');if(!root)return;const installed=get();root.innerHTML=`<div class="appstore-head"><div><div class="muted">LOLITE SOFTWARE</div><h1>App Store</h1><div class="muted">Install apps first. Installed apps appear on your desktop.</div></div><span class="appstore-note">${installed.length} installed</span></div><div class="appstore-grid">${apps.map(a=>{const on=installed.includes(a.id);return `<article class="appstore-card"><div class="appstore-icon">${a.icon}</div><h3>${a.name}</h3><p>${a.desc}</p><button class="${on?'installed':''}" onclick="${on?`window.loliteOpenApp('${a.id}')`:`window.loliteInstallApp('${a.id}')`}">${on?'Open':'Install'}</button>${on?`<button style="margin-top:7px;background:transparent;color:#8d97a6" onclick="window.loliteUninstallApp('${a.id}')">Uninstall</button>`:''}</article>`}).join('')}</div><div class="appstore-note">Apps are installed locally using Lolite OS preferences. Nothing is added to the desktop until you install it.</div>`}
 const oldPage=window.page;window.page=function(id){if(id==='appstore'){setTimeout(render,0);return '<div class="appstore"><div class="store-empty">Loading App Store…</div></div>'}return oldPage(id)};
 const oldIcons=window.renderIcons;window.renderIcons=function(){oldIcons();const installed=get();const icons=[['✨','Low Light AI','lowlight-ai'],['🌐','Lolite Browser','browser'],['📝','Quick Notes','notes'],['🧮','Calculator','calculator'],['🎨','Lolite Paint','paint']];const box=document.getElementById('icons');if(!box)return;icons.filter(x=>installed.includes(x[2])).forEach(x=>{const b=document.createElement('button');b.className='desktop-icon';b.ondblclick=()=>window.loliteOpenApp(x[2]);b.innerHTML=`<b class="app-symbol">${x[0]}</b><span>${x[1]}</span>`;box.appendChild(b)});const app=document.createElement('button');app.className='desktop-icon';app.ondblclick=()=>openApp('appstore','App Store',780,590);app.innerHTML='<b class="app-symbol app-store"></b><span>App Store</span>';box.appendChild(app)};
})();
