/* Lolite OS Creative Tools — Wallpaper Editor, enhanced Paint, and liquid refraction UI. */
(()=>{
  const css=`
  .creative{height:100%;display:flex;flex-direction:column;gap:10px;background:#0d1016;color:#eef2f7}.creative-toolbar{display:flex;gap:6px;flex-wrap:wrap;padding:8px;background:#171c25;border:1px solid #29313d;border-radius:10px}.creative-toolbar button,.creative-toolbar select,.creative-toolbar input{border:1px solid #303947;background:#202733;color:#eef2f7;border-radius:7px;padding:7px 9px}.creative-toolbar button{cursor:pointer}.creative-toolbar button.active{border-color:#8b5cf6;background:#31235b}.creative-canvas-wrap{flex:1;min-height:0;background:#080b10;border:1px solid #29313d;border-radius:10px;display:grid;place-items:center;overflow:auto}.creative canvas{max-width:100%;max-height:100%;touch-action:none}.creative-status{font-size:11px;color:#8995a7}.tool-group{display:flex;gap:5px;align-items:center}.tool-group label{font-size:11px;color:#9aa5b5}
  .liquid-glass .window,.liquid-glass #taskbar,.liquid-glass .panel,.liquid-glass .card,.liquid-glass .taskwin{background:rgba(20,24,34,.62)!important;border-color:rgba(255,255,255,.16)!important;backdrop-filter:url(#lolite-liquid-filter) blur(2px) saturate(170%);-webkit-backdrop-filter:blur(2px) saturate(170%);box-shadow:inset 0 1px rgba(255,255,255,.24),inset 0 -1px rgba(0,0,0,.28),0 16px 45px rgba(0,0,0,.32)!important}.liquid-glass .window::before,.liquid-glass #taskbar::before{content:"";position:absolute;inset:0;border-radius:inherit;pointer-events:none;background:linear-gradient(125deg,rgba(255,255,255,.18),transparent 28%,transparent 68%,rgba(160,190,255,.08));mix-blend-mode:screen}.liquid-glass .window{overflow:hidden}.liquid-glass .titlebar{background:rgba(255,255,255,.055)!important}.liquid-glass .soft,.liquid-glass .primary,.liquid-glass button.task{background:rgba(255,255,255,.08)!important;border-color:rgba(255,255,255,.18)!important;box-shadow:inset 0 1px rgba(255,255,255,.2),0 5px 18px rgba(0,0,0,.18)}
  `;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','0');svg.setAttribute('height','0');svg.innerHTML=`<defs><filter id="lolite-liquid-filter" x="-12%" y="-12%" width="124%" height="124%"><feTurbulence type="fractalNoise" baseFrequency="0.018 0.025" numOctaves="2" seed="7" result="noise"/><feGaussianBlur in="noise" stdDeviation="2" result="soft"/><feDisplacementMap in="SourceGraphic" in2="soft" scale="18" xChannelSelector="R" yChannelSelector="G"/></filter></defs>`;document.body.append(svg);
  function fitCanvas(c,w,h){c.width=w;c.height=h;c.style.width='100%';c.style.height='auto'}
  function downloadCanvas(c,name){const a=document.createElement('a');a.download=name;a.href=c.toDataURL('image/png');a.click()}
  const old=window.page;
  window.page=function(id){
    if(id==='paint')return `<div class="creative"><div class="creative-toolbar"><div class="tool-group"><button onclick="window.paintTool('pen')">✏️ Pen</button><button onclick="window.paintTool('marker')">🖍️ Marker</button><button onclick="window.paintTool('highlighter')">🖌️ Highlighter</button><button onclick="window.paintTool('eraser')">🧽 Eraser</button><button onclick="window.paintTool('line')">╱ Line</button><button onclick="window.paintTool('rect')">▭ Box</button><button onclick="window.paintTool('circle')">◯ Circle</button></div><div class="tool-group"><label>Size</label><input id="paintSize" type="range" min="1" max="60" value="6"></div><div class="tool-group"><label>Colour</label><input id="paintColor" type="color" value="#8b5cf6"></div><button onclick="window.paintClear()">Clear</button><button onclick="window.paintSavePNG()">Save PNG</button><button onclick="window.paintSavePDF()">Save as PDF</button><button onclick="window.paintSaveWallpaper()">Save as Wallpaper</button></div><div class="creative-canvas-wrap"><canvas id="paintCanvas" width="760" height="500"></canvas></div><div class="creative-status">Draw, highlight, erase, add shapes, then save your creation as a PNG, PDF or Lolite wallpaper.</div></div>`;
    if(id==='wallpaper-editor')return `<div class="creative"><div class="creative-toolbar"><button class="active" onclick="window.wpTool('draw')">✏️ Draw</button><button onclick="window.wpTool('glow')">✨ Glow</button><button onclick="window.wpTool('text')">🔤 Text</button><button onclick="window.wpTool('rect')">▭ Shape</button><button onclick="window.wpTool('circle')">◯ Circle</button><button onclick="window.wpGradient()">🌈 Gradient</button><button onclick="window.wpBackground()">🎨 Background</button><input id="wpColor" type="color" value="#8b5cf6"><input id="wpSize" type="range" min="2" max="80" value="12"><select id="wpFont"><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Courier New</option><option>Impact</option><option>Trebuchet MS</option></select><button onclick="window.wpUndo()">↶ Undo</button><button onclick="window.wpClear()">Clear</button><button onclick="window.wpSave()">Save Wallpaper</button></div><div class="creative-canvas-wrap"><canvas id="wpCanvas" width="1000" height="600"></canvas></div><div class="creative-status">Create a wallpaper with gradients, glow, drawing, text, shapes and custom colours. Text mode asks what you want to write.</div></div>`;
    return old(id);
  };
  let ptool='pen',px=0,py=0,pdown=false;
  window.paintTool=t=>ptool=t;
  window.paintClear=()=>{const c=document.getElementById('paintCanvas');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height)};
  window.paintSavePNG=()=>{const c=document.getElementById('paintCanvas');if(c)downloadCanvas(c,'lolite-paint.png')};
  window.paintSaveWallpaper=()=>{const c=document.getElementById('paintCanvas');if(c){localStorage.loliteCustomWallpaper=c.toDataURL('image/png');if(window.loliteWallpaperData)window.loliteWallpaperData(c.toDataURL('image/png'));downloadCanvas(c,'lolite-wallpaper.png');toast('Saved as a Lolite wallpaper')}};
  window.paintSavePDF=()=>{const c=document.getElementById('paintCanvas');if(!c)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><body style="margin:0;background:white"><img src="${c.toDataURL('image/png')}" style="width:100%"><script>setTimeout(()=>print(),250)<\/script></body></html>`);w.document.close()};
  function initPaint(){const c=document.getElementById('paintCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{pdown=true;const p=pos(e);px=p.x;py=p.y};c.onpointerup=()=>{pdown=false;ctx.globalAlpha=1};c.onpointermove=e=>{if(!pdown)return;const p=pos(e),size=+document.getElementById('paintSize').value,col=document.getElementById('paintColor').value;ctx.strokeStyle=ptool==='eraser'?'#fff':col;ctx.lineWidth=size;ctx.lineCap='round';ctx.globalAlpha=ptool==='highlighter'?.25:ptool==='marker'?.55:1;if(ptool==='line'){ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(p.x,p.y);ctx.stroke()}else if(ptool==='rect'){ctx.strokeRect(px,py,p.x-px,p.y-py)}else if(ptool==='circle'){const r=Math.hypot(p.x-px,p.y-py);ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(p.x,p.y);ctx.stroke()}px=p.x;py=p.y};}
  let wtool='draw',wx=0,wy=0,wdown=false,whistory=[];
  window.wpTool=t=>{wtool=t;if(t==='text'){const text=prompt('Wallpaper text:');if(text){const c=document.getElementById('wpCanvas'),ctx=c.getContext('2d');ctx.fillStyle=document.getElementById('wpColor').value;ctx.font=`bold ${Math.max(18,+document.getElementById('wpSize').value*3)}px ${document.getElementById('wpFont').value}`;ctx.fillText(text,wx||100,wy||100)}}};
  window.wpGradient=()=>{const c=document.getElementById('wpCanvas');if(!c)return;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,document.getElementById('wpColor').value);g.addColorStop(.5,'#111827');g.addColorStop(1,'#050816');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height)};
  window.wpBackground=()=>{const c=document.getElementById('wpCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle=document.getElementById('wpColor').value;ctx.fillRect(0,0,c.width,c.height)};
  window.wpUndo=()=>{const c=document.getElementById('wpCanvas'),ctx=c?.getContext('2d'),img=whistory.pop();if(c&&ctx&&img)ctx.putImageData(img,0,0)};window.wpClear=()=>{const c=document.getElementById('wpCanvas');if(c)c.getContext('2d').clearRect(0,0,c.width,c.height)};window.wpSave=()=>{const c=document.getElementById('wpCanvas');if(!c)return;const data=c.toDataURL('image/png');localStorage.loliteCustomWallpaper=data;const wall=document.getElementById('wallpaper');if(wall)wall.style.backgroundImage=`url(${data})`;downloadCanvas(c,'lolite-custom-wallpaper.png');toast('Wallpaper saved and applied')};
  function initWP(){const c=document.getElementById('wpCanvas');if(!c)return;const ctx=c.getContext('2d');ctx.fillStyle='#0b0716';ctx.fillRect(0,0,c.width,c.height);const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{wdown=true;const p=pos(e);wx=p.x;wy=p.y;whistory.push(ctx.getImageData(0,0,c.width,c.height))};c.onpointerup=()=>wdown=false;c.onpointermove=e=>{if(!wdown||wtool==='text')return;const p=pos(e),col=document.getElementById('wpColor').value,size=+document.getElementById('wpSize').value;ctx.lineCap='round';ctx.lineWidth=size;ctx.strokeStyle=col;if(wtool==='glow'){ctx.shadowColor=col;ctx.shadowBlur=size*2;ctx.globalAlpha=.65}else{ctx.shadowBlur=0;ctx.globalAlpha=1}if(wtool==='rect'){ctx.strokeRect(wx,wy,p.x-wx,p.y-wy)}else if(wtool==='circle'){const r=Math.hypot(p.x-wx,p.y-wy);ctx.beginPath();ctx.arc(wx,wy,r,0,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(wx,wy);ctx.lineTo(p.x,p.y);ctx.stroke()}wx=p.x;wy=p.y;ctx.shadowBlur=0};}
  const observer=new MutationObserver(()=>{if(document.getElementById('paintCanvas'))initPaint();if(document.getElementById('wpCanvas'))initWP()});observer.observe(document.getElementById('windows'),{childList:true,subtree:true});
  window.loliteWallpaperData=data=>{localStorage.loliteCustomWallpaper=data;const wall=document.getElementById('wallpaper');if(wall)wall.style.backgroundImage=`url(${data})`};
})();
