/* Lolite Device Experience — startup mode picker plus phone/tablet shell. */
(()=> {
 const css = `
 #loliteModeChooser{position:fixed;inset:0;z-index:100000;background:radial-gradient(ellipse at 50% 0%,#25234b 0%,#111421 48%,#090b11 100%);display:flex;align-items:center;justify-content:center;padding:24px;color:#f5f6ff;font-family:"Segoe UI",system-ui,sans-serif}
 .lm-wrap{width:min(980px,100%);margin:auto}.lm-brand{display:flex;align-items:center;justify-content:center;gap:14px;margin-bottom:24px}.lm-logo{width:54px;height:54px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(145deg,#8c7bff,#5143bd);font-size:30px;font-weight:900;box-shadow:0 10px 35px #5143bd55}.lm-brand h1{font-size:28px;margin:0}.lm-eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;color:#a7add0;margin-bottom:6px}.lm-title{text-align:center;font-size:clamp(26px,4vw,42px);letter-spacing:-.04em;margin:0 0 9px}.lm-sub{text-align:center;color:#aab2c7;margin:0 auto 28px;max-width:620px;line-height:1.55}.lm-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.lm-choice{position:relative;text-align:left;padding:20px;border-radius:18px;border:1px solid #353c55;background:linear-gradient(145deg,#1c2132ee,#121722ee);color:#f5f6ff;min-height:235px;transition:transform .18s,border-color .18s,background .18s;overflow:hidden}.lm-choice:hover,.lm-choice:focus-visible{transform:translateY(-3px);border-color:#8b7cff;outline:none;background:linear-gradient(145deg,#282849,#151b29)}.lm-choice h2{margin:15px 0 7px;font-size:22px}.lm-choice p{color:#aab3c8;line-height:1.5;margin:0;max-width:390px}.lm-tag{display:inline-flex;align-items:center;gap:6px;color:#c9c3ff;background:#6557cf2c;border:1px solid #7366dc55;border-radius:999px;padding:5px 9px;font-size:11px}.lm-art{height:90px;display:flex;align-items:center;justify-content:center;gap:10px}.lm-monitor{width:118px;height:72px;border:2px solid #6b76a1;border-radius:9px;padding:6px;box-shadow:0 10px 25px #0005}.lm-screen{height:100%;border-radius:4px;background:linear-gradient(135deg,#8a78ff,#4c8dff 55%,#1a2140);position:relative}.lm-screen:after{content:"";position:absolute;left:12%;right:12%;bottom:14%;height:6px;border-radius:8px;background:#ffffff88}.lm-stand{width:28px;height:7px;background:#6b76a1;margin:0 auto;border-radius:0 0 5px 5px}.lm-phone{width:43px;height:78px;border:2px solid #7580aa;border-radius:12px;padding:4px;box-shadow:0 10px 25px #0005}.lm-phone .lm-screen{border-radius:8px}.lm-tablet{width:94px;height:68px;border:2px solid #7580aa;border-radius:10px;padding:5px}.lm-device-options{display:none;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:14px}.lm-device-options.visible{display:grid}.lm-device{display:flex;align-items:center;gap:13px;padding:15px;border:1px solid #343b55;border-radius:14px;background:#171c2a;color:#f4f5ff;text-align:left}.lm-device:hover{border-color:#8b7cff;background:#22233d}.lm-device strong,.lm-device small{display:block}.lm-device small{color:#aab2c7;margin-top:4px;line-height:1.4}.lm-footer{text-align:center;color:#7e89a4;font-size:12px;margin-top:22px}.lm-back{display:none;background:transparent;color:#c5c9dd;margin:0 0 12px;padding:8px 0}.lm-back.visible{display:block}
 #loliteMobileShell{position:absolute;inset:0;z-index:35;color:#f6f6ff;display:flex;flex-direction:column;background:linear-gradient(160deg,#211b45dd,#0c1225eF 48%,#11162aee);font-family:"Segoe UI",system-ui,sans-serif;overflow:hidden}
 .lm-statusbar{height:34px;flex:0 0 34px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;font-size:12px;font-weight:700;color:#f2f3ff;background:#0d1022aa;backdrop-filter:blur(20px)}.lm-status-right{display:flex;align-items:center;gap:8px}.lm-status-right button{background:transparent;color:inherit;padding:3px}
 .lm-mobile-head{padding:18px 20px 8px}.lm-mobile-head h1{font-size:28px;margin:0;letter-spacing:-.04em}.lm-mobile-head p{font-size:13px;color:#bbc2d9;margin:5px 0 0}.lm-mobile-search{margin:12px 20px 16px;display:flex;gap:9px;align-items:center;border:1px solid #ffffff22;background:#ffffff12;border-radius:14px;padding:11px 13px;color:#d5daf0}.lm-mobile-search input{width:100%;background:transparent;color:white;border:0;outline:0;font:inherit}.lm-mobile-search input::placeholder{color:#a5aec8}
 .lm-app-scroll{flex:1;overflow:auto;padding:0 18px 20px;scrollbar-width:thin;scrollbar-color:#54577a transparent}.lm-section-label{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:#a6afcf;margin:10px 2px 12px}.lm-app-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px 8px}.lm-app-icon{display:flex;flex-direction:column;align-items:center;gap:7px;background:transparent;color:#f7f7ff;min-width:0;padding:0 2px;text-align:center}.lm-app-icon:active .lm-icon-tile{transform:scale(.92)}.lm-icon-tile{width:clamp(48px,6vw,62px);height:clamp(48px,6vw,62px);display:grid;place-items:center;border-radius:18px;font-size:25px;font-weight:700;background:linear-gradient(145deg,#38345f,#1c2949);border:1px solid #ffffff26;box-shadow:0 8px 20px #0003;transition:transform .12s}.lm-app-icon span:last-child{font-size:11px;line-height:1.25;max-width:100%;overflow-wrap:anywhere;text-shadow:0 1px 5px #0007}.lm-dock-wrap{padding:8px 16px 9px}.lm-dock{display:flex;justify-content:center;gap:12px;padding:10px 12px;border:1px solid #ffffff24;background:#111529bb;border-radius:22px;backdrop-filter:blur(22px)}.lm-dock .lm-icon-tile{width:48px;height:48px;border-radius:15px}.lm-bottom-nav{height:25px;flex:0 0 25px;display:flex;align-items:center;justify-content:center;gap:42px;background:#0c1020aa}.lm-nav-btn{background:transparent;color:#cdd3ec;font-size:18px;padding:0 8px}.lm-home-indicator{width:78px;height:4px;border-radius:5px;background:#f4f4ff;opacity:.85}
 .lm-quick{position:absolute;z-index:90;top:38px;right:12px;width:min(340px,calc(100% - 24px));padding:15px;border:1px solid #ffffff24;border-radius:18px;background:#151a2af5;box-shadow:0 20px 55px #0008;backdrop-filter:blur(24px)}.lm-quick h3{margin:0 0 12px}.lm-quick-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.lm-quick-grid button{padding:12px;border-radius:12px;background:#272d45;color:#f4f5ff;text-align:left;border:1px solid #ffffff12}.lm-quick-grid button.active{background:#5d53c7}.lm-quick p{font-size:12px;color:#aeb8d1;line-height:1.5;margin:12px 0 0}
 .mobile-mode #wallpaper:after{opacity:.28}.mobile-mode #icons,.mobile-mode #taskbar{display:none!important}.mobile-mode #windows{position:absolute;inset:0;z-index:55;pointer-events:none}.mobile-mode .window{pointer-events:auto;position:fixed!important;left:0!important;top:34px!important;right:0!important;bottom:25px!important;width:auto!important;height:auto!important;min-width:0!important;min-height:0!important;resize:none!important;border-radius:0!important;z-index:70!important;animation:none}.mobile-mode .window .titlebar{height:45px;cursor:default;padding-left:14px}.mobile-mode .window .content{height:calc(100% - 45px);padding:14px}.mobile-mode .window .controls .min,.mobile-mode .window .controls .max{display:none}.mobile-mode .window .controls .close{display:block}.mobile-mode .window .controls .close:after{content:"×"}.mobile-mode #toast{z-index:99999}
 .tablet-mode #loliteMobileShell .lm-mobile-head{padding-top:25px}.tablet-mode #loliteMobileShell .lm-app-grid{grid-template-columns:repeat(6,minmax(0,1fr));gap:22px 12px}.tablet-mode #loliteMobileShell .lm-icon-tile{width:68px;height:68px;border-radius:20px}.tablet-mode #loliteMobileShell .lm-app-scroll{padding-left:34px;padding-right:34px}.tablet-mode #loliteMobileShell .lm-mobile-head{padding-left:36px}.tablet-mode #loliteMobileShell .lm-mobile-search{margin-left:36px;margin-right:36px}.tablet-mode #loliteMobileShell .lm-dock .lm-icon-tile{width:54px;height:54px}
 @media(max-width:520px){#loliteModeChooser{padding:16px;align-items:flex-start;overflow:auto}.lm-brand{margin:12px 0 20px}.lm-options{grid-template-columns:1fr;gap:10px}.lm-choice{min-height:0;padding:14px;display:grid;grid-template-columns:90px 1fr;align-items:center;column-gap:13px}.lm-art{height:82px;grid-row:span 2}.lm-choice h2{font-size:18px;margin:0 0 5px}.lm-choice p{font-size:12px}.lm-tag{font-size:10px}.lm-device-options{grid-template-columns:1fr}.lm-title{font-size:27px}.lm-sub{font-size:13px;margin-bottom:18px}.lm-app-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:17px 4px}.lm-mobile-head h1{font-size:25px}.lm-statusbar{padding:0 14px}.lm-dock{gap:9px}.lm-dock .lm-icon-tile{width:43px;height:43px}.mobile-mode .window .content{padding:10px}}
 @media(min-width:521px) and (max-width:850px){.lm-app-grid{grid-template-columns:repeat(5,minmax(0,1fr))}}
 @media(prefers-reduced-motion:reduce){.lm-choice,.lm-icon-tile{transition:none}}
 `;
 const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
 const APPS=[
  {id:'home',name:'Home',icon:'⌂',color:'linear-gradient(145deg,#5d62d5,#4035a2)'},
  {id:'games',name:'Game Store',icon:'🎮',color:'linear-gradient(145deg,#8064e8,#4b2eaa)'},
  {id:'files',name:'Files',icon:'📁',color:'linear-gradient(145deg,#e2b74f,#8d6321)'},
  {id:'settings',name:'Settings',icon:'⚙',color:'linear-gradient(145deg,#7e8da5,#394457)'},
  {id:'appstore',name:'App Store',icon:'▦',color:'linear-gradient(145deg,#4d8dff,#3e47ad)'},
  {id:'lowlight-ai',name:'Lolite AI',icon:'✦',color:'linear-gradient(145deg,#bc8cff,#6251c7)'},
  {id:'chatroom',name:'Lolite Chat',icon:'◉',color:'linear-gradient(145deg,#59b6a5,#267f7a)'},
  {id:'calculator',name:'Calculator',icon:'＋',color:'linear-gradient(145deg,#657589,#303d53)'},
  {id:'notes',name:'Quick Notes',icon:'▤',color:'linear-gradient(145deg,#4b9bd7,#275d94)'},
  {id:'paint',name:'Lolite Paint',icon:'🎨',color:'linear-gradient(145deg,#e87b9b,#98416c)'},
  {id:'wallpaper-editor',name:'Wallpaper Editor',icon:'▧',color:'linear-gradient(145deg,#e16b9f,#6544c9)'},
  {id:'world',name:'World Sandbox',icon:'🌎',color:'linear-gradient(145deg,#56a88a,#246b61)'}
 ];
 let chosenMode='desktop',chosenDevice='phone',shell=null,quick=null,activeApp=null,originalOpen=null,originalClose=null,originalRestore=null;
 const getApp=id=>APPS.find(a=>a.id===id)||{id,name:id.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase()),icon:'◈',color:'linear-gradient(145deg,#565f85,#28314c)'};
 function chooser(){if(document.getElementById('loliteModeChooser'))return;const el=document.createElement('div');el.id='loliteModeChooser';el.innerHTML=`<div class="lm-wrap"><div class="lm-brand"><div class="lm-logo">L</div><div><div class="lm-eyebrow">A desktop and mobile experience</div><h1>Lolite OS</h1></div></div><h2 class="lm-title">How would you like to start?</h2><p class="lm-sub">Choose the Lolite experience for this session. Mobile mode has its own app launcher, dock, quick settings and full-screen apps.</p><div class="lm-options"><button class="lm-choice" id="lmDesktop" type="button"><div class="lm-art"><div><div class="lm-monitor"><div class="lm-screen"></div></div><div class="lm-stand"></div></div></div><div class="lm-tag">WINDOWS-STYLE DESKTOP</div><h2>Normal Lolite</h2><p>Resizable windows, desktop shortcuts, taskbar and the familiar Lolite workspace.</p></button><button class="lm-choice" id="lmMobile" type="button"><div class="lm-art"><div class="lm-tablet"><div class="lm-screen"></div></div><div class="lm-phone"><div class="lm-screen"></div></div></div><div class="lm-tag">TOUCH-FIRST EXPERIENCE</div><h2>Mobile Lolite</h2><p>A phone or tablet-style home screen, app grid, dock, navigation and quick settings.</p></button></div><button class="lm-back" id="lmBack" type="button">← Back to experiences</button><div class="lm-device-options" id="lmDeviceOptions"><button class="lm-device" id="lmPhone" type="button"><span class="lm-phone"><span class="lm-screen" style="display:block;height:100%"></span></span><span><strong>Phone</strong><small>Compact layout, four-column app grid and bottom dock.</small></span></button><button class="lm-device" id="lmTablet" type="button"><span class="lm-tablet"><span class="lm-screen" style="display:block;height:100%"></span></span><span><strong>Tablet</strong><small>Roomier layout, wider app grid and larger touch targets.</small></span></button></div><div class="lm-footer">Your choice applies now. Choose again next time you launch Lolite OS.</div></div>`;document.body.appendChild(el);
  el.querySelector('#lmDesktop').onclick=()=>startDesktop();el.querySelector('#lmMobile').onclick=()=>{el.querySelector('.lm-options').style.display='none';el.querySelector('#lmDeviceOptions').classList.add('visible');el.querySelector('#lmBack').classList.add('visible')};el.querySelector('#lmBack').onclick=()=>{el.querySelector('.lm-options').style.display='grid';el.querySelector('#lmDeviceOptions').classList.remove('visible');el.querySelector('#lmBack').classList.remove('visible')};el.querySelector('#lmPhone').onclick=()=>startMobile('phone');el.querySelector('#lmTablet').onclick=()=>startMobile('tablet');
 }
 function baseStart(){document.getElementById('loliteModeChooser')?.remove();document.getElementById('boot')?.remove();const d=document.getElementById('desktop');d?.classList.remove('hidden');window.loadPrefs?.();window.renderIcons?.();}
 function startDesktop(){chosenMode='desktop';document.documentElement.classList.remove('mobile-mode','tablet-mode','phone-mode');baseStart();window.openApp?.('home','Home',650,450);}
 function startMobile(device){chosenMode='mobile';chosenDevice=device;document.documentElement.classList.add('mobile-mode',device==='tablet'?'tablet-mode':'phone-mode');baseStart();document.getElementById('icons')?.classList.add('hidden');document.getElementById('taskbar')?.classList.add('hidden');buildShell();window.dispatchEvent(new CustomEvent('lolite:modechange',{detail:{mode:'mobile',device}}));}
 function open(id){const a=getApp(id);hideQuick();if(id==='home'){showLauncher();return}if(!window.page){toast('App system is still loading.');return}activeApp=id;document.getElementById('loliteMobileShell')?.classList.add('app-open');shell?.querySelectorAll('.lm-app-icon').forEach(b=>b.classList.remove('selected'));window.openApp?.(id,a.name,850,650);const win=document.querySelector('.window[data-window-id="'+CSS.escape(id)+'"]');if(win){win.classList.add('mobile-app-window');win.style.zIndex='1000';win.querySelector('.titlebar strong').textContent=a.name;win.querySelector('.controls .close').title='Back to Home';}}
 function showLauncher(){activeApp=null;document.querySelectorAll('.mobile-app-window').forEach(w=>{const id=w.dataset.windowId;window.closeWin?.(id)});document.querySelectorAll('#windows .window').forEach(w=>{const id=w.dataset.windowId;window.closeWin?.(id)});shell?.classList.remove('app-open');if(quick)hideQuick();const input=shell?.querySelector('#lmMobileSearchInput');if(input)input.value='';drawApps('');}
 function showQuick(){if(quick){hideQuick();return}quick=document.createElement('div');quick.className='lm-quick';quick.innerHTML='<h3>Quick settings</h3><div class="lm-quick-grid"><button class="active" data-q="wifi">◉ Wi-Fi · On</button><button class="active" data-q="sound">♫ Sound · On</button><button data-q="dark">☾ Dark mode · On</button><button data-q="motion">◌ Reduce motion · Off</button><button data-q="wallpaper">▧ Wallpaper</button><button data-q="settings">⚙ All settings</button></div><p>Wi-Fi and sound indicators are interface controls only; they do not change your device hardware.</p>';document.getElementById('loliteMobileShell')?.appendChild(quick);quick.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const k=b.dataset.q;if(k==='settings'){hideQuick();open('settings');return}if(k==='wallpaper'){hideQuick();open('wallpaper-editor');return}b.classList.toggle('active');if(k==='motion'){const on=b.classList.contains('active');localStorage.reduce=on?'true':'false';document.documentElement.classList.toggle('reduce',on)}if(k==='dark'){document.documentElement.classList.toggle('mobile-light',!b.classList.contains('active'))}});}
 function hideQuick(){quick?.remove();quick=null}
 function drawApps(query){const grid=shell?.querySelector('#lmAppGrid');if(!grid)return;const q=(query||'').toLowerCase().trim();const list=APPS.filter(a=>!q||a.name.toLowerCase().includes(q));grid.innerHTML=list.map(a=>'<button class="lm-app-icon" type="button" data-app="'+a.id+'"><span class="lm-icon-tile" style="background:'+a.color+'">'+a.icon+'</span><span>'+a.name+'</span></button>').join('');grid.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>open(b.dataset.app));}
 function buildShell(){shell=document.createElement('div');shell.id='loliteMobileShell';shell.innerHTML='<div class="lm-statusbar"><span id="lmStatusTime">9:41</span><span class="lm-status-right"><span>◉</span><span>▰</span><button id="lmQuickBtn" aria-label="Quick settings">☰</button></span></div><div class="lm-mobile-head"><h1>Good day.</h1><p>Your Lolite, anywhere.</p></div><label class="lm-mobile-search">⌕ <input id="lmMobileSearchInput" placeholder="Search apps…" autocomplete="off"></label><div class="lm-app-scroll"><div class="lm-section-label">Your apps</div><div class="lm-app-grid" id="lmAppGrid"></div><div class="lm-section-label">Suggestions</div><div class="lm-app-grid" id="lmSuggestedGrid"></div></div><div class="lm-dock-wrap"><div class="lm-dock" id="lmDock"></div></div><div class="lm-bottom-nav"><button class="lm-nav-btn" id="lmBackBtn" aria-label="Back">‹</button><div class="lm-home-indicator"></div><button class="lm-nav-btn" id="lmHomeBtn" aria-label="Home">○</button></div>';document.getElementById('desktop').appendChild(shell);shell.querySelector('#lmQuickBtn').onclick=showQuick;shell.querySelector('#lmHomeBtn').onclick=showLauncher;shell.querySelector('#lmBackBtn').onclick=()=>{if(quick)hideQuick();else showLauncher()};shell.querySelector('#lmMobileSearchInput').oninput=e=>drawApps(e.target.value);shell.querySelector('#lmMobileSearchInput').onkeydown=e=>{if(e.key==='Enter'){const first=shell.querySelector('#lmAppGrid [data-app]');first?.click()}};const dockIds=['home','games','files','appstore','settings'];shell.querySelector('#lmDock').innerHTML=dockIds.map(id=>{const a=getApp(id);return '<button class="lm-app-icon" data-app="'+id+'" aria-label="'+a.name+'"><span class="lm-icon-tile" style="background:'+a.color+'">'+a.icon+'</span></button>'}).join('');shell.querySelector('#lmDock').querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>open(b.dataset.app));const suggestions=shell.querySelector('#lmSuggestedGrid');suggestions.innerHTML=['lowlight-ai','chatroom','world'].map(id=>{const a=getApp(id);return '<button class="lm-app-icon" data-app="'+id+'"><span class="lm-icon-tile" style="background:'+a.color+'">'+a.icon+'</span><span>'+a.name+'</span></button>'}).join('');suggestions.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>open(b.dataset.app));drawApps('');const clock=()=>{const el=shell?.querySelector('#lmStatusTime');if(el)el.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})};clock();setInterval(clock,15000);}
 function init(){originalOpen=window.openApp;originalClose=window.closeWin;originalRestore=window.restoreWin;window.LoliteDeviceMode={showChooser:chooser,mode:()=>({mode:chosenMode,device:chosenDevice}),startMobile,startDesktop};chooser();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();