/* Lolite OS device experience picker and touch-first mobile shell. */
(()=> {
 const css=`
 #loliteModeChooser{position:fixed;inset:0;z-index:100000;background:radial-gradient(ellipse at top,#29234d,#090b12 70%);display:grid;place-items:center;padding:20px;color:#f5f6ff;font-family:system-ui,sans-serif}
 .lm-wrap{width:min(900px,100%)}.lm-brand{text-align:center;font-size:28px;font-weight:800;margin-bottom:12px}.lm-title{text-align:center;font-size:clamp(25px,4vw,40px);margin:8px 0}.lm-sub{text-align:center;color:#aeb6cf;line-height:1.5;margin:0 auto 24px;max-width:620px}.lm-options,.lm-device-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.lm-choice,.lm-device{color:#f5f6ff;background:#191e30;border:1px solid #39415f;border-radius:18px;padding:22px;text-align:left;cursor:pointer}.lm-choice:hover,.lm-device:hover{border-color:#9789ff;background:#222442}.lm-choice h2{margin:10px 0}.lm-choice p,.lm-device small{color:#adb6ce;line-height:1.5}.lm-art{font-size:46px}.lm-device-options{display:none}.lm-device-options.visible{display:grid}.lm-back{display:none;background:none;color:#d4d8eb;margin:0 0 12px;cursor:pointer}.lm-back.visible{display:block}
 #loliteMobileShell{position:absolute;inset:0;z-index:99999;display:flex;flex-direction:column;color:#fff;background:radial-gradient(ellipse at top left,#29214f,#0b1020 65%);font-family:system-ui,sans-serif;overflow:hidden}.lm-statusbar{height:38px;flex:0 0 38px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;background:#080b19aa;font-size:13px}.lm-statusbar button{background:none;color:white;cursor:pointer}.lm-mobile-head{padding:18px 20px 10px}.lm-mobile-head h1{margin:0;font-size:28px}.lm-mobile-head p{color:#b8c0d8;margin:4px 0}.lm-mobile-search{display:flex;gap:8px;margin:8px 18px 16px;padding:12px;border:1px solid #ffffff25;border-radius:14px;background:#ffffff12}.lm-mobile-search input{width:100%;border:0;outline:0;background:transparent;color:white;font:inherit}.lm-app-scroll{flex:1;overflow:auto;padding:0 18px 20px}.lm-section-label{font-size:11px;text-transform:uppercase;letter-spacing:.14em;color:#aab4d0;margin:12px 2px}.lm-app-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px 8px}.lm-app-icon{display:flex;flex-direction:column;align-items:center;gap:7px;background:none;color:white;cursor:pointer;min-width:0;padding:0 2px}.lm-icon-tile{width:54px;height:54px;border-radius:17px;display:grid;place-items:center;font-size:25px;background:linear-gradient(145deg,#6258bc,#253d63);border:1px solid #ffffff30}.lm-app-icon span:last-child{font-size:11px;text-align:center;overflow-wrap:anywhere}.lm-dock-wrap{padding:8px 14px}.lm-dock{display:flex;justify-content:center;gap:12px;padding:10px;border:1px solid #ffffff25;background:#111529d9;border-radius:22px}.lm-dock .lm-icon-tile{width:46px;height:46px}.lm-bottom-nav{height:26px;flex:0 0 26px;display:flex;align-items:center;justify-content:center;gap:45px;background:#080b19aa}.lm-nav-btn{background:none;color:#fff;font-size:20px;cursor:pointer}.lm-home-indicator{width:75px;height:4px;border-radius:9px;background:#fff}.lm-quick{position:absolute;z-index:100000;top:42px;right:12px;background:#171c2cf5;border:1px solid #ffffff30;border-radius:16px;padding:14px;width:min(320px,calc(100% - 24px));box-shadow:0 18px 50px #0008}.lm-quick button{padding:12px;margin:4px;border-radius:10px;background:#303651;color:white;cursor:pointer}
 .mobile-mode #wallpaper:after{opacity:.18}.mobile-mode #icons,.mobile-mode #taskbar{display:none!important}.mobile-mode #windows{position:absolute;inset:0;z-index:100001;pointer-events:none}.mobile-mode .window{pointer-events:auto;position:fixed!important;left:0!important;top:38px!important;right:0!important;bottom:26px!important;width:auto!important;height:auto!important;min-width:0!important;min-height:0!important;resize:none!important;border-radius:0!important;z-index:100002!important;animation:none}.mobile-mode .window .titlebar{height:45px;cursor:default}.mobile-mode .window .content{height:calc(100% - 45px);overflow:auto}.mobile-mode .window .controls .min,.mobile-mode .window .controls .max{display:none}
 .tablet-mode #loliteMobileShell .lm-app-grid{grid-template-columns:repeat(6,minmax(0,1fr));gap:24px 12px}.tablet-mode #loliteMobileShell .lm-icon-tile{width:68px;height:68px}.tablet-mode #loliteMobileShell .lm-app-scroll{padding-left:35px;padding-right:35px}
 @media(max-width:520px){#loliteModeChooser{align-items:start;overflow:auto}.lm-options{grid-template-columns:1fr}.lm-choice{padding:15px}.lm-device-options{grid-template-columns:1fr}.lm-title{font-size:27px}.lm-sub{font-size:13px}.lm-app-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}
 `;
 const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
 const APPS=[['home','Home','⌂'],['games','Game Store','🎮'],['files','Files','📁'],['settings','Settings','⚙'],['appstore','App Store','▦'],['lowlight-ai','Lolite AI','✦'],['chatroom','Lolite Chat','◉'],['calculator','Calculator','＋'],['notes','Quick Notes','▤'],['paint','Lolite Paint','🎨'],['wallpaper-editor','Wallpaper Editor','▧'],['world','World Sandbox','🌎']];
 let shell=null,quick=null,mode='desktop',device='phone';
 const appName=id=>APPS.find(a=>a[0]===id)?.[1]||id;
 function chooser(){if(document.getElementById('loliteModeChooser'))return;const el=document.createElement('div');el.id='loliteModeChooser';el.innerHTML='<div class="lm-wrap"><div class="lm-brand">◈ Lolite OS</div><h2 class="lm-title">How would you like to start?</h2><p class="lm-sub">Choose the experience that fits your device. You can return here by refreshing the page.</p><div class="lm-options"><button class="lm-choice" id="lmDesktop"><div class="lm-art">🖥️</div><h2>Normal Lolite</h2><p>Use the classic desktop with windows, shortcuts and taskbar.</p></button><button class="lm-choice" id="lmMobile"><div class="lm-art">📱　▰</div><h2>Mobile Lolite</h2><p>Use a touch-first home screen with a mobile app launcher.</p></button></div><button class="lm-back" id="lmBack">← Back to experiences</button><div class="lm-device-options" id="lmDevices"><button class="lm-device" id="lmPhone">📱 <strong>Phone</strong><br><small>Compact four-column launcher.</small></button><button class="lm-device" id="lmTablet">▰ <strong>Tablet</strong><br><small>Roomier six-column launcher.</small></button></div></div>';document.body.appendChild(el);
 el.querySelector('#lmDesktop').onclick=startDesktop;el.querySelector('#lmMobile').onclick=()=>{el.querySelector('.lm-options').style.display='none';el.querySelector('#lmDevices').classList.add('visible');el.querySelector('#lmBack').classList.add('visible')};el.querySelector('#lmBack').onclick=()=>{el.querySelector('.lm-options').style.display='grid';el.querySelector('#lmDevices').classList.remove('visible');el.querySelector('#lmBack').classList.remove('visible')};el.querySelector('#lmPhone').onclick=()=>startMobile('phone');el.querySelector('#lmTablet').onclick=()=>startMobile('tablet');}
 function startBase(){document.getElementById('loliteModeChooser')?.remove();document.getElementById('boot')?.remove();const d=document.getElementById('desktop');if(d){d.classList.remove('hidden');d.style.display='block'}try{window.loadPrefs?.()}catch(e){console.warn(e)}try{window.renderIcons?.()}catch(e){console.warn(e)}}
 function startDesktop(){mode='desktop';document.documentElement.classList.remove('mobile-mode','phone-mode','tablet-mode');document.getElementById('loliteMobileShell')?.remove();startBase();window.openApp?.('home','Home',650,450)}
 function startMobile(which){try{mode='mobile';device=which==='tablet'?'tablet':'phone';startBase();document.documentElement.classList.remove('phone-mode','tablet-mode');document.documentElement.classList.add('mobile-mode',device+'-mode');document.getElementById('icons')?.classList.add('hidden');document.getElementById('taskbar')?.classList.add('hidden');document.getElementById('loliteMobileShell')?.remove();buildShell();window.dispatchEvent(new CustomEvent('lolite:modechange',{detail:{mode,device}}))}catch(e){console.error(e);alert('Mobile Lolite could not start: '+(e?.message||e))}}
 function openApp(id){if(id==='home'){document.querySelectorAll('#windows .window').forEach(w=>window.closeWin?.(w.dataset.windowId));shell?.classList.remove('app-open');return}const title=appName(id);window.openApp?.(id,title,850,650);const win=document.querySelector('.window[data-window-id="'+CSS.escape(id)+'"]');if(win){win.style.zIndex='100002';const h=win.querySelector('.titlebar strong');if(h)h.textContent=title}}
 function buildShell(){shell=document.createElement('div');shell.id='loliteMobileShell';shell.innerHTML='<div class="lm-statusbar"><span id="lmTime"></span><span>◉ ▰ <button id="lmQuick">☰</button></span></div><div class="lm-mobile-head"><h1>Good day.</h1><p>Your Lolite, anywhere.</p></div><label class="lm-mobile-search">⌕ <input id="lmSearch" placeholder="Search apps…" autocomplete="off"></label><div class="lm-app-scroll"><div class="lm-section-label">Your apps</div><div class="lm-app-grid" id="lmGrid"></div></div><div class="lm-dock-wrap"><div class="lm-dock" id="lmDock"></div></div><div class="lm-bottom-nav"><button class="lm-nav-btn" id="lmBackBtn">‹</button><div class="lm-home-indicator"></div><button class="lm-nav-btn" id="lmHomeBtn">○</button></div>';const d=document.getElementById('desktop');if(!d)throw Error('Desktop container is missing');d.appendChild(shell);shell.style.display='flex';shell.style.zIndex='99999';
 const render=q=>{const grid=shell.querySelector('#lmGrid');const list=APPS.filter(a=>!q||a[1].toLowerCase().includes(q.toLowerCase()));grid.innerHTML=list.map(a=>'<button class="lm-app-icon" data-app="'+a[0]+'"><span class="lm-icon-tile">'+a[2]+'</span><span>'+a[1]+'</span></button>').join('');grid.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>openApp(b.dataset.app))};shell.querySelector('#lmSearch').oninput=e=>render(e.target.value.trim());shell.querySelector('#lmSearch').onkeydown=e=>{if(e.key==='Enter')shell.querySelector('#lmGrid [data-app]')?.click()};shell.querySelector('#lmHomeBtn').onclick=()=>{document.querySelectorAll('#windows .window').forEach(w=>window.closeWin?.(w.dataset.windowId));shell.style.display='flex'};shell.querySelector('#lmBackBtn').onclick=()=>{if(quick){quick.remove();quick=null}else{document.querySelectorAll('#windows .window').forEach(w=>window.closeWin?.(w.dataset.windowId));shell.style.display='flex'}};shell.querySelector('#lmQuick').onclick=()=>{if(quick){quick.remove();quick=null;return}quick=document.createElement('div');quick.className='lm-quick';quick.innerHTML='<h3>Quick settings</h3><button data-action="settings">⚙ All settings</button><button data-action="motion">◌ Toggle reduced motion</button><button data-action="home">⌂ Home</button><p>Wi-Fi and sound indicators are visual only.</p>';shell.appendChild(quick);quick.querySelectorAll('button').forEach(b=>b.onclick=()=>{const action=b.dataset.action;if(action==='settings')openApp('settings');else if(action==='motion'){const on=!document.documentElement.classList.contains('reduce');document.documentElement.classList.toggle('reduce',on);localStorage.reduce=on?'true':'false'}else{quick.remove();quick=null;shell.style.display='flex'}})};
 const dock=['home','games','files','appstore','settings'];shell.querySelector('#lmDock').innerHTML=dock.map(id=>{const a=APPS.find(x=>x[0]===id);return '<button class="lm-app-icon" data-app="'+id+'" aria-label="'+a[1]+'"><span class="lm-icon-tile">'+a[2]+'</span></button>'}).join('');shell.querySelectorAll('#lmDock [data-app]').forEach(b=>b.onclick=()=>openApp(b.dataset.app));render('');const tick=()=>{const e=shell?.querySelector('#lmTime');if(e)e.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};tick();setInterval(tick,15000)}
 function init(){window.LoliteDeviceMode={showChooser:chooser,startMobile,startDesktop,mode:()=>({mode,device})}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();