/* Lolite OS virtual filesystem + ZIP support. Browser-only, persistent with IndexedDB. */
const FileOS=(()=>{
  const DB='lolite-fs',STORE='files';let dbp;
  const openDB=()=>dbp||(dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'path'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}));
  async function put(path,data){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({path,data,updated:Date.now()});tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  async function all(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function remove(path){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(path);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  const esc=s=>String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));
  function filesPage(){setTimeout(render,0);return `<div class="files-app"><div class="file-toolbar"><button class="primary" onclick="FileOS.chooseUpload()">＋ Upload</button><button class="soft" onclick="FileOS.newFolder()">＋ Folder</button><button class="soft" onclick="FileOS.chooseZip()">📦 Open ZIP</button><button class="soft" onclick="FileOS.makeZip()">⇩ Create ZIP</button></div><div id="fileStatus" class="muted">Persistent storage · IndexedDB</div><div id="fileList" class="file-list"></div><input id="fileUpload" type="file" multiple hidden onchange="FileOS.handleUpload(this.files)"><input id="zipUpload" type="file" accept=".zip,application/zip" hidden onchange="FileOS.handleZip(this.files[0])"></div>`}
  async function render(){const box=document.querySelector('#fileList');if(!box)return;const rows=await all();if(!rows.length){box.innerHTML='<div class="empty"><div>📁</div><b>This folder is empty</b><span class="muted">Upload files or extract a game ZIP to get started.</span></div>';return}rows.sort((a,b)=>a.path.localeCompare(b.path));box.innerHTML=rows.map(r=>`<div class="file-row"><span class="file-icon">${r.path.endsWith('/')?'📁':r.path.toLowerCase().endsWith('.zip')?'📦':'📄'}</span><div class="file-name"><b>${esc(r.path)}</b><small>${r.data instanceof Blob?Math.round(r.data.size/1024)+' KB':'Saved'}</small></div><button class="soft" onclick="FileOS.deleteFile('${encodeURIComponent(r.path)}')">Delete</button></div>`).join('')}
  function chooseUpload(){document.querySelector('#fileUpload')?.click()}
  function chooseZip(){document.querySelector('#zipUpload')?.click()}
  async function handleUpload(list){for(const f of [...list])await put(f.name,f);toast('Uploaded '+list.length+' file'+(list.length===1?'':'s'));render()}
  async function newFolder(){const name=prompt('Folder name');if(!name)return;await put(name.replace(/\\/g,'').replace(/\/$/,'')+'/',new Blob());toast('Created folder');render()}
  async function deleteFile(enc){const path=decodeURIComponent(enc);if(!confirm('Delete '+path+'?'))return;await remove(path);toast('Deleted');render()}
  async function handleZip(file){if(!file)return;try{const entries=await readZip(file);for(const e of entries){if(e.name.endsWith('/'))await put(e.name,new Blob());else await put(e.name,e.blob)}toast('Extracted '+entries.filter(e=>!e.name.endsWith('/')).length+' files');render();registerGames(entries)}catch(e){console.error(e);toast('Could not extract that ZIP')};document.querySelector('#zipUpload').value=''}
  async function readZip(file){const buf=await file.arrayBuffer(),dv=new DataView(buf),u16=o=>dv.getUint16(o,true),u32=o=>dv.getUint32(o,true);let eocd=-1;for(let p=buf.byteLength-22;p>=Math.max(0,buf.byteLength-66000);p--){if(u32(p)===0x06054b50){eocd=p;break}}if(eocd<0)throw Error('Not ZIP');const count=u16(eocd+10),cdSize=u32(eocd+12),cdOff=u32(eocd+16);let p=cdOff,out=[];for(let i=0;i<count;i++){if(u32(p)!==0x02014b50)throw Error('Bad central directory');const method=u16(p+10),compSize=u32(p+20),uncompSize=u32(p+24),nameLen=u16(p+28),extraLen=u16(p+30),commentLen=u16(p+32),localOff=u32(p+42);const name=new TextDecoder().decode(new Uint8Array(buf,p+46,nameLen));const lp=localOff;const ln=u16(lp+26),le=u16(lp+28);const data=new Uint8Array(buf,lp+30+ln+le,compSize);let blob;if(method===0)blob=new Blob([data]);else if(method===8){const ds=new DecompressionStream('deflate-raw');blob=new Response(new Blob([data]).stream().pipeThrough(ds)).blob()}else throw Error('Unsupported compression');out.push({name,blob,uncompSize});p+=46+nameLen+extraLen+commentLen}return out}
  async function makeZip(){const rows=(await all()).filter(x=>!x.path.endsWith('/'));if(!rows.length){toast('No files to zip');return}const parts=[],central=[];let offset=0;for(const r of rows){const bytes=new Uint8Array(await r.data.arrayBuffer()),name=new TextEncoder().encode(r.path),crc=crc32(bytes);const head=new Uint8Array(30+name.length),dv=new DataView(head.buffer);dv.setUint32(0,0x04034b50,true);dv.setUint16(4,20,true);dv.setUint16(8,0,true);dv.setUint16(10,0,true);dv.setUint32(14,crc,true);dv.setUint32(18,bytes.length,true);dv.setUint32(22,bytes.length,true);dv.setUint16(26,name.length,true);head.set(name,30);parts.push(head,bytes);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,crc,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=head.length+bytes.length}const centralOffset=offset,centralSize=central.reduce((n,x)=>n+x.length,0);parts.push(...central);const end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,rows.length,true);ev.setUint16(10,rows.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,centralOffset,true);parts.push(end);downloadBlob(new Blob(parts,{type:'application/zip'}),'lolite-files.zip');toast('Created ZIP')}
  function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function registerGames(entries){const html=entries.find(e=>/^(.*\/)?index\.html$/i.test(e.name));if(!html)return;const root=html.name.replace(/index\.html$/i,'');const title=root.split('/').filter(Boolean).pop()||'Installed Game';const installs=JSON.parse(localStorage.loliteGames||'[]');if(!installs.some(x=>x.path===root)){installs.push({title,path:root,installed:Date.now()});localStorage.loliteGames=JSON.stringify(installs);toast(title+' added to Game Library')}}
  return {filesPage,chooseUpload,chooseZip,handleUpload,handleZip,newFolder,deleteFile,makeZip,render,all,put,registerGames};
})();
