/* Lolite OS 3.7.0 — unique animated game art */
(()=>{
 const CSS=`
 @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
 .store{display:grid;grid-template-columns:226px minmax(0,1fr);height:100%;min-height:540px;margin:-20px;background:#0b0e13;color:#eef2f8;overflow:hidden;font-family:'DM Sans','Segoe UI',sans-serif;letter-spacing:0}
 .store *{box-sizing:border-box}.store button,.store input{font:inherit}.store-side{display:flex;flex-direction:column;gap:22px;background:#0d1118;border-right:1px solid #202834;padding:23px 14px;min-width:0}
 .store-brand{padding:2px 12px 17px;border-bottom:1px solid #202834;font:700 20px 'Space Grotesk','Segoe UI',sans-serif;letter-spacing:-.7px}.store-brand span{display:block;margin-top:4px;font:600 10px 'DM Sans',sans-serif;letter-spacing:2px;color:#7e8a9c}
 .store-nav-label{padding:0 12px 8px;color:#657184;font-size:10px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase}
 .store-nav{display:grid;gap:4px}.store-nav button{display:flex;align-items:center;gap:11px;width:100%;padding:10px 12px;border:1px solid transparent;border-radius:8px;background:transparent;color:#a8b2c1;text-align:left;font-size:13px;cursor:pointer;transition:background .15s,border-color .15s}
 .store-nav button:hover{background:#171e28;color:#f4f6fa}.store-nav button.active{background:#1b2030;border-color:#34324f;color:#fff}.store-nav .nav-mark{display:inline-grid;place-items:center;width:22px;height:22px;border-radius:6px;background:#202937;color:#a7b7d3;font-size:10px;font-weight:700}.store-nav button.active .nav-mark{background:#7167df;color:#fff}
 .store-side-footer{margin-top:auto;padding:13px 12px;border-top:1px solid #202834;color:#657184;font-size:11px;line-height:1.7}
 .store-main{min-width:0;overflow:auto;padding:26px clamp(16px,3vw,36px) 42px;background:radial-gradient(ellipse at 84% -12%,#1b2540 0,transparent 34%),#0b0e13;scrollbar-color:#303b4c transparent}
 .store-top{display:flex;align-items:center;gap:14px;position:sticky;top:-26px;z-index:5;padding:0 0 18px;background:linear-gradient(#0b0e13 82%,#0b0e1300)}
 .store-search-wrap{position:relative;flex:1;min-width:0}.store-search-mark{position:absolute;left:14px;top:50%;transform:translateY(-50%);color:#77859a;font-size:15px;pointer-events:none}
 .store-search{width:100%;height:43px;padding:0 14px 0 39px;border:1px solid #283241!important;border-radius:8px!important;background:#111720!important;color:#f4f6fb!important;outline:none}.store-search:focus{border-color:#7268dc!important;box-shadow:0 0 0 3px #7268dc20}
 .store-count-pill{white-space:nowrap;color:#8d9aab;font-size:12px}
 .store-hero{position:relative;display:flex;align-items:center;justify-content:space-between;gap:20px;min-height:230px;margin:0 0 31px;padding:clamp(23px,3vw,38px);overflow:hidden;border:1px solid #303c52;border-radius:8px;background:linear-gradient(112deg,#19243a 0%,#151a28 56%,#201d3a 100%);isolation:isolate}
 .store-hero:before{content:'';position:absolute;z-index:-1;width:290px;height:290px;right:7%;top:-105px;border:1px solid #9baaff30;border-radius:50%;box-shadow:0 0 0 28px #9baaff08,0 0 0 58px #9baaff05}
 .store-hero:after{content:'PLAY';position:absolute;right:7%;bottom:-22px;color:#ffffff08;font:700 clamp(66px,10vw,118px)/1 'Space Grotesk',sans-serif;letter-spacing:-8px;pointer-events:none}
 .store-eyebrow{font-size:10px;font-weight:700;letter-spacing:2px;color:#aaa5ff;text-transform:uppercase}.store-hero h1{margin:12px 0 10px;font:700 clamp(27px,3vw,38px)/1.08 'Space Grotesk','Segoe UI',sans-serif;letter-spacing:-1.5px}.store-hero p{max-width:440px;margin:0 0 20px;color:#aab5c6;font-size:13px;line-height:1.7}
 .store-primary{position:relative;z-index:1;padding:10px 15px;border:1px solid #8e85ff;border-radius:8px;background:#7469e8;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.store-primary:hover{background:#8378f5}
 .store-hero-side{position:relative;z-index:1;display:flex;flex-direction:column;align-items:flex-end;gap:8px;min-width:110px}.store-hero-side strong{font:700 48px 'Space Grotesk',sans-serif;letter-spacing:-3px;color:#d4d0ff}.store-hero-side span{font-size:10px;letter-spacing:1.8px;color:#a4aec2}
 .store-section{margin:0 0 34px}.store-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.store-section-head h2{margin:0;font:600 19px 'Space Grotesk','Segoe UI',sans-serif;letter-spacing:-.45px}.store-section-head p{margin:5px 0 0;color:#78869a;font-size:12px}.store-section-head button{padding:7px 9px;border:1px solid #293344;border-radius:7px;background:#121823;color:#b8b2ff;font-size:11px;cursor:pointer}.store-section-head button:hover{background:#1c2330}
 .store-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,205px),1fr));gap:13px}
 .store-card{min-width:0;overflow:hidden;border:1px solid #242e3b;border-radius:8px;background:#111720;transition:transform .16s,border-color .16s,background .16s}.store-card:hover{transform:translateY(-3px);border-color:#4b4d72;background:#151b27}
 .store-cover{position:relative;display:flex;flex-direction:column;justify-content:space-between;align-items:flex-start;min-height:117px;padding:14px;overflow:hidden;background:linear-gradient(135deg,var(--cover-a,#202c40),var(--cover-b,#141923))}
 .store-cover:before{content:'';position:absolute;width:110px;height:110px;right:-25px;top:-42px;border:1px solid #ffffff22;border-radius:8px;transform:rotate(28deg);box-shadow:0 0 0 14px #ffffff06,0 0 0 29px #ffffff04}
 .store-cover:after{content:'';position:absolute;width:70px;height:70px;right:23px;bottom:-42px;border:1px solid #ffffff19;border-radius:50%}
 .store-cover-label{position:relative;z-index:1;color:#d0d8e6;font-size:9px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase}.store-cover-title{position:relative;z-index:1;max-width:90%;font:700 18px/1.1 'Space Grotesk','Segoe UI',sans-serif;letter-spacing:-.45px;color:#fff;text-shadow:0 2px 15px #0005}
 .store-card-body{padding:13px}.store-card h3{overflow:hidden;margin:0 0 6px;font-size:13px;font-weight:700;white-space:nowrap;text-overflow:ellipsis}.store-card-meta{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:12px;color:#78869a;font-size:10px}.store-tag{overflow:hidden;max-width:70%;padding:3px 6px;border:1px solid #30384a;border-radius:4px;color:#a9b2c2;text-overflow:ellipsis;white-space:nowrap}
 .store-play{width:100%;padding:9px 10px;border:1px solid #3b3b65;border-radius:7px;background:#22233b;color:#d9d7ff;font-size:12px;font-weight:700;cursor:pointer}.store-play:hover{background:#34335a;border-color:#6d65b8;color:#fff}
 .store-empty{padding:38px 20px;text-align:center;border:1px dashed #303b4a;border-radius:8px;color:#8995a6;font-size:13px}
 .store-player{height:100%;min-height:0;display:flex;flex-direction:column;gap:10px;background:#0b0e13;color:#eef2f8;font-family:'DM Sans','Segoe UI',sans-serif}.store-player-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.store-player-head strong{font:600 16px 'Space Grotesk',sans-serif}.store-player-actions{display:flex;gap:6px;flex-wrap:wrap}.store-player-actions button{background:#171f2b;border:1px solid #303c4d;border-radius:7px;padding:8px 10px;color:#e9edf6;font-size:11px;cursor:pointer}.store-frame{flex:1;min-height:0;width:100%;border:1px solid #283242;border-radius:8px;background:#05070a}
 .store-player-fullscreen{position:fixed!important;inset:0!important;z-index:2147483000!important;height:100dvh!important;width:100vw!important;padding:12px!important;background:#07090d!important}
 @media(max-width:760px){.store{grid-template-columns:1fr}.store-side{display:none}.store-main{padding:17px}.store-top{top:-17px}.store-hero{min-height:205px}.store-hero-side{display:none}.store-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.store-cover{min-height:100px}.store-card-body{padding:10px}.store-card h3{font-size:12px}}
 @media(max-width:430px){.store-grid{grid-template-columns:1fr}.store-hero h1{font-size:27px}}
 /* Animated game-store artwork: slow ambient gradients and decorative geometry. */
 @keyframes storeAurora{0%,100%{background-position:0% 50%,100% 50%}50%{background-position:100% 50%,0% 50%}}
 @keyframes storeOrbit{0%,100%{transform:translate3d(0,0,0) rotate(28deg)}50%{transform:translate3d(-12px,8px,0) rotate(43deg)}}
 @keyframes storeCoverDrift{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}
 @keyframes storeRingPulse{0%,100%{opacity:.35;transform:scale(.94)}50%{opacity:.8;transform:scale(1.08)}}
 @keyframes storeTextShimmer{0%{background-position:180% 0}100%{background-position:-180% 0}}
 .store-main{background-image:radial-gradient(ellipse at 84% -12%,#1b2540 0,transparent 34%),radial-gradient(ellipse at 12% 35%,#17132b55 0,transparent 35%),linear-gradient(120deg,#0b0e13,#0c1018,#0b0e13);background-size:100% 100%,180% 180%,220% 220%;animation:storeAurora 30s ease-in-out infinite}
 .store-hero{background-image:radial-gradient(ellipse at 88% 15%,#51468a55,transparent 36%),linear-gradient(112deg,#19243a 0%,#151a28 56%,#201d3a 100%),linear-gradient(120deg,#19243a,#28234a,#19243a);background-size:180% 180%,100% 100%,220% 220%;animation:storeAurora 22s ease-in-out infinite}
 .store-hero:before{animation:storeOrbit 18s ease-in-out infinite}
 .store-hero:after{animation:storeRingPulse 7s ease-in-out infinite}
 .store-cover{background-image:radial-gradient(ellipse at 82% 14%,#ffffff24,transparent 35%),linear-gradient(var(--cover-angle,135deg),var(--cover-a,#202c40),var(--cover-b,#141923),var(--cover-a,#202c40));background-size:150% 150%,220% 220%;animation:storeCoverDrift var(--cover-speed,18s) ease-in-out var(--cover-delay,0ms) infinite}
 .store-cover:before{animation:storeOrbit var(--cover-speed,14s) ease-in-out var(--cover-delay,0ms) infinite}
 .store-cover[data-skin="0"]:before{border-radius:50%;transform:rotate(0deg)}
 .store-cover[data-skin="1"]:before{border-radius:2px;clip-path:polygon(50% 0,100% 100%,0 100%)}
 .store-cover[data-skin="2"]:before{border-radius:50% 4px 50% 4px;transform:rotate(45deg)}
 .store-cover[data-skin="3"]:before{border-radius:0;clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%)}
 .store-cover[data-skin="4"]:before{border-radius:50%;box-shadow:0 0 0 12px #ffffff08,0 0 35px var(--cover-a)}
 .store-cover[data-skin="5"]:before{border-radius:10px 50% 10px 50%;transform:rotate(-20deg)}
 .store-cover[data-skin="0"]:after{right:15%;bottom:-35px;width:92px;height:92px}
 .store-cover[data-skin="1"]:after{border-radius:4px;transform:rotate(45deg)}
 .store-cover[data-skin="2"]:after{width:46px;height:46px;right:42px}
 .store-cover[data-skin="3"]:after{border-radius:0;transform:rotate(45deg)}
 .store-cover[data-skin="4"]:after{width:100px;height:100px;right:-10px;bottom:-65px}
 .store-cover[data-skin="5"]:after{border-radius:50% 0 50% 0;transform:rotate(-25deg)}
 .store-cover:after{animation:storeRingPulse 8s ease-in-out infinite}
 .store-card{animation:loliteRiseIn .34s ease-out both}
 .store-card:nth-child(4n+2){animation-delay:.035s}.store-card:nth-child(4n+3){animation-delay:.07s}.store-card:nth-child(4n+4){animation-delay:.105s}
 .store-card:hover .store-cover:before{animation-duration:5s}
 .store-primary,.store-play,.store-nav button,.store-section-head button{transition:transform .18s ease,background .2s,border-color .2s,box-shadow .2s}
 .store-primary:hover,.store-play:hover,.store-section-head button:hover{transform:translateY(-2px);box-shadow:0 7px 20px #7066e52a}
 .store-nav button .nav-mark{transition:transform .18s ease,background .18s}
 .store-nav button:hover .nav-mark{transform:translateX(2px)}
 .store-search{transition:border-color .18s,box-shadow .18s}
 .store-player-head button{transition:background .18s,transform .18s}
 .store-player-head button:hover{transform:translateY(-1px)}
 @media(prefers-reduced-motion:reduce){.store-main,.store-hero,.store-hero:before,.store-hero:after,.store-cover,.store-cover:before,.store-cover:after,.store-card{animation:none!important;transition:none!important}}

 `;
 if(!document.getElementById('lolite-game-store-style')){const s=document.createElement('style');s.id='lolite-game-store-style';document.head.appendChild(s)}document.getElementById('lolite-game-store-style').textContent=CSS;
 const manifest=['clangrybirds2.html','clbadmondaysimulator.html','clbaldicaseoh.html','clbaldisbasics.html','clbaldisbasicsremaster.html','clbitlife.html','clblockblast.html','clcookieclicker.html','clcookieclickermodmenu.html','clcrazycars.html','clcuttherope.html','cldemolitionderbycrashracing.html','cldungeonsanddegenerategambler.html','clescaperoad.html','clescaperoad-2.html','clescaperoad3.html','clfallguys.html','clfireboyandwatergirl2.html','clfireboyandwatergirl3.html','clFNAF.html','clFNAF2.html','clFNAF3.html','clFNAF4.html','clgdbreeze.html','clgorillatag.html','clgranny2.html','clgranny22.html','clgranny3.html','clgrannycreepy.html','clgrannynightmare.html','clgrannyy.html','clgrowagarden.html','clgta3.html','clhalflife.html','clholeio.html','clinfinitecraft.html','clLobotemyDash.html','lolite-2048.html','lolite-pong.html','lolite-sokoban.html','clmario64webgl.html','clmelonplayground.html','clminecraftpocketedition.html','clmotox3m2.html','clmotox3m3.html','clmotox3mm.html','clmotox3mpoolparty.html','clmotox3mspookyland.html','clmotox3mwinter.html','closu.html','clovo2.html','clovodimensions.html','clovofixed.html','clpaperio.html','clpaperio3d.html','clpaperiomania.html','clparkingfury.html','clparkingfury2.html','clparkingfury3.html','clpixelbattlegroundsio.html','clpvz2gardenless.html','PVZM.html','clragollhit.html','clRedBall4.html','clrocketleague.html','clshiftatmidnight.html','slope.html','slope-2-player.html','clslopeplus.html','clsmbremastered.html','clsnowrider.html','clspacewarsbattleground.html','clstickmanhook.html','clsubwaysurfersmiami.html','clsupermariobros.html','clsurvivorio.html','cltemplerun2.html','cltinyfishing.html','clvex3.html','wheely.html','wrestle-bros.html','zombie-rush.html'];
 const pretty=raw=>{const key=raw.replace(/^cl/i,'').replace(/^lolite[-_]/i,'').replace(/\.html?$/i,'').toLowerCase();const known={'angrybirds2':'Angry Birds 2','baldisbasics':'Baldi’s Basics','baldisbasicsremaster':'Baldi’s Basics Remastered','baldicaseoh':'Baldi’s Basics: CaseOh','badmondaysimulator':'Bad Monday Simulator','bitlife':'BitLife','blockblast':'Block Blast','cookieclicker':'Cookie Clicker','cookieclickermodmenu':'Cookie Clicker Mod Menu','crazycars':'Crazy Cars','cuttherope':'Cut the Rope','demolitionderbycrashracing':'Demolition Derby Crash Racing','dungeonsanddegenerategambler':'Dungeons and Degenerate Gamblers','escaperoad':'Escape Road','escaperoad-2':'Escape Road 2','escaperoad3':'Escape Road 3','fallguys':'Fall Guys','fireboyandwatergirl2':'Fireboy and Watergirl 2','fireboyandwatergirl3':'Fireboy and Watergirl 3','fnaf':'Five Nights at Freddy’s','fnaf2':'Five Nights at Freddy’s 2','fnaf3':'Five Nights at Freddy’s 3','fnaf4':'Five Nights at Freddy’s 4','gdbreeze':'Geometry Dash Breeze','gorillatag':'Gorilla Tag','granny2':'Granny 2','granny22':'Granny 2.2','granny3':'Granny 3','grannycreepy':'Granny: Creepy Mod','grannynightmare':'Granny: Nightmare','grannyy':'Granny','growagarden':'Grow a Garden','gta3':'Grand Theft Auto III','halflife':'Half-Life','holeio':'Hole.io','infinitecraft':'Infinite Craft','lobotemydash':'Lobotomy Dash','minecraftpocketedition':'Minecraft: Pocket Edition','melonplayground':'Melon Playground','motox3m':'Moto X3M','motox3m2':'Moto X3M 2','motox3m3':'Moto X3M 3','motox3mpoolparty':'Moto X3M Pool Party','motox3mspookyland':'Moto X3M Spooky Land','motox3mwinter':'Moto X3M Winter','ovo2':'OvO 2','ovodimensions':'OvO Dimensions','ovofixed':'OvO','paperio':'Paper.io','paperio3d':'Paper.io 3D','paperiomania':'Paper.io Mania','parkingfury':'Parking Fury','parkingfury2':'Parking Fury 2','parkingfury3':'Parking Fury 3','pixelbattlegroundsio':'Pixel Battlegrounds.io','pvz2gardenless':'Plants vs. Zombies 2: Gardenless','ragollhit':'Ragdoll Hit','redball4':'Red Ball 4','rocketleague':'Rocket League','shiftatmidnight':'Shift at Midnight','slope-2-player':'Slope 2 Player','slopeplus':'Slope Plus','smbremastered':'Super Mario Bros. Remastered','snowrider':'Snow Rider','spacewarsbattleground':'Space Wars Battleground','stickmanhook':'Stickman Hook','subwaysurfersmiami':'Subway Surfers: Miami','supermariobros':'Super Mario Bros.','survivorio':'Survivor.io','templerun2':'Temple Run 2','tinyfishing':'Tiny Fishing','wrestle-bros':'Wrestle Bros'};if(known[key])return known[key];let s=raw.replace(/^cl/i,'').replace(/^lolite[-_]/i,'').replace(/\.html?$/i,'').replace(/[_-]+/g,' ');s=s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/([A-Za-z])([0-9])/g,'$1 $2').replace(/\s+/g,' ').trim().replace(/\b\w/g,m=>m.toUpperCase());return s.replace(/\bPvz\b/gi,'PVZ').replace(/\bFnaf\b/gi,'FNAF').replace(/\bGta\b/gi,'GTA').replace(/\bIo\b/gi,'IO')};
 const categorize=g=>{const f=g.file.toLowerCase();if(/baldi/.test(f))return 'Baldi’s Basics';if(/fnaf|granny|nightmare|zombie|shiftatmidnight|badmondaysimulator/.test(f))return 'Horror';if(/crazycars|racing|moto|slope|escaperoad|parking|rocketleague|derby|wheely|snowrider/.test(f))return 'Racing';if(/2048|sokoban|blockblast|cookie|cuttherope|fireboy|infinitecraft|ovo|paperio|stickmanhook|tinyfishing/.test(f))return 'Puzzle';if(/growagarden|holeio|pixelbattlegrounds|survivorio|paperio|bitlife|fallguys/.test(f))return 'IO & Casual';if(/minecraft|melonplayground|bitlife|infinitecraft|dungeonsanddegenerategambler|halflife|gta3/.test(f))return 'Simulation & Sandbox';if(/fishing|wrestle|gorilla|football|basketball|sports/.test(f))return 'Sports';if(/mario|angrybirds|pvz|subway|templerun|vex|redball|fireboy|stickman|lobotemy|gd|supermario/.test(f))return 'Platformers & Arcade';return 'Classics'};
 const categoryNames=['All Games','Featured','Popular Games','IO & Casual','Baldi’s Basics','Horror','Racing','Puzzle','Platformers & Arcade','Simulation & Sandbox','Sports','Classics'];
 const navMarks={'All Games':'ALL','Featured':'★','Popular Games':'TOP','IO & Casual':'IO','Baldi’s Basics':'BB','Horror':'HR','Racing':'RACE','Puzzle':'PUZ','Platformers & Arcade':'PLAY','Simulation & Sandbox':'SIM','Sports':'SPRT','Classics':'CL'};
 let games=manifest.map(file=>({file,title:pretty(file),url:'html games/'+encodeURIComponent(file),category:categorize({file})}));
 let active='Featured',query='';
 const isPopular=g=>/baldi|fnaf|granny|mario|angrybirds|pvz|minecraft|growagarden|slope|escaperoad|gta|cookieclicker/i.test(g.file);
 const matchesCategory=g=>active==='All Games'||active==='Featured'||active==='Popular Games'?true:g.category===active;
 const filtered=()=>games.filter(g=>matchesCategory(g)&&(!query||g.title.toLowerCase().includes(query.toLowerCase())||g.category.toLowerCase().includes(query.toLowerCase()))&&(active!=='Popular Games'||isPopular(g)));
 const coverPalette=g=>{let hash=0;for(const ch of g.file)hash=(Math.imul(hash,31)+ch.charCodeAt(0))>>>0;const hue=hash%360,hue2=(hue+48+(hash%73))%360;return [`hsl(${hue} 62% 28%)`,`hsl(${hue2} 48% 13%)`,`${12+(hash%13)}s`,String(hash%6),`-${hash%17000}ms`]};
 const card=g=>{const colors=coverPalette(g);return '<article class="store-card"><div class="store-cover" data-skin="'+colors[3]+'" style="--cover-a:'+colors[0]+';--cover-b:'+colors[1]+';--cover-speed:'+colors[2]+';--cover-delay:'+colors[4]+'"><span class="store-cover-label">'+g.category+'</span><strong class="store-cover-title">'+g.title+'</strong></div><div class="store-card-body"><h3 title="'+g.title+'">'+g.title+'</h3><div class="store-card-meta"><span class="store-tag">'+g.category+'</span><span>In library</span></div><button class="store-play" type="button" onclick=\'window.loliteStorePlay("'+g.file+'")\'>Play game <span aria-hidden="true">↗</span></button></div></article>'};
 const section=(title,list)=>list.length?'<section class="store-section"><div class="store-section-head"><div><h2>'+title+'</h2><p>'+list.length+' games to explore</p></div><button type="button" onclick=\'window.loliteStoreCategory("'+title+'")\'>View collection →</button></div><div class="store-grid">'+list.slice(0,8).map(card).join('')+'</div></section>':'';
 function render(){const root=document.querySelector('.store-main');if(!root)return;const top='<div class="store-top"><div class="store-search-wrap"><span class="store-search-mark" aria-hidden="true">⌕</span><input class="store-search" aria-label="Search games" placeholder="Search your library…" value="'+query.replace(/&/g,'&amp;').replace(/"/g,'&quot;')+'" oninput="window.loliteStoreSearch(this.value)"></div><span class="store-count-pill">'+games.length+' titles</span></div>';
 if(query||!['Featured','All Games'].includes(active)){const list=filtered();root.innerHTML=top+'<section class="store-section"><div class="store-section-head"><div><h2>'+active+'</h2><p>'+list.length+' matching games</p></div></div>'+(list.length?'<div class="store-grid">'+list.map(card).join('')+'</div>':'<div class="store-empty">No games found. Try another title or category.</div>')+'</section>';return}
 if(active==='All Games'){root.innerHTML=top+'<section class="store-section"><div class="store-section-head"><div><h2>All games</h2><p>Every game in your Lolite library.</p></div></div><div class="store-grid">'+games.map(card).join('')+'</div></section>';return}
 root.innerHTML=top+'<section class="store-hero"><div><span class="store-eyebrow">LOLITE GAME LIBRARY</span><h1>Less browsing.<br>More playing.</h1><p>Your games, organised into collections. Find something new, jump back into a favourite, and launch it right from your desktop.</p><button class="store-primary" type="button" onclick="window.loliteStoreCategory(\'All Games\')">Explore all '+games.length+' games <span aria-hidden="true">→</span></button></div><div class="store-hero-side"><strong>'+String(games.length).padStart(2,'0')+'</strong><span>GAMES IN LIBRARY</span></div></section>'+section('Popular Games',games.filter(isPopular))+section('IO & Casual',games.filter(g=>g.category==='IO & Casual'))+section('Horror',games.filter(g=>g.category==='Horror'))+section('Racing',games.filter(g=>g.category==='Racing'))+section('Platformers & Arcade',games.filter(g=>g.category==='Platformers & Arcade'))+section('Puzzle',games.filter(g=>g.category==='Puzzle'))}
 function shell(){return '<div class="store"><aside class="store-side"><div class="store-brand">lolite<span>GAME LIBRARY</span></div><div><div class="store-nav-label">Browse library</div><nav class="store-nav">'+categoryNames.map(c=>'<button type="button" class="'+(active===c?'active':'')+'" data-category="'+c+'" aria-pressed="'+(active===c)+'" onclick=\'window.loliteStoreCategory("'+c+'")\'><span class="nav-mark" aria-hidden="true">'+navMarks[c]+'</span><span>'+c+'</span></button>').join('')+'</nav></div><div class="store-side-footer">LOLITE OS · GAME LIBRARY<br>One place for your collection.</div></aside><main class="store-main"><div class="store-empty">Loading your library…</div></main></div>'}
 window.loliteStoreCategory=c=>{if(!categoryNames.includes(c)&&!['IO Games','Arcade','IO & Casual'].includes(c))return;active=c;query='';document.querySelectorAll('.store-nav button').forEach(b=>{const on=b.dataset.category===c;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});render()};
 window.loliteStoreSearch=q=>{query=q;render()};
 window.loliteStorePlay=file=>{const game=games.find(g=>g.file===file);if(!game)return;const id='store-game-'+file.replace(/[^a-z0-9]/gi,'').slice(0,24);openApp(id,game.title,1000,720);let tries=0;const fill=()=>{const c=state.windows[id]?.el.querySelector('.content');if(!c){if(++tries<40)setTimeout(fill,25);return}c.innerHTML='<div class="store-player"><div class="store-player-head"><strong>'+game.title+'</strong><div class="store-player-actions"><button type="button" onclick=\'window.loliteStoreFullscreen("'+id+'")\'>Enter fullscreen</button><button type="button" onclick=\'window.loliteStoreOpenSeparate("'+game.url+'")\'>Open separately ↗</button></div></div><iframe class="store-frame" title="'+game.title+'" src="'+game.url+'" allow="fullscreen; gamepad; autoplay; pointer-lock" allowfullscreen loading="eager"></iframe></div>'};fill()};
 window.loliteStoreFullscreen=id=>{const root=state.windows[id]?.el.querySelector('.content');const frame=root?.querySelector('iframe');const target=frame||root;if(!target)return;const req=target.requestFullscreen||target.webkitRequestFullscreen;if(req)Promise.resolve(req.call(target)).catch(()=>toast('Fullscreen was blocked. Try the fullscreen control inside the game.'));else toast('Fullscreen is not supported by this browser.')};
 window.loliteStoreOpenSeparate=url=>window.open(url,'_blank','noopener,noreferrer');
 const oldPage=window.page;window.page=function(id){if(id==='games'){setTimeout(render,0);return shell()}return oldPage(id)};
})();