/* Lolite OS game library: fast HTML/HTM discovery, search and reliable launch controls. */
(()=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let htmlGames=[],loading=false,lastDiscovery=0;
 const basePage=window.page;
 const titleFromFile=file=>{const key=file.replace(/\.(?:html?|HTML?)$/,'');const known={clgrannyy:'Granny Original',clgta3:'GTA III',clpaperio:'Paper.io 2',clslopeplus:'Slope Plus','GTA Vice City':'GTA Vice City'};return known[key]||key.replace(/^cl/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())};
 const mature=name=>['Granny Original','GTA III','GTA Vice City'].includes(name);
 async function discover(force=false){if(loading)return htmlGames;if(!force&&Date.now()-lastDiscovery<15000&&htmlGames.length)return htmlGames;loading=true;try{const r=await fetch('https://api.github.com/repos/darby9123-arch/Lolite-OS/contents/html%20games',{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw Error('discovery failed');const items=await r.json(),seen=new Set();htmlGames=items.filter(x=>x.type==='file'&&/\.(html|htm)$/i.test(x.name)).map(x=>({name:titleFromFile(x.name),file:x.name})).filter(g=>{const k=g.file.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.name.localeCompare(b.name));lastDiscovery=Date.now();return htmlGames}catch(e){return htmlGames}finally{loading=false}}
 const card=g=>`<article class="card html-game-card"><h3>🎮 ${esc(g.name)}</h3>${mature(g.name)?'<span class="mature-badge">MATURE</span>':''}<span class="html-game-badge">HTML / HTM</span><p class="muted">Repository game · loads only when opened.</p><button class="primary html-play" data-file="${encodeURIComponent(g.file)}" data-name="${encodeURIComponent(g.name)}">Play</button></article>`;
 function storeMarkup(){return `<div class="card" style="margin-top:18px" id="game-store-list"><div class="html-game-head"><div><h3>🛍️ Game Store</h3><p class="muted">HTML and HTM games from the repository.</p></div><button id="refreshGamesBtn" class="soft">↻ Refresh</button></div><div class="game-search"><input id="gameStoreSearch" type="search" placeholder="Search HTML games…" autocomplete="off"><span id="gameStoreCount" class="muted"></span></div><div id="htmlGameGrid" class="html-game-grid"></div></div>`}
 function renderStore(){const grid=document.getElementById('htmlGameGrid');if(!grid)return;const q=(document.getElementById('gameStoreSearch')?.value||'').trim().toLowerCase();const rows=htmlGames.filter(g=>g.name.toLowerCase().includes(q)||g.file.toLowerCase().includes(q));grid.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty"><div>🔎</div><b>No matching games</b><span class="muted">Try another game name.</span></div>';const count=document.getElementById('gameStoreCount');if(count)count.textContent=`${rows.length} of ${htmlGames.length} games`}
 function wireStore(){document.getElementById('gameStoreSearch')?.addEventListener('input',renderStore);document.getElementById('refreshGamesBtn')?.addEventListener('click',async()=>{await discover(true);renderStore()});document.getElementById('htmlGameGrid')?.addEventListener('click',e=>{const b=e.target.closest('.html-play');if(b){const name=decodeURIComponent(b.dataset.name),file=decodeURIComponent(b.dataset.file);const open=()=>launchHTMLGame(name,file);mature(name)&&window.LoliteMatureGames?window.LoliteMatureGames.gate(name,open):open()}});renderStore()}
 window.refreshGameStore=async()=>{await discover(true);renderStore()};
 window.launchHTMLGame=(name,file)=>{const clean=String(file||'').replace(/^html games[\\/]/i,'');const id='html-game-'+clean.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');if(state.windows[id]){restoreWin(id);return}openApp(id,name,900,650);setTimeout(()=>{const c=state.windows[id]?.el.querySelector('.content');if(!c)return;const local='html%20games/'+clean.split(/[\\/]/).map(encodeURIComponent).join('/');const raw='https://raw.githubusercontent.com/darby9123-arch/Lolite-OS/main/html%20games/'+clean.split(/[\\/]/).map(encodeURIComponent).join('/');c.innerHTML='<iframe title="'+esc(name)+'" src="'+local+'" loading="eager" allow="fullscreen; gamepad; autoplay" tabindex="0" style="width:100%;height:100%;min-height:560px;border:0;border-radius:12px;background:#000"></iframe>';const frame=c.querySelector('iframe');frame.addEventListener('load',()=>frame.focus(),{once:true});frame.addEventListener('error',()=>{if(frame.dataset.fallback)return;frame.dataset.fallback='1';frame.src=raw},{once:true});c.addEventListener('pointerdown',()=>frame.focus())},80)};
 const launchHTMLOriginal=window.launchHTMLGame;window.launchHTMLGame=(name,file)=>{if(mature(name)&&window.LoliteMatureGames)return window.LoliteMatureGames.gate(name,()=>launchHTMLOriginal(name,file));return launchHTMLOriginal(name,file)};
 window.page=function(id){if(id==='games')return `<h2>🎮 Default Games</h2><p class="muted">Playable built-in games. Search to jump straight to a game.</p><div class="game-search"><input id="defaultGameSearch" type="search" placeholder="Search default games…" autocomplete="off"><span id="defaultGameCount" class="muted"></span></div><div id="defaultGameGrid" class="cards"></div>`;if(id==='game-store'){setTimeout(async()=>{await discover();wireStore()},0);return `<h2>🛍️ Game Store</h2><p class="muted">Repository HTML and HTM games are discovered quickly and loaded only when you press Play.</p>${storeMarkup()}`}return basePage(id)};
 const map={Minefield:'minefield','Tic-tac-toe':'tic-tac-toe','Memory Puzzle':'memory-puzzle',Simon:'simon',Nibbles:'nibbles',Snake:'snake',Breakout:'breakout','2048':'2048','Sliding Puzzle':'sliding-puzzle',Maze:'maze',Tetris:'tetris','Connect Four':'connect-four'};window.__loliteGameMap=map;
 const renderDefault=()=>{const grid=document.getElementById('defaultGameGrid');if(!grid)return;const q=(document.getElementById('defaultGameSearch')?.value||'').toLowerCase();const rows=Object.keys(map).filter(g=>g.toLowerCase().includes(q));grid.innerHTML=rows.map(g=>`<div class="card"><div class="game-icon">🎮</div><h3>${esc(g)}</h3><p class="muted">Ready to play</p><button class="primary default-play" data-game="${encodeURIComponent(g)}">Play</button></div>`).join('');const count=document.getElementById('defaultGameCount');if(count)count.textContent=`${rows.length} games`};
 function wireDefault(){document.getElementById('defaultGameSearch')?.addEventListener('input',renderDefault);document.getElementById('defaultGameGrid')?.addEventListener('click',e=>{const b=e.target.closest('.default-play');if(b)launchGame(decodeURIComponent(b.dataset.game))});renderDefault()}
 const pageHook=window.page;window.page=function(id){const r=pageHook(id);if(id==='games')setTimeout(wireDefault,0);return r};
 const oldRender=window.renderIcons;window.renderIcons=()=>{oldRender?.();const box=document.querySelector('#icons');if(!box)return;const a=[['⌂','Home','home'],['🎮','Default Games','games'],['🛍️','Game Store','game-store'],['📁','Files','files'],['🌐','Lolite Browser','browser'],['⚙','Settings','settings']];box.innerHTML=a.map(x=>`<button class="desktop-icon" ondblclick="openApp('${x[2]}','${x[1]}')"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')};
 setTimeout(()=>{window.renderIcons?.();discover()},500);

/* V3.0.3 uploaded-games correction */
(()=>{
 const uploaded=[];
 const files=[];
 function uploadedGamePath(name){
   return 'html games/'+name;
 }
 window.launchUploadedGame=function(file,name){
   const safe=String(file||'').replace(/^html games[\\/]/i,'');
   const src=uploadedGamePath(safe).split(' ').join('%20').split('/').map((x,i)=>i?'/' + encodeURIComponent(x):x).join('');
   const id='uploaded-'+safe.toLowerCase().replace(/[^a-z0-9]+/g,'-');
   openApp(id,name||safe,960,700);
   setTimeout(()=>{
     const w=state.windows[id],root=w?.el?.querySelector('.content');if(!root)return;
     root.innerHTML='<div class="uploaded-game"><div class="uploaded-gamebar"><strong>'+String(name||safe).replace(/[&<>]/g,'')+'</strong><button class="soft" type="button" onclick="this.parentElement.nextElementSibling.requestFullscreen?.()">Fullscreen</button></div><iframe src="'+src+'" title="Game" allow="fullscreen;gamepad;autoplay" style="width:100%;height:calc(100% - 42px);min-height:500px;border:0;border-radius:10px;background:#000"></iframe></div>';
   },80);
 };
})();
})();
