/* Separates built-in/default games from repository HTML games. */
(()=>{
  const defaultGames=['Pong','Minefield','Tic-tac-toe','Memory Puzzle','Simon','Sliding Puzzle','Duck Hunt','Yahtzee','Maze','Typespeed','Lunar Lander','Nibbles','Pixel World','Tron','Asteroids','Arkanoid','Flood It','Quoridor','Space Invaders','Scrabble','Othello','Quarto','Fruit Ninja','Tetris','Minotaurus','Connect Four','Missile Command','Abalone','Sokoban','Dr. Mario','Puyo Puyo','Checkers','Pipe Dream','Blackjack','Traffic Jam','Last Stand','Bloxorz','Bejeweled','Zoop','Rampart','Mancala','Bubble Shooter','Scorched Earth','Worms','Gorillas','Angry Birds','Stratego','Risk','Go','Diner Dash','Fire N Ice','Chess'];
  const playable={Minefield:'minefield','Tic-tac-toe':'tic-tac-toe','Memory Puzzle':'memory-puzzle',Simon:'simon',Nibbles:'nibbles'};
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const titleFromFile=file=>{const key=file.replace(/\.(?:html?|HTML?)$/,'');const known={clgrannyy:'Granny Original',clgta3:'GTA III',clpaperio:'Paper.io 2',clslopeplus:'Slope Plus'};return known[key]||key.replace(/^cl/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())};
  let htmlGames=[];
  const htmlGrid=()=>`<div class="card" style="margin-top:18px" id="game-store-list"><div class="html-game-head"><div><h3>🛍️ Game Store</h3><p class="muted">HTML and HTM games from the repository.</p></div><button onclick="refreshGameStore()">↻ Refresh</button></div><div class="html-game-grid">${htmlGames.length?htmlGames.map(g=>`<div class="card html-game-card"><h3>🎮 ${esc(g.name)}</h3><span class="html-game-badge">HTML / HTM</span><p>Repository game. Launches in a Lolite OS window.</p><button class="primary" onclick="launchHTMLGame('${esc(g.name)}','${esc(g.file)}')">Play</button></div>`).join(''):'<div class="empty"><div>🛍️</div><b>No HTML games found</b><span class="muted">Add an .html or .htm game to the html games folder, then refresh.</span></div>'}</div></div>`;
  window.refreshGameStore=async()=>{try{const r=await fetch('https://api.github.com/repos/darby9123-arch/Lolite-OS/contents/html%20games',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error('discovery failed');const items=await r.json();const seen=new Set();htmlGames=items.filter(x=>x.type==='file'&&/\.html?$/i.test(x.name)).map(x=>({name:titleFromFile(x.name),file:x.name})).filter(x=>{const k=x.file.toLowerCase();if(seen.has(k))return false;seen.add(k);return true});const box=document.getElementById('game-store-list');if(box)box.outerHTML=htmlGrid()}catch(e){const box=document.getElementById('game-store-list');if(box){const note=box.querySelector('.html-game-head .muted');if(note)note.textContent='Could not refresh the repository right now.'}}};
  const basePage=window.page;
  window.page=function(id){
    if(id==='games')return `<h2>🎮 Default Games</h2><p class="muted">Built-in Lolite games. These are separate from the HTML Game Store.</p><div class="cards">${defaultGames.map(g=>`<div class="card"><h3>🎮 ${esc(g)}</h3><button class="soft" onclick="launchGame('${esc(g)}')">${playable[g]||g==='Pong'?'Play':'Coming soon'}</button></div>`).join('')}</div>`;
    if(id==='game-store'){setTimeout(()=>refreshGameStore(),0);return `<h2>🛍️ Game Store</h2><p class="muted">Browse HTML and HTM games added to the Lolite OS repository.</p>${htmlGrid()}`}
    return basePage(id);
  };
  window.launchHTMLGame=(name,file)=>{const id='html-game-'+file.replace(/[^a-z0-9]+/gi,'-')+'-'+Date.now();openApp(id,name,900,650);const w=state.windows[id]?.el.querySelector('.content');if(w)w.innerHTML=`<iframe title="${esc(name)}" src="html%20games/${encodeURIComponent(file)}" style="width:100%;height:100%;min-height:560px;border:0;border-radius:12px;background:#000"></iframe>`};
  window.renderIcons=()=>{const a=[['⌂','Home','home'],['🎮','Default Games','games'],['🛍️','Game Store','game-store'],['📁','Files','files'],['🌐','Lolite Browser','browser'],['⚙','Settings','settings']];const box=document.querySelector('#icons');if(box)box.innerHTML=a.map(x=>`<button class="desktop-icon" ondblclick="openApp('${x[2]}','${x[1]}')"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')};
  const start=document.querySelector('#startBtn');if(start)start.onclick=()=>{const box=document.querySelector('#start');if(!box)return;box.classList.toggle('hidden');box.innerHTML='<div class="start-head"><div class="boot-logo">L</div><div><b>lolite OS</b><div class="muted">Your desktop, upgraded.</div></div></div><div class="start-list">'+[['⌂','Home','home'],['🎮','Default Games','games'],['🛍️','Game Store','game-store'],['📁','Files','files'],['🌐','Browser','browser'],['⚙','Settings','settings']].map(x=>`<button onclick="openApp('${x[2]}','${x[1]}');document.querySelector('#start').classList.add('hidden')">${x[0]} &nbsp; ${x[1]}</button>`).join('')+'</div>'};
  setTimeout(()=>{window.renderIcons?.();refreshGameStore()},0);
})();
