/* Lolite OS 3.9.0 — WebGL liquid-glass renderer.
   WebGL renders animated fluid caustics, chromatic edge light and specular reflections.
   Native backdrop-filter supplies the live backdrop; this shader supplies the moving optical surface. */
(()=>{'use strict';
 const root=document.documentElement,selectors=['#taskbar','.window','.panel'],active=new Map();
 const reduce=()=>root.classList.contains('reduce')||root.classList.contains('reduce-motion')||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const vertex='attribute vec2 a_position; varying vec2 v_uv; void main(){v_uv=a_position*0.5+0.5;gl_Position=vec4(a_position,0.0,1.0);}';
 const fragment="precision mediump float;\nvarying vec2 v_uv;\nuniform vec2 u_resolution;\nuniform float u_time;\nuniform float u_strength;\nfloat hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}\nfloat noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.0,0.0)),f.x),mix(hash(i+vec2(0.0,1.0)),hash(i+vec2(1.0,1.0)),f.x),f.y);}\nvoid main(){\n vec2 uv=v_uv; float t=u_time; float aspect=max(u_resolution.x/max(u_resolution.y,1.0),0.25); vec2 p=(uv-0.5)*vec2(aspect,1.0);\n float a=sin(p.x*7.2+sin(p.y*4.1+t*0.43)*1.8-t*0.68); float b=cos(p.y*9.0+sin(p.x*5.3-t*0.31)*1.5+t*0.52); float field=a*0.55+b*0.45;\n float grain=noise(uv*vec2(8.0,5.0)+vec2(t*0.045,-t*0.035));\n float bands=pow(max(0.0,0.5+0.5*sin((uv.x*6.0+uv.y*3.8)*5.2+field*2.6-t*0.72)),7.0);\n float caustic=pow(max(0.0,0.5+0.5*sin(field*5.0+grain*2.0+t*0.35)),5.0);\n float edge=min(min(uv.x,1.0-uv.x),min(uv.y,1.0-uv.y)); float rim=1.0-smoothstep(0.0,0.085,edge);\n vec2 lightA=vec2(0.18+0.11*sin(t*0.22),0.12+0.08*cos(t*0.19)); vec2 lightB=vec2(0.83+0.07*cos(t*0.17),0.86+0.06*sin(t*0.2));\n float specA=pow(max(0.0,1.0-length((uv-lightA)*vec2(1.0,1.8))*2.1),5.0); float specB=pow(max(0.0,1.0-length((uv-lightB)*vec2(1.1,1.6))*2.5),6.0);\n float hue=clamp(0.5+0.32*field+0.18*sin(uv.x*5.0+t*0.12),0.0,1.0); vec3 tint=mix(vec3(0.48,0.31,1.0),vec3(0.25,0.88,1.0),hue);\n float alpha=clamp(0.025+bands*0.11+caustic*0.085+rim*0.12+specA*0.18+specB*0.11,0.0,0.34)*u_strength;\n vec3 colour=tint*(0.38+bands*0.72+caustic*0.48)+vec3(1.0)*((rim*0.48)+(specA*0.85)+(specB*0.56)); gl_FragColor=vec4(colour,alpha);\n}";
 function compile(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){console.warn('Lolite WebGL glass shader:',gl.getShaderInfoLog(s));gl.deleteShader(s);return null}return s}
 function attach(el){if(active.has(el)||!el.isConnected||active.size>=12)return;const canvas=document.createElement('canvas');canvas.className='liquid-glass-webgl';canvas.setAttribute('aria-hidden','true');const gl=canvas.getContext('webgl',{alpha:true,antialias:false,depth:false,stencil:false,premultipliedAlpha:false,preserveDrawingBuffer:false})||canvas.getContext('experimental-webgl');if(!gl)return;const vs=compile(gl,gl.VERTEX_SHADER,vertex),fs=compile(gl,gl.FRAGMENT_SHADER,fragment);if(!vs||!fs)return;const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){console.warn('Lolite WebGL glass program:',gl.getProgramInfoLog(program));return}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,1,1]),gl.STATIC_DRAW);gl.useProgram(program);const pos=gl.getAttribLocation(program,'a_position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);const item={el,canvas,gl,program,buffer,res:gl.getUniformLocation(program,'u_resolution'),time:gl.getUniformLocation(program,'u_time'),strength:gl.getUniformLocation(program,'u_strength'),start:performance.now(),observer:null};el.insertBefore(canvas,el.firstChild);active.set(el,item);if('ResizeObserver'in window){item.observer=new ResizeObserver(()=>resize(item));item.observer.observe(el)}resize(item)}
 function resize(item){if(!item.el.isConnected)return;const r=item.el.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,1.35),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(item.canvas.width!==w||item.canvas.height!==h){item.canvas.width=w;item.canvas.height=h;item.gl.viewport(0,0,w,h)}}
 function detach(item){item.observer?.disconnect();item.canvas.remove();try{item.gl.getExtension('WEBGL_lose_context')?.loseContext()}catch{}active.delete(item.el)}
 function enabled(){return root.classList.contains('glass')&&localStorage.getItem('glass')==='true'}
 function sync(){const on=enabled();root.classList.toggle('webgl-glass',on&&active.size>0);if(!on){for(const item of [...active.values()])detach(item);root.classList.remove('webgl-glass');return}document.querySelectorAll(selectors.join(',')).forEach(attach);root.classList.toggle('webgl-glass',active.size>0);for(const item of [...active.values()])if(!item.el.isConnected)detach(item)}
 let lastScan=0,lastDraw=0,raf=0;
 function start(){if(!raf&&enabled())raf=requestAnimationFrame(frame)}
 function stop(){if(raf)cancelAnimationFrame(raf);raf=0;sync()}
 function frame(now){raf=0;if(!enabled()){sync();return}if(now-lastScan>500){sync();lastScan=now}if(now-lastDraw<32){start();return}lastDraw=now;const paused=reduce();for(const item of active.values()){const gl=item.gl;resize(item);gl.useProgram(item.program);gl.bindBuffer(gl.ARRAY_BUFFER,item.buffer);const pos=gl.getAttribLocation(item.program,'a_position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);gl.uniform2f(item.res,item.canvas.width,item.canvas.height);gl.uniform1f(item.time,paused?0:(now-item.start)*0.001);gl.uniform1f(item.strength,paused?0.8:1.0);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLE_STRIP,0,4)}start()}
 const api={setEnabled(on){localStorage.setItem('glass',on?'true':'false');root.classList.toggle('glass',!!on);if(on){sync();start()}else stop()},refresh(){sync();start()}};
 window.LoliteLiquidGlass=api;
 const mo=new MutationObserver(()=>{if(enabled()){sync();start()}else{sync();if(raf){cancelAnimationFrame(raf);raf=0}}});mo.observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{sync();start()},{once:true});else{sync();start()}
 window.addEventListener('resize',()=>active.forEach(resize));
})();