/* Lolite OS 1.1 polish layer: glass, icons, pinning, Files revamp and game fixes. */
(()=>{
 const apps=[['home','Home','⌂'],['games','Default Games','🎮'],['game-store','Game Store','🛍'],['files','Files','📁'],['browser','Lolite Browser','🌐'],['settings','Settings','⚙']];
 const gameMap={Minefield:'minefield', 'Tic-tac-toe':'tic-tac-toe','Memory Puzzle':'memory-puzzle',Simon:'simon',Nibbles:'nibbles',Snake:'snake',Breakout:'breakout','2048':'2048'};
 const iconFor=id=>(apps.find(a=>a[0]===id)||['','','▦'])[2];
 const pins=()=>JSON.parse(localStorage.lolitePins||'["files","games","browser"]');
 const savePins=a=>localStorage.lolitePins=JSON.stringify([...new Set(a)]);
 const context=(el,id,title)=>{el.oncontextmenu=e=>{e.preventDefault();showMenu(e.clientX,e.clientY,id,title)}};
 function showMenu(x,y,id,title){document.querySelector('.lolite-context')?.remove();const p=pins(),pinned=p.includes(id);const m=document.createElement('div');m.className='lolite-context';m.style.left=Math.min(x,innerWidth-220)+'px';m.style.top=Math.min(y,innerHeight-160)+'px';m.innerHTML=`<b>${iconFor(id)} ${title}</b><button onclick="openApp('${id}','${title}');closeContext()">Open</button><button onclick="LolitePins.toggle('${id}');closeContext()">${pinned?'Unpin from taskbar':'Pin to taskbar'}</button><button onclick="closeContext()">Close menu</button>`;document.body.appendChild(m)}
 window.closeContext=()=>document.querySelector('.lolite-context')?.remove();document.addEventListener('pointerdown',e=>{if(!e.target.closest('.lolite-context'))closeContext()});
 window.LolitePins={toggle(id){let p=pins();p=p.includes(id)?p.filter(x=>x!==id):[...p,id];savePins(p);renderTaskbarPins();toast(p.includes(id)?'Pinned to taskbar':'Unpinned from taskbar')}};
 function renderTaskbarPins(){const box=document.querySelector('#tasks');if(!box)return;box.querySelectorAll('.pinned-task').forEach(x=>x.remove());pins().slice().reverse().forEach(id=>{const a=apps.find(x=>x[0]===id);if(!a)return;const b=document.createElement('button');b.className='taskwin pinned-task';b.title='Right-click for options';b.innerHTML=`<span class="task-icon">${a[2]}</span><span>${a[1]}</span>`;b.onclick=()=>openApp(a[0],a[1]);context(b,a[0],a[1]);box.prepend(b)})}
 const oldRender=window.renderIcons;window.renderIcons=()=>{const box=document.querySelector('#icons');if(!box)return;box.innerHTML=apps.map(a=>`<button class="desktop-icon app-icon" ondblclick="openApp('${a[0]}','${a[1]}')"><b class="app-glyph glyph-${a[0]}">${a[2]}</b><span>${a[1]}</span></button>`).join('');apps.forEach(a=>{const b=box.querySelector(`[ondblclick*="'${a[0]}'"]`);if(b)context(b,a[0],a[1])});oldRender?.();box.innerHTML=apps.map(a=>`<button class="desktop-icon app-icon" ondblclick="openApp('${a[0]}','${a[1]}')"><b class="app-glyph glyph-${a[0]}">${a[2]}</b><span>${a[1]}</span></button>`).join('');apps.forEach(a=>{const b=box.querySelector(`[ondblclick*="'${a[0]}'"]`);if(b)context(b,a[0],a[1])})};
 const oldOpen=window.openApp;window.openApp=function(id,title,w,h){oldOpen(id,title,w,h);setTimeout(()=>{const task=document.querySelector('#task-'+id);if(task)context(task,id,title)},0)};
 const oldLoad=window.loadPrefs;window.loadPrefs=()=>{oldLoad?.();document.documentElement.classList.add('v11');renderTaskbarPins()};
 function filesPage(){setTimeout(()=>renderFiles('all'),0);return `<div class="files-v11"><div class="files-top"><div><h2>📁 Files</h2><span class="muted">Your local Lolite workspace</span></div><div class="files-actions"><button class="primary" onclick="FileOS.chooseUpload()">＋ New files</button><button class="soft" onclick="FileOS.newFolder()">＋ Folder</button><button class="soft" onclick="FileOS.chooseZip()">📦 ZIP</button><button class="soft" onclick="FileOS.makeZip()">⇩ Export</button></div></div><div class="files-layout"><aside class="files-sidebar"><button onclick="renderFiles('all')">⌂ Home</button><button onclick="renderFiles('folder')">📁 Folders</button><button onclick="renderFiles('zip')">📦 Archives</button><button onclick="renderFiles('game')">🎮 Games</button></aside><section class="files-main"><div class="files-search"><input id="fileSearch" placeholder="Search files…" oninput="renderFiles('all')"><span id=fileCount></span></div><div id=fileList class="file-grid"></div></section></div><input id="fileUpload" type="file" multiple hidden onchange="FileOS.handleUpload(this.files)"><input id="zipUpload" type="file" accept=".zip,application/zip" hidden onchange="FileOS.handleZip(this.files[0])"></div>`}
 async function renderFiles(filter){const box=document.querySelector('#fileList');if(!box||!window.FileOS)return;let rows=await FileOS.all();const q=(document.querySelector('#fileSearch')?.value||'').toLowerCase();rows=rows.filter(r=>{const p=r.path.toLowerCase();return(!q||p.includes(q))&&(filter==='all'||filter==='folder'&&p.endsWith('/')||filter==='zip'&&p.endsWith('.zip')||filter==='game'&&p.endsWith('index.html'))});document.querySelector('#fileCount').textContent=rows.length+' item'+(rows.length===1?'':'s');if(!rows.length){box.innerHTML='<div class="files-empty"><div>📂</div><b>No matching files</b><span class="muted">Upload something or create a folder to get started.</span></div>';return}box.innerHTML=rows.sort((a,b)=>a.path.localeCompare(b.path)).map(r=>{const enc=encodeURIComponent(r.path),folder=r.path.endsWith('/'),size=r.data instanceof Blob?Math.max(1,Math.round(r.data.size/1024))+' KB':'Saved';return `<article class="file-card" oncontextmenu="event.preventDefault();FileOS.deleteFile('${enc}')"><div class="file-big">${folder?'📁':r.path.endsWith('.zip')?'📦':r.path.endsWith('.html')?'🌐':'📄'}</div><b title="${r.path}">${r.path.split('/').filter(Boolean).pop()||r.path}</b><small>${size}</small><button class="soft" onclick="FileOS.deleteFile('${enc}')">Delete</button></article>`}).join('')}
 window.renderFiles=renderFiles;
 const oldPage=window.page;window.page=function(id){if(id==='files')return filesPage();if(id==='games')return gamePage();if(id==='settings')return settingsPage();return oldPage(id)};
 function gamePage(){const playable=Object.keys(gameMap);return `<div class="game-hero"><div><span class=muted>DEFAULT GAMES</span><h1>🎮 Game Library</h1><p class=muted>Playable built-in games only. No more fake “Play” buttons for missing modules.</p></div><button class=soft onclick="openApp('world','World Sandbox',760,580)">🌎 World Sandbox</button></div><div class=cards>${playable.map(g=>`<div class=card><div class=game-icon>${iconForGame(g)}</div><h3>${g}</h3><p class=muted>Ready to play</p><button class=primary onclick="launchGame('${g.replaceAll("'","\\'")}')">Play</button></div>`).join('')}</div>`}
 function iconForGame(g){return ({Minefield:'💣','Tic-tac-toe':'⭕', 'Memory Puzzle':'🧠',Simon:'🔴',Nibbles:'🐍',Snake:'🐍',Breakout:'🧱','2048':'🔢'})[g]||'🎮'}
 window.launchGame=function(g){const path=gameMap[g];if(!path){toast('Game module unavailable');return}const id='game-'+path;openApp(id,g,700,600);setTimeout(()=>{const c=state.windows[id]?.el.querySelector('.content');if(c)c.innerHTML=`<iframe title="${g}" src="games/${path}/index.html" style="width:100%;height:100%;min-height:500px;border:0;border-radius:14px;background:#090613"></iframe>`},30)};
 function settingsPage(){return `<h2>⚙ Settings</h2><p class=muted>Polished controls for appearance, performance and desktop behavior.</p><div class=settings-tabs><button class=soft onclick="v11Settings('appearance')">🎨 Appearance</button><button class=soft onclick="v11Settings('taskbar')">📌 Taskbar</button><button class=soft onclick="v11Settings('performance')">⚡ Performance</button><button class=soft onclick="v11Settings('about')">ⓘ About</button></div><div id=v11-settings>${appearance()}</div>`}
 function appearance(){return `<div class=card><h3>Liquid Glass</h3><label><input type=checkbox ${localStorage.glass==='true'?'checked':''} onchange="setGlassV11(this.checked)"> Experimental Liquid Glass</label><p class=muted>Uses layered translucency, refraction-like highlights, blur and depth. OFF by default.</p></div><div class=card><h3>UI density</h3><button class=soft onclick="localStorage.compact=false;location.reload()">Comfortable</button> <button class=soft onclick="localStorage.compact=true;location.reload()">Compact</button></div><div class=card><h3>Accent</h3><div class=accent-grid>${[['purple','#8b5cf6'],['blue','#3b82f6'],['cyan','#06b6d4'],['pink','#ec4899'],['green','#22c55e'],['orange','#f97316']].map(x=>`<button class=accent-dot style="--dot:${x[1]}" title="${x[0]}" onclick="localStorage.accent='${x[0]}';location.reload()"></button>`).join('')}</div></div>`}
 function taskbar(){return `<div class=card><h3>📌 Pinned apps</h3><p class=muted>Right-click an application to pin or unpin it.</p><div class=pinned-list>${pins().map(id=>{const a=apps.find(x=>x[0]===id);return a?`<button class=soft onclick="LolitePins.toggle('${id}')">${a[2]} ${a[1]} · Unpin</button>`:''}).join('')||'<span class=muted>No pinned apps</span>'}</div></div><div class=card><h3>Taskbar position</h3><select class=settings-select onchange="localStorage.taskbar=this.value;location.reload()"><option value=bottom>Bottom</option><option value=top ${localStorage.taskbar==='top'?'selected':''}>Top</option></select></div>`}
 function performance(){return `<div class=card><h3>Motion</h3><label><input type=checkbox ${localStorage.reduce==='true'?'checked':''} onchange="localStorage.reduce=this.checked;location.reload()"> Reduce Motion</label></div><div class=card><h3>Effects</h3><label><input type=checkbox ${localStorage.animations!=='false'?'checked':''} onchange="localStorage.animations=this.checked;location.reload()"> Smooth animations</label></div>`}
 function about(){return `<div class=card><h3>Lolite OS 1.1</h3><p>Copyright © 2026 Darby9 / Lolite OS. Lolite OS original UI, code and branding are protected by applicable copyright law unless a file states otherwise.</p><p class=muted>Third-party games, libraries and referenced trademarks remain the property of their respective owners. Lolite does not claim ownership of third-party names or assets.</p><p class=muted>Open-source components are used only according to their respective licenses.</p></div>`}
 window.v11Settings=s=>{const b=document.querySelector('#v11-settings');if(b)b.innerHTML=s==='appearance'?appearance():s==='taskbar'?taskbar():s==='performance'?performance():about()};window.setGlassV11=v=>{localStorage.glass=v;document.documentElement.classList.toggle('glass',v);toast(v?'Liquid Glass enabled':'Liquid Glass disabled')};
 setTimeout(()=>{renderTaskbarPins();window.renderIcons();},1600);
})();
