/* Lolite OS 1.2 game/performance layer. Loaded last so game controls stay reliable. */
(()=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const map={Minefield:'minefield','Tic-tac-toe':'tic-tac-toe','Memory Puzzle':'memory-puzzle',Simon:'simon',Nibbles:'nibbles',Snake:'snake',Breakout:'breakout','2048':'2048','Sliding Puzzle':'sliding-puzzle',Maze:'maze',Tetris:'tetris','Connect Four':'connect-four'};window.__loliteGameMap=map;
 const oldPage=window.page,htmlGames=[];let discoveryBusy=false,lastDiscovery=0;
 const title=file=>{const k=file.replace(/\.(html|htm)$/i,'');const known={clgrannyy:'Granny Original',clgta3:'GTA III',clpaperio:'Paper.io 2',clslopeplus:'Slope Plus'};return known[k]||k.replace(/^cl/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())};
 async function discover(force=false){if(discoveryBusy)return htmlGames;if(!force&&Date.now()-lastDiscovery<30000&&htmlGames.length)return htmlGames;discoveryBusy=true;try{const r=await fetch('https://api.github.com/repos/darby9123-arch/Lolite-OS/contents/html%20games',{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw Error();const items=await r.json(),seen=new Set();htmlGames.length=0;for(const x of items){if(x.type!=='file'||!/\.(html|htm)$/i.test(x.name))continue;const k=x.name.toLowerCase();if(seen.has(k))continue;seen.add(k);htmlGames.push({file:x.name,name:title(x.name)})}htmlGames.sort((a,b)=>a.name.localeCompare(b.name));lastDiscovery=Date.now()}catch{}finally{discoveryBusy=false}return htmlGames}
 function launch(name,file){const id='html-game-'+file.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');if(state.windows[id]){restoreWin(id);return}openApp(id,name,900,650);setTimeout(()=>{const c=state.windows[id]?.el.querySelector('.content');if(!c)return;c.innerHTML=`<iframe title="${esc(name)}" src="html%20games/${encodeURIComponent(file)}" loading="eager" allow="fullscreen; gamepad" tabindex="0" style="width:100%;height:100%;min-height:560px;border:0;border-radius:12px;background:#000"></iframe>`;const f=c.querySelector('iframe');f.addEventListener('load',()=>f.focus(),{once:true});c.addEventListener('pointerdown',()=>f.focus())},30)}
 window.launchHTMLGame=launch;
 window.launchGame=function(name){const path=map[name];if(!path){toast(name+' is not available yet');return}const id='game-'+path;if(state.windows[id]){restoreWin(id);return}openApp(id,name,700,600);setTimeout(()=>{const c=state.windows[id]?.el.querySelector('.content');if(!c)return;c.innerHTML=`<iframe title="${esc(name)}" src="games/${encodeURIComponent(path)}/index.html" loading="eager" allow="fullscreen; gamepad" tabindex="0" style="width:100%;height:100%;min-height:500px;border:0;border-radius:14px;background:#090613"></iframe>`;const f=c.querySelector('iframe');f.addEventListener('load',()=>f.focus(),{once:true});c.addEventListener('pointerdown',()=>f.focus())},30)};
 function gamePage(){return `<div class="game-hero"><div><span class="muted">DEFAULT GAMES</span><h1>🎮 Game Library</h1><p class="muted">Fast, playable built-in games. No fake Play buttons.</p></div><button class="soft" id="worldGameBtn">🌎 World Sandbox</button></div><div class="game-search"><input id="defaultGameSearch" type="search" placeholder="Search default games…" autocomplete="off"><span id="defaultGameCount" class="muted"></span></div><div class="cards" id="defaultGameGrid"></div>`}
 function renderDefault(){const grid=document.getElementById('defaultGameGrid');if(!grid)return;const q=(document.getElementById('defaultGameSearch')?.value||'').trim().toLowerCase();const rows=Object.keys(map).filter(g=>g.toLowerCase().includes(q));grid.innerHTML=rows.map(g=>`<div class="card"><div class="game-icon">🎮</div><h3>${esc(g)}</h3><p class="muted">Ready to play</p><button class="primary" data-default-game="${encodeURIComponent(g)}">Play</button></div>`).join('');const count=document.getElementById('defaultGameCount');if(count)count.textContent=`${rows.length} games`}
 function wireDefault(){document.getElementById('defaultGameSearch')?.addEventListener('input',renderDefault);document.getElementById('defaultGameGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-default-game]');if(b)window.launchGame(decodeURIComponent(b.dataset.defaultGame))});document.getElementById('worldGameBtn')?.addEventListener('click',()=>openApp('world','World Sandbox',760,580));renderDefault()}
 function storePage(){setTimeout(async()=>{await discover();renderStore();wireStore()},0);return `<h2>🛍️ Game Store</h2><p class="muted">HTML and HTM games. Files are discovered once, filtered locally and only loaded after Play.</p><div class="game-search"><input id="htmlGameSearch" type="search" placeholder="Search HTML games…" autocomplete="off"><span id="htmlGameCount" class="muted"></span><button class="soft" id="refreshHtmlGames">↻ Refresh</button></div><div class="html-game-grid" id="htmlGameGrid"></div>`}
 function renderStore(){const grid=document.getElementById('htmlGameGrid');if(!grid)return;const q=(document.getElementById('htmlGameSearch')?.value||'').trim().toLowerCase();const rows=htmlGames.filter(g=>g.name.toLowerCase().includes(q)||g.file.toLowerCase().includes(q));grid.innerHTML=rows.length?rows.map(g=>`<article class="card html-game-card"><h3>🎮 ${esc(g.name)}</h3><span class="html-game-badge">HTML / HTM</span><p class="muted">Loads only when opened.</p><button class="primary" data-html-file="${encodeURIComponent(g.file)}" data-html-name="${encodeURIComponent(g.name)}">Play</button></article>`).join(''):'<div class="empty"><div>🔎</div><b>No matching games</b><span class="muted">Try another search.</span></div>';const count=document.getElementById('htmlGameCount');if(count)count.textContent=`${rows.length} of ${htmlGames.length} games`}
 function wireStore(){document.getElementById('htmlGameSearch')?.addEventListener('input',renderStore);document.getElementById('refreshHtmlGames')?.addEventListener('click',async()=>{await discover(true);renderStore()});document.getElementById('htmlGameGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-html-file]');if(b)launch(decodeURIComponent(b.dataset.htmlName),decodeURIComponent(b.dataset.htmlFile))})}
 window.refreshGameStore=async()=>{await discover(true);renderStore()};
 window.page=function(id){if(id==='games'){const r=gamePage();setTimeout(wireDefault,0);return r}if(id==='game-store')return storePage();return oldPage(id)};
 document.addEventListener('click',e=>{if(e.target.closest('#searchBtn'))requestAnimationFrame(()=>document.querySelector('#searchPanel input')?.focus())});
 setTimeout(discover,400);
})();
