/* Lolite OS 1.3 app suite, bug fixes and non-emoji application icon system. */
(()=>{
 const appIcons={home:'home',games:'games','game-store':'store',files:'files',browser:'browser',settings:'settings',paint:'paint',notepad:'notepad',calculator:'calculator','screen-capture':'capture',clock:'clock',widgets:'widgets',battery:'battery',autoclicker:'clicker',terminal:'terminal',ai:'ai',minecraft:'minecraft',scramjet:'browser'};
 const apps=[['home','Home'],['games','Default Games'],['game-store','Game Store'],['files','Files'],['browser','Lolite Browser'],['scramjet','Scramjet'],['paint','Paint'],['notepad','Notepad'],['calculator','Calculator'],['screen-capture','Screen Capture'],['clock','Clock'],['widgets','Widgets'],['battery','Battery'],['autoclicker','Auto Clicker'],['terminal','Terminal'],['ai','Lolite AI'],['minecraft','Minecraft']];
 const icon=(id)=>`<span class="app-symbol app-${appIcons[id]||'generic'}" aria-hidden="true"></span>`;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 window.__loliteApps=apps;window.__loliteAppIcon=icon;
 function launch(id,title,w=720,h=560){openApp(id,title,w,h)}
 const oldPage=window.page;
 function appPage(id){
  if(id==='paint')return `<div class="tool-app paint-app"><div class="tool-head"><div><h2>Paint</h2><span class="muted">Draw, paint and create.</span></div><div class="tool-actions"><label>Brush <input id="paintSize" type="range" min="1" max="40" value="6"></label><input id="paintColor" type="color" value="#8b5cf6"><button class="soft" id="paintEraser">Eraser</button><button class="soft" id="paintClear">Clear</button><button class="primary" id="paintSave">Save PNG</button></div></div><canvas id="paintCanvas"></canvas></div>`;
  if(id==='notepad')return `<div class="tool-app"><div class="tool-head"><div><h2>Notepad</h2><span class="muted">Simple local text editor.</span></div><div class="tool-actions"><button class="soft" id="noteNew">New</button><button class="primary" id="noteSave">Download .txt</button></div></div><textarea id="noteText" class="notepad" placeholder="Start typing…"></textarea></div>`;
  if(id==='calculator')return `<div class="calculator"><div id="calcDisplay" class="calc-display">0</div><div class="calc-grid">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+','C','⌫','%','±'].map(x=>`<button class="${x==='='?'primary':''}" data-calc="${x}">${x}</button>`).join('')}</div></div>`;
  if(id==='screen-capture')return `<div class="tool-app"><div class="tool-head"><div><h2>Screen Capture</h2><span class="muted">Take a screenshot or record this screen.</span></div></div><div class="capture-cards"><button class="primary" id="takeShot">Take Screenshot</button><button class="soft" id="startRecord">Start Recording</button><button class="soft" id="stopRecord" disabled>Stop Recording</button></div><div id="captureStatus" class="card muted">Ready.</div></div>`;
  if(id==='clock')return `<div class="clock-app"><div id="bigClock">--:--:--</div><div id="bigDate" class="muted"></div></div>`;
  if(id==='widgets')return `<div class="tool-app"><div class="tool-head"><div><h2>Widgets</h2><span class="muted">Useful desktop cards.</span></div></div><div class="widget-grid"><div class="card"><b>Clock</b><div id="widgetClock">--:--</div></div><div class="card"><b>Battery</b><div id="widgetBattery">Checking…</div></div><div class="card"><b>Performance</b><div>Lightweight UI mode active</div></div><div class="card"><b>Quick launch</b><button class="soft" id="widgetPaint">Open Paint</button></div></div></div>`;
  if(id==='battery')return `<div class="tool-app"><h2>Battery</h2><div class="battery-big" id="batteryBig">Checking…</div><p class="muted">Browser battery information is only available when your browser exposes the Battery Status API.</p></div>`;
  if(id==='autoclicker')return `<div class="tool-app"><h2>Auto Clicker</h2><p class="muted">A simple local timer for repeated clicks.</p><div class="card"><label>Interval <input id="clickInterval" type="number" min="50" max="10000" value="500"> ms</label><div class="tool-actions"><button class="primary" id="clickStart">Start</button><button class="soft" id="clickStop">Stop</button></div><p id="clickStatus" class="muted">Stopped</p></div></div>`;
  if(id==='terminal')return `<div class="terminal-app"><div class="terminal-head"><b>lolite terminal</b><button class="soft" id="terminalHelp">?</button></div><pre id="terminalOutput">Lolite Terminal 1.3\nType ? for commands.\n</pre><form id="terminalForm"><span>›</span><input id="terminalInput" autocomplete="off" spellcheck="false"></form></div>`;
  if(id==='ai')return `<div class="tool-app ai-coming"><div class="ai-mark">AI</div><h2>Lolite AI</h2><p>Coming soon in <b>v2</b>.</p><p class="muted">The AI app is intentionally unavailable in v1.3.</p></div>`;
  if(id==='minecraft')return `<div class="tool-app minecraft-app"><div class="game-hero"><div><h2>Minecraft</h2><p class="muted">Eaglercraft browser client.</p></div><button class="primary" id="minecraftLaunch">Launch Eaglercraft</button></div><div class="card"><p class="muted">Eaglercraft is a browser-based Minecraft implementation. Lolite does not copy third-party client source into this repository.</p></div></div>`;
  if(id==='scramjet')return `<div class="tool-app"><div class="game-hero"><div><h2>Scramjet</h2><p class="muted">Browser engine integration status.</p></div><button class="soft" id="scramjetCheck">Check runtime</button></div><div id="sj-status" class="card">Checking Scramjet runtime…</div><div class="card"><p class="muted">Lolite keeps the upstream Scramjet controller and proxy transport separate instead of copying its source into the OS. This app reports whether a compatible runtime is actually available.</p></div></div>`;
  return null;
 }
 function settingsPage(){return `<h2>⚙ Settings</h2><p class="muted">Appearance, performance, apps and release information.</p><div class="settings-tabs"><button class="soft" data-settings="appearance">Appearance</button><button class="soft" data-settings="taskbar">Taskbar</button><button class="soft" data-settings="performance">Performance</button><button class="soft" data-settings="updates">Update Log</button><button class="soft" data-settings="about">About</button></div><div id="v13-settings">${settingsSection('appearance')}</div>`}
 function settingsSection(s){if(s==='updates')return `<div class="card"><h3>Lolite OS Update Log</h3><div class="result"><b>1.3</b><br>New app suite, redesigned non-emoji icons, Minecraft/Eaglercraft launcher, Scramjet runtime panel, Paint, Notepad, Calculator, Screen Capture, Clock, Widgets, Battery, Auto Clicker, Terminal and v2 AI placeholder.</div><div class="result"><b>1.2</b><br>Game performance, searchable game libraries, reliable game controls and four more playable games.</div><div class="result"><b>1.1</b><br>UI polish, taskbar pinning, Liquid Glass and Files improvements.</div><div class="result"><b>1.0</b><br>Major Lolite OS edition with settings, browser diagnostics and game systems.</div></div>`;if(s==='appearance')return `<div class="card"><h3>Appearance</h3><p class="muted">Liquid Glass and visual density are still controlled by the existing Lolite settings.</p><button class="soft" onclick="localStorage.glass=localStorage.glass!=='true';document.documentElement.classList.toggle('glass',localStorage.glass==='true')">Toggle Liquid Glass</button></div>`;if(s==='taskbar')return `<div class="card"><h3>Taskbar</h3><p class="muted">Use right-click application menus to pin or unpin apps.</p></div>`;if(s==='performance')return `<div class="card"><h3>Performance</h3><p class="muted">Games are lazy-loaded and Game Store discovery is cached. Reduce Motion is available in the existing settings.</p></div>`;return `<div class="card"><h3>About Lolite OS</h3><p>Lolite OS 1.3</p><p class="muted">Copyright © 2026 Darby9 / Lolite OS. Third-party projects remain under their own licenses.</p></div>`}
 window.page=function(id){if(id==='settings')return settingsPage();const p=appPage(id);return p||oldPage(id)};
 function bindPaint(root){const c=root.querySelector('#paintCanvas');if(!c)return;const ctx=c.getContext('2d');let down=false,erase=false,last=null;const resize=()=>{const r=c.getBoundingClientRect();if(r.width<1||r.height<1)return;const d=devicePixelRatio||1;c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0)};resize();new ResizeObserver(resize).observe(c);const pos=e=>{const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};c.addEventListener('pointerdown',e=>{down=true;c.setPointerCapture(e.pointerId);last=pos(e)});c.addEventListener('pointermove',e=>{if(!down)return;const p=pos(e);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=+root.querySelector('#paintSize').value;ctx.strokeStyle=erase?'#000':root.querySelector('#paintColor').value;ctx.globalCompositeOperation=erase?'destination-out':'source-over';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});c.addEventListener('pointerup',()=>{down=false;ctx.globalCompositeOperation='source-over'});root.querySelector('#paintEraser').onclick=()=>{erase=!erase;root.querySelector('#paintEraser').textContent=erase?'Eraser ON':'Eraser'};root.querySelector('#paintClear').onclick=()=>ctx.clearRect(0,0,c.width,c.height);root.querySelector('#paintSave').onclick=()=>{const a=document.createElement('a');a.download='lolite-paint.png';a.href=c.toDataURL('image/png');a.click()}}
 function bindCalculator(root){let value='0',stored=null,op=null;const d=root.querySelector('#calcDisplay');const calc=x=>{if(/^[0-9.]$/.test(x)){value=value==='0'&&x!=='.'?x:value+x;return}if(x==='C'){value='0';stored=null;op=null;return}if(x==='⌫'){value=value.length>1?value.slice(0,-1):'0';return}if(x==='±'){value=String(-Number(value));return}if(x==='%'){value=String(Number(value)/100);return}if(['+','−','×','÷'].includes(x)){stored=Number(value);op=x;value='0';return}if(x==='='&&op){const b=Number(value);value=String(op==='+'?stored+b:op==='−'?stored-b:op==='×'?stored*b:b?stored/b:0);op=null}};root.addEventListener('click',e=>{const b=e.target.closest('[data-calc]');if(!b)return;calc(b.dataset.calc);d.textContent=value})}
 function bindNotepad(root){const t=root.querySelector('#noteText');root.querySelector('#noteNew').onclick=()=>{if(!t.value||confirm('Clear the note?'))t.value=''};root.querySelector('#noteSave').onclick=()=>{const a=document.createElement('a');a.download='lolite-note.txt';a.href=URL.createObjectURL(new Blob([t.value],{type:'text/plain'}));a.click()}}
 function bindTerminal(root){const input=root.querySelector('#terminalInput'),out=root.querySelector('#terminalOutput');const commands={help:'Commands: ? / help, clear, apps, date, time, echo <text>, version, about',apps:'Apps: Paint, Notepad, Calculator, Screen Capture, Clock, Widgets, Battery, Auto Clicker, Terminal, Minecraft, Scramjet, Lolite AI',version:'Lolite OS 1.3',about:'Lolite OS — Darby9',clear:'',date:new Date().toLocaleDateString(),time:new Date().toLocaleTimeString()};const run=s=>{const [cmd,...rest]=s.trim().split(/\s+/),low=(cmd||'').toLowerCase();if(low==='echo')return rest.join(' ');if(low==='clear'){out.textContent='';return ''}return commands[low]||commands[low==='?'?'help':'help']};root.querySelector('#terminalHelp').onclick=()=>{out.textContent+='\n'+commands.help+'\n';input.focus()};root.querySelector('#terminalForm').onsubmit=e=>{e.preventDefault();const s=input.value;out.textContent+=`› ${s}\n${run(s)}\n`;input.value='';out.scrollTop=out.scrollHeight};input.focus()}
 function bindCapture(root){let recorder,parts=[];root.querySelector('#takeShot').onclick=async()=>{try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true});const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,250));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);stream.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.download='lolite-screenshot.png';a.href=c.toDataURL('image/png');a.click();root.querySelector('#captureStatus').textContent='Screenshot saved.'}catch{root.querySelector('#captureStatus').textContent='Screenshot cancelled or unavailable.'}};root.querySelector('#startRecord').onclick=async()=>{try{const s=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});parts=[];recorder=new MediaRecorder(s);recorder.ondataavailable=e=>e.data.size&&parts.push(e.data);recorder.onstop=()=>{const a=document.createElement('a');a.download='lolite-recording.webm';a.href=URL.createObjectURL(new Blob(parts,{type:'video/webm'}));a.click();s.getTracks().forEach(t=>t.stop());root.querySelector('#captureStatus').textContent='Recording saved.'};recorder.start();root.querySelector('#startRecord').disabled=true;root.querySelector('#stopRecord').disabled=false;root.querySelector('#captureStatus').textContent='Recording…'}catch{root.querySelector('#captureStatus').textContent='Recording unavailable or cancelled.'}};root.querySelector('#stopRecord').onclick=()=>recorder?.stop()}
 function bindExtras(root,id){if(id==='paint')bindPaint(root);if(id==='notepad')bindNotepad(root);if(id==='calculator')bindCalculator(root);if(id==='screen-capture')bindCapture(root);if(id==='terminal')bindTerminal(root);if(id==='widgets')root.querySelector('#widgetPaint').onclick=()=>launch('paint','Paint');if(id==='scramjet'){root.querySelector('#scramjetCheck').onclick=()=>window.LoliteScramjet?.check();setTimeout(()=>window.LoliteScramjet?.check(),50)}if(id==='clock'||id==='widgets'){const tick=()=>{const d=new Date(),time=d.toLocaleTimeString();root.querySelector('#bigClock')&&(root.querySelector('#bigClock').textContent=time);root.querySelector('#bigDate')&&(root.querySelector('#bigDate').textContent=d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'}));root.querySelector('#widgetClock')&&(root.querySelector('#widgetClock').textContent=time)};tick();root._timer=setInterval(tick,1000)}if(id==='battery'||id==='widgets'){navigator.getBattery?.().then(b=>{const show=()=>{const s=Math.round(b.level*100)+'%'+(b.charging?' · Charging':'');root.querySelector('#batteryBig')&&(root.querySelector('#batteryBig').textContent=s);root.querySelector('#widgetBattery')&&(root.querySelector('#widgetBattery').textContent=s)};show();b.addEventListener('levelchange',show);b.addEventListener('chargingchange',show)}).catch(()=>{})}if(id==='autoclicker'){let timer;root.querySelector('#clickStart').onclick=()=>{clearInterval(timer);const ms=Math.max(50,+root.querySelector('#clickInterval').value||500);timer=setInterval(()=>{const el=document.elementFromPoint(innerWidth/2,innerHeight/2);if(el&&el!==document.body)el.click()},ms);root.querySelector('#clickStatus').textContent='Running'};root.querySelector('#clickStop').onclick=()=>{clearInterval(timer);root.querySelector('#clickStatus').textContent='Stopped'}}if(id==='minecraft')root.querySelector('#minecraftLaunch').onclick=()=>window.open('https://g.deev.is/eaglercraft/','_blank','noopener,noreferrer')}
 const oldOpen=window.openApp;window.openApp=function(id,title,w,h){if(appPage(id)||id==='settings'){oldOpen(id,title,w||720,h||560);setTimeout(()=>{const c=state.windows[id]?.el.querySelector('.content');if(c){c.innerHTML=window.page(id);bindExtras(c,id);c.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>{c.querySelector('#v13-settings').innerHTML=settingsSection(b.dataset.settings)})}},30);return}oldOpen(id,title,w,h)};
 const oldRender=window.renderIcons;window.renderIcons=()=>{oldRender?.();const box=document.querySelector('#icons');if(!box)return;box.innerHTML=apps.map(a=>`<button class="desktop-icon app-icon" data-app="${a[0]}">${icon(a[0])}<span>${a[1]}</span></button>`).join('');box.querySelectorAll('[data-app]').forEach(b=>b.ondblclick=()=>launch(b.dataset.app,apps.find(a=>a[0]===b.dataset.app)?.[1]||b.dataset.app));};
 const renderPins=()=>{const box=document.querySelector('#tasks');if(!box)return;box.querySelectorAll('.pinned-task').forEach(x=>x.remove());let pins=[];try{pins=JSON.parse(localStorage.lolitePins||'[]')}catch{};pins.forEach(id=>{const a=apps.find(x=>x[0]===id);if(!a)return;const b=document.createElement('button');b.className='taskwin pinned-task';b.innerHTML=icon(id)+`<span>${a[1]}</span>`;b.onclick=()=>launch(id,a[1]);box.prepend(b)})};
 const oldToggle=window.LolitePins?.toggle;if(window.LolitePins)window.LolitePins.toggle=id=>{let p=[];try{p=JSON.parse(localStorage.lolitePins||'[]')}catch{};p=p.includes(id)?p.filter(x=>x!==id):[...p,id];localStorage.lolitePins=JSON.stringify([...new Set(p)]);renderPins();toast(p.includes(id)?'Pinned to taskbar':'Unpinned from taskbar')};
 setTimeout(()=>{window.renderIcons?.();renderPins()},900);
})();
