/* Lolite OS 1.8: five-column desktop icon grid + custom wallpaper settings. */
(()=>{
 const css=document.createElement('style');css.textContent=`
 #icons{grid-template-columns:repeat(5,104px)!important;grid-auto-flow:row!important;grid-auto-rows:max-content;align-items:start;justify-items:center;max-height:calc(100vh - 100px);overflow:hidden}
 @media(max-width:650px){#icons{grid-template-columns:repeat(5,82px)!important;gap:8px}.desktop-icon{width:82px}}
 .custom-wallpaper-card{display:grid;gap:12px}.wallpaper-preview{height:180px;border-radius:14px;border:1px solid var(--line);background:#0b0913 center/cover no-repeat;display:grid;place-items:center;color:var(--muted);overflow:hidden}.wallpaper-preview.has-image{color:transparent}.wallpaper-actions{display:flex;gap:8px;flex-wrap:wrap}.wallpaper-actions input{max-width:100%}
 `;document.head.appendChild(css);
 const key='lolite-custom-wallpaper';
 const apply=src=>{const w=document.getElementById('wallpaper');if(!w)return;if(src){w.style.backgroundImage=`url("${String(src).replace(/"/g,'%22')}")`;w.classList.add('custom-wallpaper-active')}else{w.style.backgroundImage='';w.classList.remove('custom-wallpaper-active')}};
 const load=()=>{try{const src=localStorage.getItem(key);if(src)apply(src)}catch(e){console.warn('Lolite wallpaper load failed',e)}};
 const page=()=>`<div class="tool-app custom-wallpaper-card"><div class="game-hero"><div><div class="muted">DESKTOP PERSONALIZATION</div><h2>Custom Wallpaper</h2><p class="muted">Choose an image from your device and use it as your Lolite desktop wallpaper. It is saved locally in this browser.</p></div><div class="app-store-icon">W</div></div><div id="wallpaperPreview" class="wallpaper-preview">No custom wallpaper selected</div><div class="wallpaper-actions"><input id="wallpaperFile" type="file" accept="image/*"><button id="wallpaperRemove" class="soft" type="button">Remove wallpaper</button></div><p id="wallpaperStatus" class="muted"></p></div>`;
 const wire=()=>{const input=document.getElementById('wallpaperFile'),preview=document.getElementById('wallpaperPreview'),status=document.getElementById('wallpaperStatus');try{const src=localStorage.getItem(key);if(src){preview.style.backgroundImage=`url("${String(src).replace(/"/g,'%22')}")`;preview.classList.add('has-image');preview.textContent='Wallpaper preview'}}catch(e){} input?.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){status.textContent='Please choose an image file.';return}const reader=new FileReader();reader.onload=()=>{try{localStorage.setItem(key,reader.result);apply(reader.result);preview.style.backgroundImage=`url("${String(reader.result).replace(/"/g,'%22')}")`;preview.classList.add('has-image');preview.textContent='Wallpaper preview';status.textContent='Custom wallpaper applied.'}catch(e){status.textContent='That image could not be saved. Try a smaller image.'}};reader.readAsDataURL(file)});document.getElementById('wallpaperRemove')?.addEventListener('click',()=>{localStorage.removeItem(key);apply('');preview.style.backgroundImage='';preview.classList.remove('has-image');preview.textContent='No custom wallpaper selected';status.textContent='Custom wallpaper removed.'})};
 const oldPage=window.page;window.page=function(id){if(id==='wallpaper-custom'){setTimeout(wire,0);return page()}return oldPage(id)};
 const oldRender=window.renderIcons;window.renderIcons=function(){oldRender?.();const box=document.querySelector('#icons');if(!box)return;box.style.gridTemplateColumns='repeat(5,104px)';if(!box.querySelector('[data-wallpaper-icon]')){const b=document.createElement('button');b.className='desktop-icon';b.dataset.wallpaperIcon='1';b.innerHTML='<span class="app-store-icon">W</span><span>Wallpaper</span>';b.ondblclick=()=>openApp('wallpaper-custom','Custom Wallpaper',760,560);box.appendChild(b)}};
 load();setTimeout(()=>window.renderIcons?.(),900);
})();
