/* Lolite OS 2.5 — Game Library 2.0 */
(()=>{
 const V='2.5', KEY='lolite-game-library-2.5';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
 const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const fav=()=>read(KEY+':favorites'), recent=()=>read(KEY+':recent');
 const setFav=v=>write(KEY+':favorites',v), setRecent=v=>write(KEY+':recent',v);
 const meta={
  'lolite-2048.html':['2048','Puzzle','Arrow keys / swipe to move tiles.'],
  'lolite-pong.html':['Pong','Arcade','Move with the mouse or touch controls.'],
  'lolite-sokoban.html':['Sokoban','Puzzle','Arrow keys / WASD to push boxes.'],
  'slope.html':['Slope','Arcade','Use A/D or the arrow keys to steer.'],
  'slope-2-player.html':['Slope 2 Player','Arcade','Use the on-screen or keyboard controls.'],
  'wheely.html':['Wheely','Puzzle','Click or tap objects to solve each level.'],
  'zombie-rush.html':['Zombie Rush','Action','Use the game controls shown on screen.'],
  'clpaperio.html':['Paper.io 2','Arcade','Keyboard or touch controls depending on the game.'],
  'clslopeplus.html':['Slope Plus','Arcade','Use the arrow keys or A/D to steer.'],
  'wrestle-bros.html':['Wrestle Bros','Sports','Use the controls shown by the game.'],
  'clgrannyy.html':['Granny Original','Horror','Use the controls shown by the game.'],
  'clgta3.html':['GTA III','Action','Use the controls shown by the game.']
 };
 const info=file=>{const x=meta[file];if(x)return {name:x[0],category:x[1],description:x[2]};const n=file.replace(/\.(html|htm)$/i,'').replace(/^cl/i,'').replace(/[-_]+/g,' ');return {name:n.replace(/\b\w/g,m=>m.toUpperCase()),category:'HTML Game',description:'Standalone HTML game. Controls are shown by the game.'}};
 const base=window.page;
 const state=()=>({games:[],loading:false});
 let cache=state();
 async function discover(force=false){if(cache.games.length&&!force)return cache.games;if(cache.loading)return cache.games;cache.loading=true;try{const r=await fetch('https://api.github.com/repos/darby9123-arch/Lolite-OS/contents/html%20games',{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw Error('discovery failed');const items=await r.json(),seen=new Set();cache.games=items.filter(x=>x.type==='file'&&/\.(html|htm)$/i.test(x.name)).map(x=>{const i=info(x.name);return {file:x.name,name:i.name,category:i.category,description:i.description,size:x.size||0}}).filter(g=>{const k=g.file.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.name.localeCompare(b.name));return cache.games}catch{return cache.games}finally{cache.loading=false}}
 const isFav=f=>fav().includes(f);
 function toggleFav(file){const a=fav(),i=a.indexOf(file);i>=0?a.splice(i,1):a.unshift(file);setFav(a.slice(0,100));render();}
 function markRecent(file){const a=recent().filter(x=>x!==file);a.unshift(file);setRecent(a.slice(0,30))}
 function install(file){const a=read(KEY+':installed');if(!a.includes(file)){a.push(file);write(KEY+':installed',a)}return true}
 function openFullscreen(frame){try{frame.requestFullscreen?.()}catch{}}
 function launch(game){install(game.file);markRecent(game.file);render();const id='v25-game-'+game.file.replace(/[^a-z0-9]+/gi,'-');if(window.state?.windows?.[id]){window.restoreWin?.(id);return}window.openApp?.(id,game.name,920,680);setTimeout(()=>{const w=window.state?.windows?.[id],c=w?.el?.querySelector('.content');if(!c)return;c.innerHTML=`<div class="v25-player"><div class="v25-playerbar"><strong>${esc(game.name)}</strong><span class="v25-player-actions"><button class="soft v25-fullscreen">Fullscreen</button><button class="soft v25-close">Close</button></span></div><iframe title="${esc(game.name)}" src="html%20games/${encodeURIComponent(game.file)}" loading="eager" allow="fullscreen; gamepad" tabindex="0"></iframe></div>`;const f=c.querySelector('iframe');c.querySelector('.v25-fullscreen')?.addEventListener('click',()=>openFullscreen(f));c.querySelector('.v25-close')?.addEventListener('click',()=>window.closeWindow?.(id));f?.addEventListener('load',()=>f.focus(),{once:true});},50)}
 function cards(games){return games.map(g=>`<article class="v25-game-card"><button class="v25-thumb" data-play="${encodeURIComponent(g.file)}" aria-label="Play ${esc(g.name)}"><span>🎮</span></button><div class="v25-game-body"><div class="v25-title-row"><h3>${esc(g.name)}</h3><button class="v25-star ${isFav(g.file)?'on':''}" data-fav="${encodeURIComponent(g.file)}" aria-label="${isFav(g.file)?'Remove from favorites':'Add to favorites'}">${isFav(g.file)?'★':'☆'}</button></div><div class="v25-tags"><span>${esc(g.category)}</span><span>HTML</span></div><p>${esc(g.description)}</p><div class="v25-card-actions"><button class="primary" data-play="${encodeURIComponent(g.file)}">Play</button><button class="soft" data-install="${encodeURIComponent(g.file)}">${read(KEY+':installed').includes(g.file)?'Installed':'Install'}</button></div></div></article>`).join('')}
 function render(){const grid=document.getElementById('v25-grid');if(!grid)return;const q=(document.getElementById('v25-search')?.value||'').trim().toLowerCase(),cat=document.getElementById('v25-category')?.value||'All';let rows=cache.games.filter(g=>(!q||g.name.toLowerCase().includes(q)||g.file.toLowerCase().includes(q)||g.category.toLowerCase().includes(q))&&(cat==='All'||g.category===cat));const mode=document.querySelector('.v25-filter.active')?.dataset.mode||'all';if(mode==='favorites')rows=rows.filter(g=>isFav(g.file));if(mode==='recent'){const r=recent();rows=rows.filter(g=>r.includes(g.file)).sort((a,b)=>r.indexOf(a.file)-r.indexOf(b.file))}grid.innerHTML=rows.length?cards(rows):'<div class="v25-empty"><b>No games found</b><span>Try another search or filter.</span></div>';const count=document.getElementById('v25-count');if(count)count.textContent=`${rows.length} of ${cache.games.length} games`}
 function wire(){document.getElementById('v25-search')?.addEventListener('input',render);document.getElementById('v25-category')?.addEventListener('change',render);document.getElementById('v25-refresh')?.addEventListener('click',async()=>{const b=document.getElementById('v25-refresh');if(b)b.textContent='Refreshing…';await discover(true);render();if(b)b.textContent='↻ Refresh'});document.querySelectorAll('.v25-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.v25-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));document.getElementById('v25-grid')?.addEventListener('click',e=>{const play=e.target.closest('[data-play]');const fv=e.target.closest('[data-fav]');const ins=e.target.closest('[data-install]');if(fv)toggleFav(decodeURIComponent(fv.dataset.fav));else if(ins){install(decodeURIComponent(ins.dataset.install));render()}else if(play){const file=decodeURIComponent(play.dataset.play),g=cache.games.find(x=>x.file===file);if(g)launch(g)}});render()}
 window.LoliteV25={version:V,refresh:()=>discover(true).then(render),favorites:()=>fav(),recent:()=>recent()};
 window.page=function(id){if(id!=='game-store')return base(id);setTimeout(async()=>{await discover();const cats=['All',...new Set(cache.games.map(g=>g.category))];const cat=document.getElementById('v25-category');if(cat)cat.innerHTML=cats.map(x=>`<option>${esc(x)}</option>`).join('');wire()},0);return `<div class="v25-store-head"><div><div class="v25-kicker">LOLITE GAMES</div><h2>Game Library 2.0</h2><p class="muted">Search, install, favorite and launch your HTML games.</p></div><button id="v25-refresh" class="soft">↻ Refresh</button></div><div class="v25-toolbar"><input id="v25-search" type="search" placeholder="Search games…" autocomplete="off"><select id="v25-category" aria-label="Game category"><option>All</option></select></div><div class="v25-filters"><button class="soft v25-filter active" data-mode="all">All</button><button class="soft v25-filter" data-mode="favorites">★ Favorites</button><button class="soft v25-filter" data-mode="recent">Recently played</button><span id="v25-count" class="muted"></span></div><div id="v25-grid" class="v25-grid"></div>`};
 const style=document.createElement('style');style.id='v25-style';style.textContent=`.v25-store-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.v25-kicker{font-size:11px;letter-spacing:.14em;opacity:.55}.v25-toolbar{display:flex;gap:10px;margin-bottom:10px}.v25-toolbar input{flex:1;min-width:0}.v25-filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:14px}.v25-filter.active{border-color:#7c5cff;background:#7c5cff18}.v25-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}.v25-game-card{overflow:hidden;border:1px solid #ffffff12;border-radius:16px;background:#ffffff06;display:flex;flex-direction:column}.v25-thumb{height:130px;border:0;background:linear-gradient(135deg,#16102b,#10213b);color:#fff;display:grid;place-items:center;font-size:42px;cursor:pointer}.v25-thumb:hover{filter:brightness(1.15)}.v25-game-body{padding:13px}.v25-title-row{display:flex;align-items:center;gap:8px}.v25-title-row h3{margin:0;flex:1}.v25-star{border:0;background:none;font-size:23px;color:inherit;cursor:pointer}.v25-star.on{color:#ffd76a}.v25-tags{display:flex;gap:6px;margin:7px 0}.v25-tags span{font-size:10px;padding:3px 7px;border-radius:999px;border:1px solid #ffffff12;opacity:.72}.v25-game-body p{min-height:38px;margin:8px 0;color:#aaa}.v25-card-actions{display:flex;gap:8px}.v25-card-actions button{flex:1}.v25-empty{padding:35px;text-align:center;display:grid;gap:7px;opacity:.7}.v25-player{height:100%;display:flex;flex-direction:column;gap:8px}.v25-playerbar{display:flex;align-items:center;justify-content:space-between;gap:10px}.v25-player-actions{display:flex;gap:6px}.v25-player iframe{flex:1;width:100%;min-height:500px;border:0;border-radius:12px;background:#000}@media(max-width:650px){.v25-store-head{flex-direction:column}.v25-toolbar{flex-direction:column}.v25-grid{grid-template-columns:1fr}.v25-player iframe{min-height:calc(100vh - 130px)}}`;document.head.appendChild(style);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(discover,400));else setTimeout(discover,400);
})();
