/* Lolite OS 2.6 — Utilities Pack */
(()=>{
 const V='2.6';
 const apps={
  calculator:{name:'Calculator',icon:'🧮',build:()=>`<div class="v26-calc"><input id="v26-calc-display" readonly value="0"><div class="v26-calc-grid">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+','C','⌫','%','(' ,')'].map(x=>`<button data-calc="${x}">${x}</button>`).join('')}</div></div>`},
  notepad:{name:'Notepad',icon:'📝',build:()=>`<textarea class="v26-notes" placeholder="Start typing…"></textarea>`},
  paint:{name:'Paint',icon:'🎨',build:()=>`<div class="v26-paint"><canvas id="v26-canvas" width="900" height="560"></canvas><div class="v26-paintbar"><label>Brush <input id="v26-size" type="range" min="1" max="40" value="5"></label><button id="v26-clear" class="soft">Clear</button></div></div>`},
  clock:{name:'Clock',icon:'🕒',build:()=>`<div class="v26-clock"><div id="v26-time">--:--:--</div><div id="v26-date" class="muted"></div></div>`},
  stopwatch:{name:'Stopwatch',icon:'⏱️',build:()=>`<div class="v26-stop"><strong id="v26-stop-time">00:00.0</strong><div><button id="v26-stop-start" class="primary">Start</button><button id="v26-stop-reset" class="soft">Reset</button></div></div>`},
  timer:{name:'Timer',icon:'⏳',build:()=>`<div class="v26-stop"><input id="v26-timer-min" type="number" min="0" value="5" aria-label="Minutes"><strong id="v26-timer-time">05:00</strong><div><button id="v26-timer-start" class="primary">Start</button><button id="v26-timer-reset" class="soft">Reset</button></div></div>`},
  screenshot:{name:'Screenshotter',icon:'📸',build:()=>`<div class="v26-tool"><h3>Screenshotter</h3><p class="muted">Capture the visible Lolite desktop.</p><button id="v26-shot" class="primary">Capture screen</button><p id="v26-shot-status" class="muted"></p></div>`},
  terminal:{name:'Terminal',icon:'⌨️',build:()=>`<div class="v26-terminal"><div id="v26-term-out">Lolite Terminal 2.6<br>Type <b>help</b> for commands.</div><div class="v26-term-row"><span>›</span><input id="v26-term-input" autocomplete="off" spellcheck="false"></div></div>`},
  system:{name:'System Information',icon:'ℹ️',build:()=>`<div class="v26-system" id="v26-system"></div>`},
  storage:{name:'Storage Manager',icon:'💾',build:()=>`<div class="v26-system" id="v26-storage"></div>`},
  network:{name:'Network Monitor',icon:'🌐',build:()=>`<div class="v26-system"><h3>Network</h3><p id="v26-network-status">Checking browser connection…</p></div>`},
  converter:{name:'Unit Converter',icon:'📏',build:()=>`<div class="v26-convert"><input id="v26-convert-value" type="number" value="1"><select id="v26-convert-from"><option value="km">Kilometres</option><option value="m">Metres</option><option value="mi">Miles</option><option value="ft">Feet</option><option value="c">Celsius</option><option value="f">Fahrenheit</option></select><span>→</span><select id="v26-convert-to"><option value="m">Metres</option><option value="km">Kilometres</option><option value="mi">Miles</option><option value="ft">Feet</option><option value="f">Fahrenheit</option><option value="c">Celsius</option></select><strong id="v26-convert-result"></strong></div>`},
  music:{name:'Music Player',icon:'🎵',build:()=>`<div class="v26-tool"><h3>Music Player</h3><p class="muted">Choose a local audio file to play it in Lolite.</p><input id="v26-audio" type="file" accept="audio/*"><audio id="v26-audio-player" controls></audio></div>`},
  notes:{name:'Quick Notes',icon:'📒',build:()=>`<div class="v26-tool"><input id="v26-quick-title" placeholder="Note title"><textarea id="v26-quick-text" placeholder="Write a note…"></textarea><button id="v26-save-note" class="primary">Save note</button><div id="v26-note-list"></div></div>`}
 };
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function open(id){const a=apps[id];if(!a)return;const wid='v26-'+id;window.openApp?.(wid,a.name,760,540);setTimeout(()=>{const c=window.state?.windows?.[wid]?.el?.querySelector('.content');if(!c)return;c.innerHTML=`<div class="v26-app"><div class="v26-apphead"><span>${a.icon} ${a.name}</span><span class="v26-version">2.6</span></div>${a.build()}</div>`;wire(id,c)},30)}
 function wire(id,c){
  if(id==='calculator')wireCalc(c); if(id==='notepad')wireNotepad(c); if(id==='paint')wirePaint(c); if(id==='clock')wireClock(c); if(id==='stopwatch')wireStop(c); if(id==='timer')wireTimer(c); if(id==='screenshot')wireShot(c); if(id==='terminal')wireTerm(c); if(id==='system')wireSystem(c); if(id==='storage')wireStorage(c); if(id==='network')wireNetwork(c); if(id==='converter')wireConverter(c); if(id==='music')wireMusic(c); if(id==='notes')wireNotes(c);
 }
 function wireCalc(c){let v='';const d=c.querySelector('#v26-calc-display');c.addEventListener('click',e=>{const b=e.target.closest('[data-calc]');if(!b)return;const x=b.dataset.calc;if(x==='C')v='';else if(x==='⌫')v=v.slice(0,-1);else if(x==='='){try{v=String(Function(`"use strict";return (${v.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-')})`)())}catch{v='Error'}}else v+=x;d.value=v||'0'})}
 function wireNotepad(c){const t=c.querySelector('textarea'),k='lolite-v26-notepad';t.value=localStorage.getItem(k)||'';t.addEventListener('input',()=>localStorage.setItem(k,t.value))}
 function wirePaint(c){const cv=c.querySelector('canvas'),ctx=cv.getContext('2d'),size=c.querySelector('#v26-size');let down=false,last=null;const pos=e=>{const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}};cv.addEventListener('pointerdown',e=>{down=true;last=pos(e);cv.setPointerCapture(e.pointerId)});cv.addEventListener('pointermove',e=>{if(!down)return;const p=pos(e);ctx.lineWidth=+size.value;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});cv.addEventListener('pointerup',()=>down=false);c.querySelector('#v26-clear').onclick=()=>ctx.clearRect(0,0,cv.width,cv.height)}
 function wireClock(c){const tick=()=>{const d=new Date();c.querySelector('#v26-time').textContent=d.toLocaleTimeString();c.querySelector('#v26-date').textContent=d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})};tick();const t=setInterval(tick,1000);c.closest('.window')?.addEventListener('remove',()=>clearInterval(t))}
 function wireStop(c){let start=0,elapsed=0,run=false,id;const out=c.querySelector('#v26-stop-time'),render=()=>{const x=elapsed+(run?performance.now()-start:0);out.textContent=`${String(Math.floor(x/60000)).padStart(2,'0')}:${String(Math.floor(x/1000)%60).padStart(2,'0')}.${Math.floor(x/100)%10}`};c.querySelector('#v26-stop-start').onclick=()=>{if(run){elapsed+=performance.now()-start;run=false;clearInterval(id);c.querySelector('#v26-stop-start').textContent='Start'}else{start=performance.now();run=true;id=setInterval(render,50);c.querySelector('#v26-stop-start').textContent='Pause'}};c.querySelector('#v26-stop-reset').onclick=()=>{elapsed=0;run=false;clearInterval(id);render()}}
 function wireTimer(c){let left=300,run=false,id;const out=c.querySelector('#v26-timer-time'),render=()=>{out.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`};const reset=()=>{left=Math.max(0,+c.querySelector('#v26-timer-min').value*60);render()};c.querySelector('#v26-timer-start').onclick=()=>{if(run){run=false;clearInterval(id);c.querySelector('#v26-timer-start').textContent='Start'}else{if(left<=0)reset();run=true;c.querySelector('#v26-timer-start').textContent='Pause';id=setInterval(()=>{left=Math.max(0,left-1);render();if(!left){run=false;clearInterval(id);c.querySelector('#v26-timer-start').textContent='Start';window.showToast?.('Timer finished')}} ,1000)}};c.querySelector('#v26-timer-reset').onclick=()=>{run=false;clearInterval(id);c.querySelector('#v26-timer-start').textContent='Start';reset()};c.querySelector('#v26-timer-min').onchange=reset;reset()}
 async function wireShot(c){c.querySelector('#v26-shot').onclick=async()=>{const s=c.querySelector('#v26-shot-status');if(!navigator.mediaDevices?.getDisplayMedia){s.textContent='Screen capture is not supported by this browser.';return}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true});const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>requestAnimationFrame(r));const cv=document.createElement('canvas');cv.width=v.videoWidth;cv.height=v.videoHeight;cv.getContext('2d').drawImage(v,0,0);stream.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.download='lolite-screenshot.png';a.href=cv.toDataURL('image/png');a.click();s.textContent='Screenshot captured.'}catch{s.textContent='Capture cancelled or blocked.'}}}
 function wireTerm(c){const input=c.querySelector('#v26-term-input'),out=c.querySelector('#v26-term-out');input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const cmd=input.value.trim();input.value='';const low=cmd.toLowerCase();let r='';if(low==='help')r='Commands: help, clear, time, date, apps, version';else if(low==='clear'){out.innerHTML='';return}else if(low==='time')r=new Date().toLocaleTimeString();else if(low==='date')r=new Date().toLocaleDateString();else if(low==='version')r='Lolite OS 2.6';else if(low==='apps')r=Object.values(apps).map(x=>x.name).join(', ');else r=`Command not found: ${esc(cmd)}`;out.innerHTML+=`<br>› ${esc(cmd)}<br>${esc(r)}`})}
 function wireSystem(c){c.querySelector('#v26-system').innerHTML=`<h3>Lolite OS 2.6</h3><p>Browser: ${esc(navigator.userAgent)}</p><p>Screen: ${screen.width} × ${screen.height}</p><p>Viewport: ${innerWidth} × ${innerHeight}</p><p>Language: ${esc(navigator.language)}</p><p>Online: ${navigator.onLine?'Yes':'No'}</p><p>Platform: ${esc(navigator.platform||'Unknown')}</p>`}
 async function wireStorage(c){const el=c.querySelector('#v26-storage');if(navigator.storage?.estimate){const x=await navigator.storage.estimate();const used=x.usage||0,total=x.quota||0;el.innerHTML=`<h3>Browser storage</h3><p>Used: ${(used/1048576).toFixed(1)} MB</p><p>Available quota: ${(total/1073741824).toFixed(2)} GB</p>`}else el.textContent='Storage estimate is not supported by this browser.'}
 function wireNetwork(c){const update=()=>c.querySelector('#v26-network-status').textContent=navigator.onLine?'Online':'Offline';update();addEventListener('online',update);addEventListener('offline',update)}
 function wireConverter(c){const convert=()=>{const n=+c.querySelector('#v26-convert-value').value||0,f=c.querySelector('#v26-convert-from').value,t=c.querySelector('#v26-convert-to').value;let base=n;if(f==='km')base=n*1000;if(f==='mi')base=n*1609.344;if(f==='ft')base=n*0.3048;if(f==='f')base=(n-32)*5/9;let r=base;if(t==='km')r=base/1000;if(t==='mi')r=base/1609.344;if(t==='ft')r=base/0.3048;if(t==='f')r=base*9/5+32;c.querySelector('#v26-convert-result').textContent=Number.isFinite(r)?String(+r.toFixed(6)):'—'};c.addEventListener('input',convert);c.addEventListener('change',convert);convert()}
 function wireMusic(c){c.querySelector('#v26-audio').onchange=e=>{const f=e.target.files?.[0];if(f)c.querySelector('#v26-audio-player').src=URL.createObjectURL(f)}}
 function wireNotes(c){const k='lolite-v26-notes',load=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(k)||'[]')}catch{};c.querySelector('#v26-note-list').innerHTML=a.map((n,i)=>`<div class="v26-note"><b>${esc(n.title||'Untitled')}</b><p>${esc(n.text)}</p><button data-del="${i}" class="soft">Delete</button></div>`).join('')||'<p class="muted">No saved notes.</p>'};c.querySelector('#v26-save-note').onclick=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(k)||'[]')}catch{};a.unshift({title:c.querySelector('#v26-quick-title').value,text:c.querySelector('#v26-quick-text').value});localStorage.setItem(k,JSON.stringify(a.slice(0,50)));c.querySelector('#v26-quick-title').value='';c.querySelector('#v26-quick-text').value='';load()};c.addEventListener('click',e=>{const b=e.target.closest('[data-del]');if(b){let a=JSON.parse(localStorage.getItem(k)||'[]');a.splice(+b.dataset.del,1);localStorage.setItem(k,JSON.stringify(a));load()}});load()}
 const basePage=window.page;window.page=function(id){if(id!=='utilities')return basePage(id);return `<h2>🧰 Utilities Pack 2.6</h2><p class="muted">Useful built-in tools for Lolite OS.</p><div class="v26-grid">${Object.entries(apps).map(([id,a])=>`<button class="v26-app-card" data-v26-open="${id}"><span>${a.icon}</span><b>${a.name}</b></button>`).join('')}</div>`};
 const oldStart=window.renderIcons;window.renderIcons=()=>{oldStart?.();const box=document.querySelector('#icons');if(!box)return;if(!box.querySelector('[data-v26-utilities]')){const b=document.createElement('button');b.className='desktop-icon';b.dataset.v26Utilities='1';b.innerHTML='<b>🧰</b><span>Utilities</span>';b.ondblclick=()=>window.openApp?.('utilities','Utilities',800,600);box.appendChild(b)}};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-v26-open]');if(b)open(b.dataset.v26Open)});
 const style=document.createElement('style');style.textContent=`.v26-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:10px}.v26-app-card{padding:18px 12px;border:1px solid #ffffff12;border-radius:14px;background:#ffffff06;color:inherit;display:grid;gap:7px;cursor:pointer;text-align:left}.v26-app-card:hover{background:#ffffff0c}.v26-app-card span{font-size:30px}.v26-app{height:100%;display:flex;flex-direction:column;gap:14px}.v26-apphead{display:flex;justify-content:space-between;font-weight:700}.v26-version{font-size:10px;opacity:.5}.v26-calc{max-width:430px;margin:auto}.v26-calc input{width:100%;font-size:28px;text-align:right;margin-bottom:10px}.v26-calc-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.v26-calc-grid button{min-height:54px}.v26-notes,.v26-tool textarea{width:100%;min-height:360px;resize:vertical}.v26-paint canvas{width:100%;height:auto;background:#fff;touch-action:none;border-radius:10px}.v26-paintbar{display:flex;gap:10px;align-items:center;margin-top:8px}.v26-clock,.v26-stop{text-align:center;display:grid;place-items:center;gap:16px;padding:35px}.v26-clock #v26-time{font-size:56px;font-weight:700}.v26-stop strong{font-size:48px}.v26-stop input{max-width:130px}.v26-terminal{height:100%;background:#070707;color:#e8e8e8;border-radius:10px;padding:14px;font-family:monospace;overflow:auto}.v26-term-row{display:flex;gap:8px}.v26-term-row input{flex:1;background:transparent;border:0;color:inherit;outline:0;font:inherit}.v26-convert{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.v26-convert input{max-width:130px}.v26-convert strong{width:100%;font-size:22px}.v26-note{border:1px solid #ffffff12;border-radius:10px;padding:10px;margin-top:8px}.v26-tool{display:grid;gap:10px}.v26-tool audio{width:100%}@media(max-width:600px){.v26-grid{grid-template-columns:repeat(2,1fr)}.v26-clock #v26-time{font-size:38px}.v26-stop strong{font-size:34px}}`;document.head.appendChild(style);
 window.LoliteV26={version:V,open};
})();
