/* Lolite OS 2.8 — Widgets & Quick Settings */
(()=>{
 const V='2.8',KEY='lolite-v28-widgets';
 const defaults={widgets:['clock','calendar','notes','storage','network','recent','favorites','sandbox'],quick:{glass:false,reduce:false,gaming:false,dnd:false,brightness:100,volume:70}};
 let state={...defaults,quick:{...defaults.quick}};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}'),quick:{...defaults.quick,...(JSON.parse(localStorage.getItem(KEY)||'{}').quick||{})}}}catch{}
 const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
 const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));
 const notes=()=>localStorage.getItem('lolite-v26-quick-notes')||localStorage.getItem('lolite-quick-notes')||'';
 const widgetData={
  clock:{title:'Clock',body:()=>`<div class="v28-clock" id="v28-clock">--:--</div><div class="v28-muted" id="v28-date"></div>`},
  calendar:{title:'Calendar',body:()=>{const d=new Date();return `<div class="v28-calendar"><b>${d.toLocaleString(undefined,{month:'long',year:'numeric'})}</b><div class="v28-calgrid">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}${(()=>{let out='';const first=new Date(d.getFullYear(),d.getMonth(),1).getDay(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();for(let i=0;i<first;i++)out+='<i></i>';for(let n=1;n<=days;n++)out+=`<span class="${n===d.getDate()?'today':''}">${n}</span>`;return out})()}</div></div>`}},
  weather:{title:'Weather',body:()=>`<div class="v28-big">☁️</div><b>Weather unavailable</b><div class="v28-muted">Connect a weather provider to enable live conditions.</div>`},
  battery:{title:'Battery',body:()=>`<div class="v28-big">🔋</div><b id="v28-battery">Checking…</b><div class="v28-muted">Browser battery information when supported.</div>`},
  storage:{title:'Storage',body:()=>`<div class="v28-big">▣</div><b id="v28-storage">Checking…</b><div class="v28-muted">Local browser storage estimate.</div>`},
  network:{title:'Network',body:()=>`<div class="v28-status" id="v28-network">Checking…</div><div class="v28-muted">Browser online status.</div>`},
  notes:{title:'Quick Notes',body:()=>`<div class="v28-note-preview">${esc(notes())||'<span class="v28-muted">No quick notes yet.</span>'}</div>`},
  recent:{title:'Recently Played',body:()=>{let a=[];try{a=JSON.parse(localStorage.getItem('lolite-game-recent-2.5')||'[]')}catch{}return a.length?`<div class="v28-list">${a.slice(0,5).map(x=>`<span>🎮 ${esc(typeof x==='string'?x:(x.name||x.id||'Game'))}</span>`).join('')}</div>`:'<span class="v28-muted">No recently played games.</span>'}},
  favorites:{title:'Favourite Apps',body:()=>`<div class="v28-list"><span>📁 Files</span><span>🎮 Game Library</span><span>🛠 Utilities</span><span>⚙ Settings</span></div>`},
  sandbox:{title:'World Sandbox',body:()=>`<div class="v28-big">🌎</div><div class="v28-muted">Your World Sandbox workspace is ready.</div><button class="primary" data-v28-open="world-sandbox">Open Sandbox</button>`}
 };
 function widgetsPage(){return `<div class="v28-page"><div class="v28-head"><div><h2>Widgets</h2><p>Useful information at a glance.</p></div><button class="soft" id="v28-refresh">Refresh</button></div><div class="v28-widget-grid">${state.widgets.map(k=>widgetData[k]?`<section class="v28-card"><div class="v28-card-head"><b>${widgetData[k].title}</b><button class="v28-hide" data-v28-hide="${k}" title="Hide widget">×</button></div>${widgetData[k].body()}</section>`:'').join('')}</div><div class="v28-muted v28-foot">Widgets are lightweight and use browser-local information unless a provider is connected.</div></div>`}
 function quickPage(){const q=state.quick;return `<div class="v28-page"><div class="v28-head"><div><h2>Quick Settings</h2><p>Fast controls for your workspace.</p></div></div><div class="v28-toggle-grid">${[['glass','Liquid Glass'],['reduce','Reduce Motion'],['gaming','Gaming Mode'],['dnd','Do Not Disturb']].map(([k,t])=>`<button class="v28-toggle ${q[k]?'on':''}" data-v28-toggle="${k}"><strong>${t}</strong><span>${q[k]?'On':'Off'}</span></button>`).join('')}</div><div class="v28-sliders"><label>Brightness <input id="v28-bright" type="range" min="30" max="100" value="${q.brightness}"><output>${q.brightness}%</output></label><label>Volume <input id="v28-volume" type="range" min="0" max="100" value="${q.volume}"><output>${q.volume}%</output></label></div><div class="v28-actions"><button class="soft" id="v28-reset">Reset controls</button></div></div>`}
 function targetContent(id){const w=window.state?.windows?.[id]?.el?.querySelector('.content');return w}
 function bindWidgets(c){c.querySelectorAll('[data-v28-hide]').forEach(b=>b.onclick=()=>{state.widgets=state.widgets.filter(x=>x!==b.dataset.v28Hide);save();renderWidgets()});c.querySelector('#v28-refresh')?.addEventListener('click',renderWidgets);c.querySelector('[data-v28-open]')?.addEventListener('click',()=>window.openApp?.('world-sandbox'));updateLive();}
 function bindQuick(c){c.querySelectorAll('[data-v28-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.v28Toggle;state.quick[k]=!state.quick[k];applyQuick();renderQuick()});const bindRange=(id,k)=>{const x=c.querySelector(id),o=x?.nextElementSibling;if(!x)return;x.oninput=()=>{state.quick[k]=+x.value;o.textContent=x.value+'%';save();applyQuick()}};bindRange('#v28-bright','brightness');bindRange('#v28-volume','volume');c.querySelector('#v28-reset')?.addEventListener('click',()=>{state.quick={...defaults.quick};save();applyQuick();renderQuick()})}
 function renderWidgets(){const c=targetContent('widgets');if(c){c.innerHTML=widgetsPage();bindWidgets(c)}}
 function renderQuick(){const c=targetContent('quick-settings');if(c){c.innerHTML=quickPage();bindQuick(c)}}
 function updateLive(){const now=new Date(),clock=document.getElementById('v28-clock'),date=document.getElementById('v28-date');if(clock)clock.textContent=now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(date)date.textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});const net=document.getElementById('v28-network');if(net)net.textContent=navigator.onLine?'Online':'Offline';navigator.storage?.estimate?.().then(x=>{const el=document.getElementById('v28-storage');if(el){const used=x.usage||0,total=x.quota||0;el.textContent=total?`${(used/1048576).toFixed(1)} MB / ${(total/1073741824).toFixed(2)} GB`:'Available'}});navigator.getBattery?.().then(b=>{const el=document.getElementById('v28-battery');if(el)el.textContent=Math.round(b.level*100)+'%'+(b.charging?' · Charging':'')}).catch(()=>{})}
 function applyQuick(){document.body.classList.toggle('v28-glass',!!state.quick.glass);document.body.classList.toggle('v28-gaming',!!state.quick.gaming);document.body.classList.toggle('v28-dnd',!!state.quick.dnd);document.body.classList.toggle('v28-reduce',!!state.quick.reduce);document.documentElement.style.setProperty('--v28-brightness',(state.quick.brightness/100).toFixed(2));save();}
 const oldPage=window.page;window.page=function(id){if(id==='widgets')return widgetsPage();if(id==='quick-settings'||id==='quicksettings')return quickPage();return oldPage?.(id)};
 const oldOpen=window.openApp;window.openApp=function(id,...rest){const r=oldOpen?.(id,...rest);if(id==='widgets')setTimeout(renderWidgets,30);if(id==='quick-settings'||id==='quicksettings')setTimeout(renderQuick,30);return r};
 const style=document.createElement('style');style.textContent=`
 .v28-page{padding:22px;color:var(--text);min-height:100%}.v28-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.v28-head h2{margin:0}.v28-head p{margin:5px 0;color:var(--muted)}.v28-widget-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.v28-card{padding:15px;border:1px solid #ffffff12;background:#ffffff07;border-radius:16px;min-height:145px}.v28-card-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.v28-hide{background:transparent;font-size:20px;color:var(--muted)}.v28-clock{font-size:42px;font-weight:800;letter-spacing:-2px}.v28-big{font-size:42px;margin:5px 0}.v28-muted{color:var(--muted);font-size:12px}.v28-status{font-size:22px;font-weight:700;margin:12px 0}.v28-note-preview{white-space:pre-wrap;max-height:90px;overflow:auto;line-height:1.5}.v28-list{display:grid;gap:7px}.v28-list span{padding:7px 9px;border-radius:9px;background:#ffffff06}.v28-calendar>b{display:block;margin-bottom:10px}.v28-calgrid{display:grid;grid-template-columns:repeat(7,1fr);gap:3px;text-align:center;font-size:11px}.v28-calgrid span,.v28-calgrid i{padding:5px}.v28-calgrid .today{border-radius:7px;background:var(--accent);color:#fff;font-weight:700}.v28-foot{margin-top:15px}.v28-toggle-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.v28-toggle{text-align:left;padding:18px;border:1px solid #ffffff12;border-radius:15px;background:#ffffff07;display:flex;justify-content:space-between;align-items:center}.v28-toggle.on{outline:2px solid var(--accent);background:#8b5cf612}.v28-toggle span{color:var(--muted)}.v28-sliders{display:grid;gap:12px;margin-top:14px}.v28-sliders label{display:grid;grid-template-columns:90px 1fr 55px;gap:10px;align-items:center;padding:13px;background:#ffffff07;border-radius:12px}.v28-sliders output{text-align:right;color:var(--muted)}.v28-actions{margin-top:14px}.v28-glass .window,.v28-glass .panel,#desktop.v28-glass #taskbar{background:linear-gradient(135deg,#ffffff20,#ffffff08)!important;backdrop-filter:blur(25px) saturate(145%)!important;-webkit-backdrop-filter:blur(25px) saturate(145%)!important}.v28-gaming #taskbar{box-shadow:0 0 0 1px var(--accent),0 12px 40px #0008}.v28-dnd #taskbar #notificationBtn{opacity:.45}.v28-reduce *,body.v28-reduce *::before,body.v28-reduce *::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.v28-toggle.on strong{color:var(--accent)}#desktop{filter:brightness(var(--v28-brightness,1))}@media(max-width:700px){.v28-toggle-grid{grid-template-columns:1fr}.v28-page{padding:14px}.v28-sliders label{grid-template-columns:75px 1fr 48px}}
 `;document.head.appendChild(style);
 applyQuick();setInterval(updateLive,1000);addEventListener('online',updateLive);addEventListener('offline',updateLive);
 window.LoliteV28={version:V,getState:()=>({...state,quick:{...state.quick}}),openWidgets:()=>window.openApp?.('widgets'),openQuickSettings:()=>window.openApp?.('quick-settings')};
})();
