/* Lolite OS 2.9 — Game Library ZIP Packs */
(()=>{
 const V='2.9', KEY='lolite-game-library-2.9', ZIP_URL='https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js';
 const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
 const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const fav=()=>read(KEY+':favorites'), recent=()=>read(KEY+':recent');
 const setFav=v=>write(KEY+':favorites',v), setRecent=v=>write(KEY+':recent',v);
 const base=window.page;
 const meta={
  'lolite-2048.html':['2048','Puzzle','Arrow keys / swipe to move tiles.'],
  'lolite-pong.html':['Pong','Arcade','Move with the mouse or touch controls.'],
  'lolite-sokoban.html':['Sokoban','Puzzle','Arrow keys / WASD to push boxes.']
 };
 const info=file=>{const x=meta[file];if(x)return {name:x[0],category:x[1],description:x[2]};const n=file.replace(/\.(html|htm|zip)$/i,'').replace(/^cl/i,'').replace(/[-_]+/g,' ');return {name:n.replace(/\b\w/g,m=>m.toUpperCase()),category:/\.zip$/i.test(file)?'ZIP Game Pack':'HTML Game',description:/\.zip$/i.test(file)?'ZIP pack containing playable HTML games.':'Standalone HTML game. Controls are shown by the game.'}};
 let cache={games:[],loading:false};
 const packCache=new Map();
 const loadJSZip=()=>new Promise((resolve,reject)=>{if(window.JSZip)return resolve(window.JSZip);const s=document.createElement('script');s.src=ZIP_URL;s.onload=()=>window.JSZip?resolve(window.JSZip):reject(Error('JSZip unavailable'));s.onerror=()=>reject(Error('ZIP library failed to load'));document.head.appendChild(s)});
 async function discover(force=false){if(cache.games.length&&!force)return cache.games;if(cache.loading)return cache.games;cache.loading=true;try{const r=await fetch('https://api.github.com/repos/darby9123-arch/Lolite-OS/contents/html%20games',{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw Error('discovery failed');const items=await r.json(),seen=new Set();cache.games=items.filter(x=>x.type==='file'&&/\.(html|htm|zip)$/i.test(x.name)).map(x=>{const i=info(x.name);return {file:x.name,name:i.name,category:i.category,description:i.description,size:x.size||0,download:x.download_url||''}}).filter(g=>{const k=g.file.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.name.localeCompare(b.name));return cache.games}catch{return cache.games}finally{cache.loading=false}}
 const isFav=f=>fav().includes(f);
 function toggleFav(file){const a=fav(),i=a.indexOf(file);i>=0?a.splice(i,1):a.unshift(file);setFav(a.slice(0,100));render()}
 function markRecent(file){const a=recent().filter(x=>x!==file);a.unshift(file);setRecent(a.slice(0,30))}
 function install(file){const a=read(KEY+':installed');if(!a.includes(file)){a.push(file);write(KEY+':installed',a)}return true}
 function safePath(path){return path.split('/').filter(x=>x&&x!=='.'&&x!=='..').join('/')}
 function resolvePath(from,ref){if(!ref||/^(data:|blob:|https?:|mailto:|javascript:|#)/i.test(ref))return null;const clean=ref.split('#')[0].split('?')[0];if(!clean)return null;const parts=safePath((from||'').split('/').slice(0,-1).concat(clean.split('/')).join('/'));return parts}
 function mime(path){const ext=(path.match(/\.([^.]+)$/)||[])[1]?.toLowerCase();return ({html:'text/html',htm:'text/html',js:'text/javascript',css:'text/css',json:'application/json',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',mp3:'audio/mpeg',wav:'audio/wav',ogg:'audio/ogg',mp4:'video/mp4',webm:'video/webm',woff:'font/woff',woff2:'font/woff2',ttf:'font/ttf'}[ext]||'application/octet-stream')}
 async function extractPack(game){
  if(packCache.has(game.file))return packCache.get(game.file);
  await loadJSZip();
  const res=await fetch('html%20games/'+encodeURIComponent(game.file),{cache:'no-store'});if(!res.ok)throw Error('Could not download ZIP pack');
  const zip=await JSZip.loadAsync(await res.arrayBuffer());const files={};
  for(const [path,obj] of Object.entries(zip.files)){if(obj.dir)continue;const p=safePath(path);if(p)files[p]=obj}
  const urls={};
  for(const [path,obj] of Object.entries(files)){const data=await obj.async('blob');urls[path]=URL.createObjectURL(new Blob([data],{type:mime(path)}))}
  const htmls=Object.keys(files).filter(p=>/\.(html|htm)$/i.test(p)).sort((a,b)=>{const ai=/^(index|game)\.(html|htm)$/i.test(a)?-1:0,bi=/^(index|game)\.(html|htm)$/i.test(b)?-1:0;return ai-bi||a.localeCompare(b)});
  const pack={files,urls,htmls};packCache.set(game.file,pack);return pack;
 }
 function rewriteCss(css,path,urls){return css.replace(/url\(\s*([\"']?)([^\"')]+)\1\s*\)/gi,(m,q,ref)=>{const target=resolvePath(path,ref);return target&&urls[target]?`url(${q}${urls[target]}${q})`:m})}
 async function buildHtml(pack,path){
  const obj=pack.files[path];if(!obj)throw Error('HTML file not found');let html=await obj.async('text');
  const doc=new DOMParser().parseFromString(html,'text/html');
  doc.querySelectorAll('[src],[href]').forEach(el=>{const attr=el.hasAttribute('src')?'src':'href',ref=el.getAttribute(attr),target=resolvePath(path,ref);if(target&&pack.urls[target])el.setAttribute(attr,pack.urls[target])});
  for(const link of doc.querySelectorAll('link[href]')){const ref=link.getAttribute('href'),target=resolvePath(path,ref);if(target&&/\.css$/i.test(target)&&pack.files[target]){const css= rewriteCss('',target,pack.urls);link.setAttribute('href',pack.urls[target]);}}
  for(const style of doc.querySelectorAll('style'))style.textContent=rewriteCss(style.textContent,path,pack.urls);
  const baseEl=doc.querySelector('base');if(baseEl)baseEl.remove();
  return '<!doctype html>'+doc.documentElement.outerHTML;
 }
 function showError(id,msg){const w=window.state?.windows?.[id],c=w?.el?.querySelector('.content');if(c)c.innerHTML=`<div class="v29-error"><b>ZIP game pack could not open</b><p>${esc(msg)}</p><button class="soft v29-close">Close</button></div>`;c?.querySelector('.v29-close')?.addEventListener('click',()=>window.closeWindow?.(id))}
 function playExtracted(parentId,pack,path,title){const id=parentId+'-'+path.replace(/[^a-z0-9]+/gi,'-');if(window.state?.windows?.[id]){window.restoreWin?.(id);return}window.openApp?.(id,title,920,680);setTimeout(async()=>{const w=window.state?.windows?.[id],c=w?.el?.querySelector('.content');if(!c)return;c.innerHTML='<div class="v29-player"><div class="v29-playerbar"><strong>'+esc(title)+'</strong><span><button class="soft v29-full">Fullscreen</button><button class="soft v29-close">Close</button></span></div><iframe title="'+esc(title)+'" loading="eager" allow="fullscreen; gamepad"></iframe></div>';const f=c.querySelector('iframe');try{f.srcdoc=await buildHtml(pack,path)}catch(e){showError(id,e.message||'Unknown ZIP error');return}c.querySelector('.v29-full')?.addEventListener('click',()=>{try{f.requestFullscreen?.()}catch{}});c.querySelector('.v29-close')?.addEventListener('click',()=>window.closeWindow?.(id));f?.addEventListener('load',()=>f.focus(),{once:true})},50)}
 async function launch(game){install(game.file);markRecent(game.file);render();const id='v29-game-'+game.file.replace(/[^a-z0-9]+/gi,'-');if(window.state?.windows?.[id]){window.restoreWin?.(id);return}if(/\.zip$/i.test(game.file)){window.openApp?.(id,game.name,760,560);setTimeout(async()=>{const w=window.state?.windows?.[id],c=w?.el?.querySelector('.content');if(!c)return;c.innerHTML='<div class="v29-loading">Opening ZIP game pack…</div>';try{const pack=await extractPack(game);if(!pack.htmls.length)throw Error('No HTML or HTM game was found inside this ZIP.');if(pack.htmls.length===1){playExtracted(id,pack,pack.htmls[0],pack.htmls[0].split('/').pop().replace(/\.(html|htm)$/i,''));return}c.innerHTML='<div class="v29-picker"><div><b>'+esc(game.name)+'</b><p class="muted">Choose a game from this ZIP pack.</p></div><div class="v29-pack-list">'+pack.htmls.map((p,i)=>`<button class="soft v29-pack-item" data-pack-path="${encodeURIComponent(p)}"><span>${esc(p.split('/').pop())}</span><small>${esc(p)}</small></button>`).join('')+'</div><button class="soft v29-close">Close</button></div>';c.querySelectorAll('[data-pack-path]').forEach(b=>b.addEventListener('click',()=>playExtracted(id,pack,decodeURIComponent(b.dataset.packPath),decodeURIComponent(b.dataset.packPath).split('/').pop().replace(/\.(html|htm)$/i,''))));c.querySelector('.v29-close')?.addEventListener('click',()=>window.closeWindow?.(id))}catch(e){showError(id,e.message||'Unknown ZIP error')}},50);return}
  const i=info(game.file);window.openApp?.(id,game.name,920,680);setTimeout(()=>{const w=window.state?.windows?.[id],c=w?.el?.querySelector('.content');if(!c)return;c.innerHTML=`<div class="v29-player"><div class="v29-playerbar"><strong>${esc(game.name)}</strong><span><button class="soft v29-full">Fullscreen</button><button class="soft v29-close">Close</button></span></div><iframe title="${esc(game.name)}" src="html%20games/${encodeURIComponent(game.file)}" loading="eager" allow="fullscreen; gamepad"></iframe></div>`;const f=c.querySelector('iframe');c.querySelector('.v29-full')?.addEventListener('click',()=>{try{f.requestFullscreen?.()}catch{}});c.querySelector('.v29-close')?.addEventListener('click',()=>window.closeWindow?.(id));f?.addEventListener('load',()=>f.focus(),{once:true})},50)
 }
 function cards(games){return games.map(g=>`<article class="v29-game-card"><button class="v29-thumb" data-play="${encodeURIComponent(g.file)}" aria-label="Play ${esc(g.name)}"><span>${/\.zip$/i.test(g.file)?'🗜️':'🎮'}</span></button><div class="v29-game-body"><div class="v29-title-row"><h3>${esc(g.name)}</h3><button class="v29-star ${isFav(g.file)?'on':''}" data-fav="${encodeURIComponent(g.file)}" aria-label="${isFav(g.file)?'Remove from favorites':'Add to favorites'}">${isFav(g.file)?'★':'☆'}</button></div><div class="v29-tags"><span>${esc(g.category)}</span><span>${/\.zip$/i.test(g.file)?'ZIP Pack':'HTML'}</span></div><p>${esc(g.description)}</p><div class="v29-card-actions"><button class="primary" data-play="${encodeURIComponent(g.file)}">Play</button><button class="soft" data-install="${encodeURIComponent(g.file)}">${read(KEY+':installed').includes(g.file)?'Installed':'Install'}</button></div></div></article>`).join('')}
 function render(){const grid=document.getElementById('v29-grid');if(!grid)return;const q=(document.getElementById('v29-search')?.value||'').trim().toLowerCase(),cat=document.getElementById('v29-category')?.value||'All';let rows=cache.games.filter(g=>(!q||g.name.toLowerCase().includes(q)||g.file.toLowerCase().includes(q)||g.category.toLowerCase().includes(q))&&(cat==='All'||g.category===cat));const mode=document.querySelector('.v29-filter.active')?.dataset.mode||'all';if(mode==='favorites')rows=rows.filter(g=>isFav(g.file));if(mode==='recent'){const r=recent();rows=rows.filter(g=>r.includes(g.file)).sort((a,b)=>r.indexOf(a.file)-r.indexOf(b.file))}grid.innerHTML=rows.length?cards(rows):'<div class="v29-empty"><b>No games found</b><span>Try another search or filter.</span></div>';const count=document.getElementById('v29-count');if(count)count.textContent=`${rows.length} of ${cache.games.length} games`}
 function wire(){document.getElementById('v29-search')?.addEventListener('input',render);document.getElementById('v29-category')?.addEventListener('change',render);document.getElementById('v29-refresh')?.addEventListener('click',async()=>{const b=document.getElementById('v29-refresh');if(b)b.textContent='Refreshing…';await discover(true);render();if(b)b.textContent='↻ Refresh'});document.querySelectorAll('.v29-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.v29-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));document.getElementById('v29-grid')?.addEventListener('click',e=>{const play=e.target.closest('[data-play]'),fv=e.target.closest('[data-fav]'),ins=e.target.closest('[data-install]');if(fv)toggleFav(decodeURIComponent(fv.dataset.fav));else if(ins){install(decodeURIComponent(ins.dataset.install));render()}else if(play){const file=decodeURIComponent(play.dataset.play),g=cache.games.find(x=>x.file===file);if(g)launch(g)}});render()}
 window.LoliteV29={version:V,refresh:()=>discover(true).then(render),favorites:()=>fav(),recent:()=>recent(),packs:()=>[...packCache.keys()]};
 window.page=function(id){if(id!=='game-store')return base(id);setTimeout(async()=>{await discover();const cats=['All',...new Set(cache.games.map(g=>g.category))];const cat=document.getElementById('v29-category');if(cat)cat.innerHTML=cats.map(x=>`<option>${esc(x)}</option>`).join('');wire()},0);return `<div class="v29-store-head"><div><div class="v29-kicker">LOLITE GAMES</div><h2>Game Library 2.9</h2><p class="muted">HTML games plus ZIP game packs, with search, favorites and fullscreen play.</p></div><button id="v29-refresh" class="soft">↻ Refresh</button></div><div class="v29-toolbar"><input id="v29-search" type="search" placeholder="Search games or packs…" autocomplete="off"><select id="v29-category" aria-label="Game category"><option>All</option></select></div><div class="v29-filters"><button class="soft v29-filter active" data-mode="all">All</button><button class="soft v29-filter" data-mode="favorites">★ Favorites</button><button class="soft v29-filter" data-mode="recent">Recently played</button><span id="v29-count" class="muted"></span></div><div id="v29-grid" class="v29-grid"></div>`};
 const style=document.createElement('style');style.id='v29-style';style.textContent=`.v29-store-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:16px}.v29-kicker{font-size:11px;letter-spacing:.14em;opacity:.55}.v29-toolbar{display:flex;gap:10px;margin-bottom:10px}.v29-toolbar input{flex:1;min-width:0}.v29-filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:14px}.v29-filter.active{border-color:#7c5cff;background:#7c5cff18}.v29-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}.v29-game-card{overflow:hidden;border:1px solid #ffffff12;border-radius:16px;background:#ffffff06;display:flex;flex-direction:column}.v29-thumb{height:130px;border:0;background:linear-gradient(135deg,#16102b,#10213b);color:#fff;display:grid;place-items:center;font-size:42px;cursor:pointer}.v29-thumb:hover{filter:brightness(1.15)}.v29-game-body{padding:13px}.v29-title-row{display:flex;align-items:center;gap:8px}.v29-title-row h3{margin:0;flex:1}.v29-star{border:0;background:none;font-size:23px;color:inherit;cursor:pointer}.v29-star.on{color:#ffd76a}.v29-tags{display:flex;gap:6px;margin:7px 0}.v29-tags span{font-size:10px;padding:3px 7px;border-radius:999px;border:1px solid #ffffff12;opacity:.72}.v29-game-body p{min-height:38px;margin:8px 0;color:#aaa}.v29-card-actions{display:flex;gap:8px}.v29-card-actions button{flex:1}.v29-empty,.v29-loading,.v29-error{padding:35px;text-align:center;display:grid;gap:8px;place-items:center;opacity:.82}.v29-player{height:100%;display:flex;flex-direction:column;gap:8px}.v29-playerbar{display:flex;align-items:center;justify-content:space-between;gap:10px}.v29-playerbar span{display:flex;gap:6px}.v29-player iframe{flex:1;width:100%;min-height:500px;border:0;border-radius:12px;background:#000}.v29-picker{height:100%;display:flex;flex-direction:column;gap:14px}.v29-pack-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:9px;overflow:auto}.v29-pack-item{display:grid;text-align:left;gap:4px;padding:12px}.v29-pack-item small{opacity:.55;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:650px){.v29-store-head{flex-direction:column}.v29-toolbar{flex-direction:column}.v29-grid{grid-template-columns:1fr}.v29-player iframe{min-height:calc(100vh - 130px)}}`;
 document.head.appendChild(style);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(discover,400));else setTimeout(discover,400);
})();
