/* Lolite OS 2.0: responsive modes, utility store, AI app and UI polish. */
(()=>{const V='2.0',utilityNames=['Paint','Notepad','Calculator','Screen Capture','Clock','Widgets','Battery','Auto Clicker','Terminal'],utilityKey='lolite-installed-utilities';localStorage.setItem('lolite-os-version',V);
const installed=()=>JSON.parse(localStorage.getItem(utilityKey)||'[]');const save=a=>localStorage.setItem(utilityKey,JSON.stringify([...new Set(a)]));const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const open=(name)=>{if(typeof window.openApp==='function')window.openApp(name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,760,540)};
const toast=m=>{const t=document.querySelector('#toast');if(!t)return;t.innerHTML='<div class="toast">'+esc(m)+'</div>';setTimeout(()=>t.innerHTML='',2200)};
const addIcon=name=>{const icons=document.querySelector('#icons');if(!icons||[...icons.querySelectorAll('.desktop-icon span:last-child')].some(x=>x.textContent===name))return;const b=document.createElement('button');b.className='desktop-icon';b.innerHTML='<span class="app-symbol app-'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'"></span><span>'+esc(name)+'</span>';b.onclick=()=>open(name);icons.appendChild(b)};
const hideUninstalled=()=>{const set=new Set(installed());document.querySelectorAll('#icons .desktop-icon').forEach(x=>{const n=x.querySelector('span:last-child')?.textContent;if(utilityNames.includes(n))x.style.display=set.has(n)?'block':'none'})};
window.LoliteUtilities={install(name){if(!utilityNames.includes(name))return;save([...installed(),name]);addIcon(name);hideUninstalled();toast(name+' installed')},installed,uninstall(name){save(installed().filter(x=>x!==name));hideUninstalled()}};
window.openLoliteAI=()=>{const id='lolite-ai';if(document.getElementById(id))return;const w=document.createElement('section');w.id=id;w.className='window';w.style.cssText='left:12%;top:10%;width:min(760px,76vw);height:min(600px,72vh);z-index:900';w.innerHTML='<header class="titlebar"><strong>Lolite AI</strong><div class="controls"><button class="close" aria-label="Close">×</button></div></header><div class="content ai-app"><div class="ai-hero"><div class="ai-mark">L</div><div><h1>Lolite AI</h1><p class="muted">Your built-in AI assistant.</p></div></div><div id="aiMessages" class="ai-messages"><div class="ai-msg bot">Hey! I’m Lolite AI. Ask me anything.</div></div><form id="aiForm" class="ai-form"><input id="aiInput" autocomplete="off" placeholder="Ask Lolite AI…"><button class="primary">Send</button></form></div>';document.querySelector('#windows').appendChild(w);w.querySelector('.close').onclick=()=>w.remove();const box=w.querySelector('#aiMessages'),form=w.querySelector('#aiForm'),input=w.querySelector('#aiInput');form.onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;box.insertAdjacentHTML('beforeend','<div class="ai-msg user">'+esc(q)+'</div>');input.value='';const wait=document.createElement('div');wait.className='ai-msg bot';wait.textContent='Thinking…';box.appendChild(wait);box.scrollTop=box.scrollHeight;try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI unavailable');wait.textContent=d.output||'No response.'}catch(err){wait.textContent='Lolite AI is unavailable. Configure the server-side AI API key to enable it.'}};input.focus()};
const store=()=>{const id='lolite-utilities-store';if(document.getElementById(id))return;const w=document.createElement('section');w.id=id;w.className='window';w.style.cssText='left:8%;top:8%;width:min(820px,84vw);height:min(620px,78vh);z-index:890';w.innerHTML='<header class="titlebar"><strong>Lolite Utilities</strong><div class="controls"><button class="close">×</button></div></header><div class="content"><div class="game-hero"><div><h1>Utilities</h1><p class="muted">Install only the tools you want. Utilities are not installed by default.</p></div></div><div class="cards utility-store-grid">'+utilityNames.map(n=>'<article class="card utility-card"><span class="app-symbol app-'+n.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'"></span><h3>'+n+'</h3><p class="muted">Lolite utility</p><button class="primary" data-install="'+esc(n)+'">'+(installed().includes(n)?'Open':'Install')+'</button></article>').join('')+'</div></div>';document.querySelector('#windows').appendChild(w);w.querySelector('.close').onclick=()=>w.remove();w.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>{const n=b.dataset.install;if(installed().includes(n))open(n);else{window.LoliteUtilities.install(n);b.textContent='Open'}})};
const addStoreEntry=()=>{const icons=document.querySelector('#icons');if(!icons)return;if(![...icons.querySelectorAll('span:last-child')].some(x=>x.textContent==='Utilities')){const b=document.createElement('button');b.className='desktop-icon';b.innerHTML='<span class="app-symbol app-store"></span><span>Utilities</span>';b.onclick=store;icons.appendChild(b)}};
const addAIEntry=()=>{const icons=document.querySelector('#icons');if(!icons)return;if(![...icons.querySelectorAll('span:last-child')].some(x=>x.textContent==='Lolite AI')){const b=document.createElement('button');b.className='desktop-icon';b.innerHTML='<span class="app-symbol app-ai"></span><span>Lolite AI</span>';b.onclick=window.openLoliteAI;icons.appendChild(b)}};
const picker=()=>{const saved=localStorage.getItem('lolite-device-mode');if(saved){document.body.dataset.device=saved;return}const x=document.createElement('div');x.id='device-mode-picker';x.innerHTML='<div class="mode-card"><div class="mode-logo">L</div><h1>Welcome to Lolite OS</h1><p>Choose the layout that fits your device.</p><div class="mode-actions"><button data-mode="pc" class="primary">PC</button><button data-mode="mobile" class="soft">Mobile</button></div><small>You can change this later in Settings.</small></div>';document.body.appendChild(x);x.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{localStorage.setItem('lolite-device-mode',b.dataset.mode);document.body.dataset.device=b.dataset.mode;x.remove()})};
const prepare=()=>{picker();addStoreEntry();addAIEntry();hideUninstalled()};setTimeout(prepare,150);window.addEventListener('load',()=>setTimeout(prepare,500));window.LoliteV20={version:V,openAI:window.openLoliteAI,openUtilities:store};
})();