/* Lolite OS 2.2: platform features, notifications, plugin-ready app store and AI quick actions. */
(()=>{
 const V='2.2', STORE_KEY='lolite-plugins-v22', NOTIFY_KEY='lolite-notifications-v22';
 const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 const toast=m=>{const t=document.querySelector('#toast');if(t){t.textContent=m;setTimeout(()=>t.textContent='',2200)}};
 const plugins=[
  {id:'weather',name:'Weather Widget',type:'Widget',desc:'A lightweight weather widget slot for the desktop.'},
  {id:'notes-widget',name:'Quick Notes',type:'Widget',desc:'A small sticky-notes workspace.'},
  {id:'focus',name:'Focus Mode',type:'Utility',desc:'Temporarily hides desktop distractions.'},
  {id:'system-info',name:'System Info',type:'Utility',desc:'Shows browser, screen and Lolite environment details.'}
 ];
 const installed=()=>{try{return JSON.parse(localStorage.getItem(STORE_KEY)||'[]')}catch{return[]}};
 const save=a=>localStorage.setItem(STORE_KEY,JSON.stringify([...new Set(a)]));
 const notify=(title,message)=>{let a;try{a=JSON.parse(localStorage.getItem(NOTIFY_KEY)||'[]')}catch{a=[]}a.unshift({title,message,time:new Date().toISOString()});localStorage.setItem(NOTIFY_KEY,JSON.stringify(a.slice(0,30)));window.LoliteNotifications?.refresh?.()};
 function notifications(){if(document.getElementById('lolite-notifications'))return;const w=document.createElement('section');w.id='lolite-notifications';w.className='window';w.style.cssText='right:20px;top:70px;width:min(420px,90vw);height:min(560px,78vh);z-index:1100';w.innerHTML='<header class="titlebar"><strong>Notification Center</strong><div class="controls"><button class="close">×</button></div></header><div class="content"><div class="notification-head"><div><h2>Notifications</h2><p class="muted">Recent Lolite activity</p></div><button id="clearNotifs" class="soft">Clear</button></div><div id="notificationList" class="notification-list"></div></div>';document.querySelector('#windows').appendChild(w);w.querySelector('.close').onclick=()=>w.remove();w.querySelector('#clearNotifs').onclick=()=>{localStorage.removeItem(NOTIFY_KEY);render();};function render(){let a=[];try{a=JSON.parse(localStorage.getItem(NOTIFY_KEY)||'[]')}catch{}const box=w.querySelector('#notificationList');box.innerHTML=a.length?a.map(n=>'<article class="notification-card"><strong>'+esc(n.title)+'</strong><p>'+esc(n.message)+'</p><small>'+new Date(n.time).toLocaleString()+'</small></article>').join(''):'<div class="empty-state">You’re all caught up.</div>'}function refresh(){if(document.body.contains(w))render()}render();window.LoliteNotifications={refresh};}
 function pluginStore(){if(document.getElementById('lolite-plugin-store'))return;const w=document.createElement('section');w.id='lolite-plugin-store';w.className='window';w.style.cssText='left:50%;top:8%;transform:translateX(-50%);width:min(900px,92vw);height:min(680px,82vh);z-index:1080';w.innerHTML='<header class="titlebar"><strong>Lolite App Store</strong><div class="controls"><button class="close">×</button></div></header><div class="content"><div class="store-tabs"><button class="primary">Apps & Utilities</button><button class="soft">Widgets</button><button class="soft">Plugins</button></div><div class="cards plugin-grid">'+plugins.map(p=>'<article class="card plugin-card"><span class="app-symbol app-plugin"></span><div><h3>'+p.name+'</h3><small>'+p.type+'</small></div><p class="muted">'+p.desc+'</p><button class="primary" data-plugin="'+p.id+'">'+(installed().includes(p.id)?'Installed':'Install')+'</button></article>').join('')+'</div><p class="muted plugin-note">Plugin-ready architecture: future Lolite apps can register here without changing the desktop shell.</p></div>';document.querySelector('#windows').appendChild(w);w.querySelector('.close').onclick=()=>w.remove();w.querySelectorAll('[data-plugin]').forEach(b=>b.onclick=()=>{const id=b.dataset.plugin;if(installed().includes(id)){toast('Already installed')}else{save([...installed(),id]);b.textContent='Installed';notify('App installed',plugins.find(p=>p.id===id)?.name+' is now available in Lolite.');toast('Plugin installed')}})}
 function quickAction(q){const s=q.toLowerCase();if(/^(open|launch|start)\s+(paint|notepad|calculator|clock|terminal|files|games|settings)/.test(s)){const n=s.replace(/^(open|launch|start)\s+/,'').trim();const map={paint:['paint','Paint'],notepad:['notepad','Notepad'],calculator:['calculator','Calculator'],clock:['clock','Clock'],terminal:['terminal','Terminal'],files:['files','Files'],games:['games','Games'],settings:['settings','Settings']};const x=map[n];if(x&&window.openApp){window.openApp(x[0],x[1],760,540);return true}}if(s.includes('edit display')||s.includes('desktop studio')){window.LoliteV21?.editDisplay?.();return true}if(s==='show notifications'||s.includes('notification center')){notifications();return true}return false}
 window.LolitePlatform={version:V,plugins,installPlugin(id){if(plugins.some(p=>p.id===id))save([...installed(),id])},installed,notify,quickAction};
 const boot=()=>{const task=document.querySelector('#taskbar');if(task&&!task.querySelector('[data-notifications]')){const b=document.createElement('button');b.className='task';b.dataset.notifications='1';b.title='Notification Center';b.textContent='♢';b.onclick=notifications;task.insertBefore(b,task.querySelector('.tray'));}const start=document.querySelector('#start');if(start&&!start.querySelector('[data-appstore-v22]')){const b=document.createElement('button');b.dataset.appstoreV22='1';b.className='start-item';b.innerHTML='<span class="app-symbol app-store"></span><span>Lolite App Store</span>';b.onclick=pluginStore;start.appendChild(b)}notify('Lolite OS updated','Welcome to Lolite OS 2.2. New platform features are ready.');};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,900));else setTimeout(boot,900);
})();